# -*- coding: utf-8 -*-
from app.common.perimeter_variant.registry import (
    CODE_WITH_NT,
    CODE_WITHOUT_NT,
    CODE_WITH_NT_WITH_GAES,
    CODE_WITHOUT_NT_WITH_GAES,
    CODE_WITHOUT_NT_WITH_GAES_WITH_KALININGRAD_ES,
    CODE_O1,
    CODE_WITHOUT_CRIMEA_SEV,
    ENTITY_KIND_CHOICES,
    EntityPerimeterBinding,
    PerimeterVariantDefinition,
    entity_perimeter_bindings,
    filter_query_by_perimeter_variant,
    model_supports_perimeter_variant,
    is_o1_perimeter_variant_code,
    normalize_perimeter_variant_code,
    perimeter_catalog_source,
    resolve_catalog_o1_perimeter_variant_code,
    perimeter_variant_applies_to_year,
    perimeter_variant_definitions,
    resolve_entity_perimeter_variants,
    variant_label_for_entity,
)

__all__ = [
    "CODE_WITH_NT",
    "CODE_WITHOUT_NT",
    "CODE_WITH_NT_WITH_GAES",
    "CODE_WITHOUT_NT_WITH_GAES",
    "CODE_WITHOUT_NT_WITH_GAES_WITH_KALININGRAD_ES",
    "CODE_O1",
    "CODE_WITHOUT_CRIMEA_SEV",
    "ENTITY_KIND_CHOICES",
    "EntityPerimeterBinding",
    "PerimeterVariantDefinition",
    "entity_perimeter_bindings",
    "filter_query_by_perimeter_variant",
    "model_supports_perimeter_variant",
    "is_o1_perimeter_variant_code",
    "normalize_perimeter_variant_code",
    "perimeter_catalog_source",
    "resolve_catalog_o1_perimeter_variant_code",
    "perimeter_variant_applies_to_year",
    "perimeter_variant_definitions",
    "resolve_entity_perimeter_variants",
    "variant_label_for_entity",
]
