SELECT [Станции(архив)].*
FROM [Станции(архив)]
UNION SELECT [Станции2022].*
FROM [Станции2022]
UNION SELECT 
    0 AS name,
    [Станции(Схема)_25-29].year,
    [Станции(Схема)_25-29].nust,
    0 AS nr,
    0 AS E,
    0 AS eotp,
    0 AS eurt,
    0 AS eust,
    0 AS Q,
    0 AS turt,
    0 AS tust,
    0 AS B,
    0 AS gaz,
    0 AS mazut,
    0 AS torf,
    0 AS slan,
    0 AS proch,
    0 AS ugol,
    0 AS don,
    0 AS podm,
    0 AS pech,
    0 AS arkt,
    0 AS kuzn,
    0 AS ural,
    0 AS bashk,
    0 AS kazah,
    0 AS kan,
    0 AS tung,
    0 AS irkut,
    0 AS hak,
    0 AS tuv,
    0 AS bur,
    0 AS chit,
    0 AS yakut,
    0 AS amur,
    0 AS urg,
    0 AS ushum,
    0 AS prim,
    0 AS mag,
    0 AS chukot,
    0 AS kamch,
    0 AS sah,
    0 AS qotr,
    0 AS snk,
    0 AS SNT,
    0 AS ewtp,
    0 AS nt,
    0 AS NTsum,
    [Станции(Схема)_25-29].obor,
    [Станции(Схема)_25-29].ved,
    [Станции(Схема)_25-29].вед,
    [Станции(Схема)_25-29].obl,
    [Станции(Схема)_25-29].dep,
    [Станции(Схема)_25-29].oes,
    [Станции(Схема)_25-29].EES,
    [Станции(Схема)_25-29].er,
    [Станции(Схема)_25-29].gk,
    [Станции(Схема)_25-29].be,
    [Станции(Схема)_25-29].numb1120,
    [Станции(Схема)_25-29].numb1
FROM [Станции(Схема)_25-29]
WHERE Year IN (2023,2024,2025)
ORDER BY [numb1], [year];
