SELECT NAME , numb1120, E, EWTP,EOTP,EUST,EURT,Q,QOTR,TURT,TUST,B,GAZ,MAZUT,UGOL,PROCH, SNK, Snt from [Волга2021]
UNION 
SELECT NAME ,numb1120,E, EWTP,EOTP,EUST,EURT,Q,QOTR,TURT,TUST,B,GAZ,MAZUT,UGOL,PROCH, SNK, Snt from  [Восток2021]
UNION
SELECT NAME , numb1120, E, EWTP,EOTP,EUST,EURT,Q,QOTR,TURT,TUST,B,GAZ,MAZUT,UGOL,PROCH, SNK, Snt from  [Северо_Запад2021]
UNION
SELECT NAME , numb1120, E, EWTP,EOTP,EUST,EURT,Q,QOTR,TURT,TUST,B,GAZ,MAZUT,UGOL,PROCH, SNK, Snt from  [Сибирь2021]
UNION
SELECT NAME , numb1120, E, EWTP,EOTP,EUST,EURT,Q,QOTR,TURT,TUST,B,GAZ,MAZUT,UGOL,PROCH, SNK, Snt from  [Урал2021]
UNION
SELECT NAME , numb1120, E, EWTP,EOTP,EUST,EURT,Q,QOTR,TURT,TUST,B,GAZ,MAZUT,UGOL,PROCH, SNK, Snt from  [Центр2021]
UNION SELECT NAME , numb1120, E, EWTP,EOTP,EUST,EURT,Q,QOTR,TURT,TUST,B,GAZ,MAZUT,UGOL,PROCH, SNK, Snt from  [Юг2021];
