SELECT NAME1, YEAR,NUST,E,Q,B,GAZ, MAZUT, TORF,PROCH,UGOL,DON,PODM,PECH,KUZN,EKIB,KARAG,KAN,numb1/10000 as numb
FROM [ОЭС-итоги]
UNION
SELECT АО as name1, YEAR,NUST,E,Q,B,GAZ, MAZUT, TORF,PROCH,UGOL,DON,PODM,PECH,KUZN,EKIB,KARAG,KAN,numb1 as numb
FROM [ОЭС-области]
UNION SELECT NAME1, YEAR,NUST,E,Q,B,GAZ, MAZUT, TORF,PROCH,UGOL,DON,PODM,PECH,KUZN,EKIB,KARAG,KAN,numb1/1000 as numb
FROM [ОЭС-станции]
ORDER BY numb, year;
