"""Пересоздание миграций

Revision ID: 008627198080
Revises: 8b053f7f64ba
Create Date: 2025-06-30 15:51:31.616603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008627198080'
down_revision = '8b053f7f64ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine_fuels', schema=None) as batch_op:
        batch_op.create_index('ix_machine_fuel_id_year_number', ['year_number'], unique=False)

    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.create_index('ix_station_id_regional_district', ['id_regional_district'], unique=False)
        batch_op.create_index('ix_station_name', ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.drop_index('ix_station_name')
        batch_op.drop_index('ix_station_id_regional_district')

    with op.batch_alter_table('machine_fuels', schema=None) as batch_op:
        batch_op.drop_index('ix_machine_fuel_id_year_number')

    # ### end Alembic commands ###
