"""Добавлена разбивка на агрегаты ПГУ корр

Revision ID: 075db04d97e0
Revises: 17e2d2e7c09f
Create Date: 2025-07-04 16:16:27.492936

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '075db04d97e0'
down_revision = '17e2d2e7c09f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pgu_machine_powers', schema=None) as batch_op:
        batch_op.alter_column('p_ust',
               existing_type=mysql.DECIMAL(precision=25, scale=15),
               nullable=False)

    with op.batch_alter_table('pgu_machines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_equipment_group_pgu', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_pgu_tes_machine_type', sa.Integer(), nullable=True))
        batch_op.alter_column('id_tes_machine_type',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('pgu_machines_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'equipment_groups', ['id_equipment_group_pgu'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'pgu_tes_machine_types', ['id_pgu_tes_machine_type'], ['id'])
        batch_op.drop_column('id_equipment_group')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pgu_machines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_equipment_group', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('pgu_machines_ibfk_1', 'equipment_groups', ['id_equipment_group'], ['id'], ondelete='RESTRICT')
        batch_op.alter_column('id_tes_machine_type',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('id_pgu_tes_machine_type')
        batch_op.drop_column('id_equipment_group_pgu')

    with op.batch_alter_table('pgu_machine_powers', schema=None) as batch_op:
        batch_op.alter_column('p_ust',
               existing_type=mysql.DECIMAL(precision=25, scale=15),
               nullable=True)

    # ### end Alembic commands ###
