"""обновлена модель Station дата ввода убрала

Revision ID: 0a07d5a144af
Revises: 631522bf302d
Create Date: 2025-05-06 12:15:56.094110

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a07d5a144af'
down_revision = '631522bf302d'
branch_labels = None
depends_on = None


def upgrade():
    # Сначала задаём значение по умолчанию для всех NULL
    op.execute("UPDATE machines SET date_exploitation = 'неизвестно' WHERE date_exploitation IS NULL")

    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.alter_column(
            'date_exploitation',
            existing_type=sa.String(length=10),
            type_=sa.Integer(),
            existing_nullable=True,
            existing_server_default=None  # убираем дефолт вовсе
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.alter_column('date_exploitation',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###
