"""обновление моделей Area и Unit

Revision ID: 0ad5755908e3
Revises: 4f6a61553098
Create Date: 2025-04-15 10:40:01.682564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ad5755908e3'
down_revision = '4f6a61553098'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('energy_areas', schema=None) as batch_op:
        # Удаляем добавление уже существующего столбца
        # batch_op.add_column(sa.Column('id_regional_energy_system', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            'fk_energy_areas_regional_energy_system',
            'regional_energy_systems',
            ['id_regional_energy_system'],
            ['id'],
            ondelete='RESTRICT'
        )

    with op.batch_alter_table('energy_units', schema=None) as batch_op:
        # Убираем добавление уже существующей колонки
        batch_op.create_foreign_key(
            'fk_energy_units_regional_energy_system',  # желательно указать имя
            'regional_energy_systems',
            ['id_regional_energy_system'], ['id'],
            ondelete='RESTRICT'
        )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('energy_units', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_regional_energy_system')

    with op.batch_alter_table('energy_areas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_regional_energy_system')

    # ### end Alembic commands ###
