"""Add year_number indexes to StationPower and MachinePower

Revision ID: 17e2d2e7c09f
Revises: 008627198080
Create Date: 2025-07-04 10:36:56.870232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17e2d2e7c09f'
down_revision = '008627198080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine_powers', schema=None) as batch_op:
        batch_op.create_index('ix_machine_power_id_machine', ['id_machine'], unique=False)
        batch_op.create_index('ix_machine_power_year_number', ['year_number'], unique=False)

    with op.batch_alter_table('station_powers', schema=None) as batch_op:
        batch_op.create_index('ix_station_power_id_station', ['id_station'], unique=False)
        batch_op.create_index('ix_station_power_year_number', ['year_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('station_powers', schema=None) as batch_op:
        batch_op.drop_index('ix_station_power_year_number')
        batch_op.drop_index('ix_station_power_id_station')

    with op.batch_alter_table('machine_powers', schema=None) as batch_op:
        batch_op.drop_index('ix_machine_power_year_number')
        batch_op.drop_index('ix_machine_power_id_machine')

    # ### end Alembic commands ###
