"""добавлены параметры техинспекции для машин по ресурсам

Revision ID: 1ee7a39d50f6
Revises: 78658ab94c24
Create Date: 2025-06-06 10:53:15.151158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ee7a39d50f6'
down_revision = '78658ab94c24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_modern', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('year_demontaz', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('resurs_coal', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('resurs_gas', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.drop_column('resurs_gas')
        batch_op.drop_column('resurs_coal')
        batch_op.drop_column('year_demontaz')
        batch_op.drop_column('year_modern')

    # ### end Alembic commands ###
