"""Пересоздание миграций

Revision ID: 33bafce6a387
Revises: 0ad5755908e3
Create Date: 2025-04-15 10:44:15.931381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33bafce6a387'
down_revision = '0ad5755908e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('energy_areas', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'regional_energy_systems', ['id_regional_energy_system'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('energy_units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_regional_energy_system', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'regional_energy_systems', ['id_regional_energy_system'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('energy_units', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_regional_energy_system')

    with op.batch_alter_table('energy_areas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
