"""Пересоздание миграций

Revision ID: 33bc86c53bdc
Revises: 6df72582cdc5
Create Date: 2025-09-19 14:50:37.941369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33bc86c53bdc'
down_revision = '6df72582cdc5'
branch_labels = None
depends_on = None


def upgrade():
    # 1) Добавляем колонку как NULLABLE (иначе упадёт на существующих строках)
    op.add_column(
        "energy_zones",
        sa.Column("id_regional_district", sa.Integer(), nullable=True),
        schema="refdata",
    )

    # 2) Индекс + FK
    op.create_index(
        "ix_refdata_energy_zones_id_regional_district",
        "energy_zones", ["id_regional_district"],
        unique=False, schema="refdata",
    )
    op.create_foreign_key(
        "fk_energy_zones_regional_district",
        "energy_zones", "regional_districts",
        ["id_regional_district"], ["id"],
        source_schema="refdata", referent_schema="refdata",
        ondelete="SET NULL", onupdate="CASCADE",
    )

    # 3) Бэਕфилл: если раньше связь была в regional_districts.id_energy_zone — перенесём
    op.execute("""
    DO $$
    BEGIN
        IF EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema='refdata'
              AND table_name='regional_districts'
              AND column_name='id_energy_zone'
        ) THEN
            UPDATE refdata.energy_zones ez
               SET id_regional_district = rd.id
              FROM refdata.regional_districts rd
             WHERE rd.id_energy_zone = ez.id;
        END IF;
    END$$;
    """)

    # 4) (Опционально) ужесточить до NOT NULL, если пустых больше нет
    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM refdata.energy_zones WHERE id_regional_district IS NULL) THEN
            ALTER TABLE refdata.energy_zones
            ALTER COLUMN id_regional_district SET NOT NULL;
        END IF;
    END$$;
    """)

    # Если у тебя в этой миграции ещё смена типа region_id — оставь:
    try:
        op.alter_column(
            "regional_districts", "region_id",
            existing_type=sa.Integer(),
            type_=sa.String(length=3),
            existing_nullable=True,
            schema="refdata",
        )
    except Exception:
        # если тип уже String(3) — просто пропустим
        pass

def downgrade():
    # Вернуть region_id типом Integer (если меняли)
    try:
        op.alter_column(
            "regional_districts", "region_id",
            existing_type=sa.String(length=3),
            type_=sa.Integer(),
            existing_nullable=True,
            schema="refdata",
        )
    except Exception:
        pass

    # Снять FK/индекс/колонку
    op.drop_constraint(
        "fk_energy_zones_regional_district",
        "energy_zones",
        schema="refdata",
        type_="foreignkey",
    )
    op.drop_index(
        "ix_refdata_energy_zones_id_regional_district",
        table_name="energy_zones",
        schema="refdata",
    )
    op.drop_column("energy_zones", "id_regional_district", schema="refdata")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('regional_districts', 'region_id',
               existing_type=sa.String(length=3),
               type_=sa.INTEGER(),
               existing_nullable=True,
               schema='refdata')
    op.drop_constraint(None, 'energy_zones', schema='refdata', type_='foreignkey')
    op.drop_index(op.f('ix_refdata_energy_zones_id_regional_district'), table_name='energy_zones', schema='refdata')
    op.drop_column('energy_zones', 'id_regional_district', schema='refdata')
    op.drop_constraint(None, 'stations', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'stations', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'stations', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'station_powers', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'pgu_machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'pgu_machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'pgu_machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'pgu_machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'pgu_machine_powers', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machine_tes_types', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machine_tes_types', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machine_powers', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machine_fuels', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machine_fuels', schema='generation', type_='foreignkey')
    # ### end Alembic commands ###
