"""Пересоздание миграций

Revision ID: 3d264d5dd2d0
Revises: 6fc108861fbe
Create Date: 2025-05-07 13:11:03.235436

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d264d5dd2d0'
down_revision = '6fc108861fbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.alter_column('date_exploitation',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text("'не указано'"))

    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stations_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stations_name'))

    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.alter_column('date_exploitation',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True,
               existing_server_default=sa.text("'не указано'"))

    # ### end Alembic commands ###
