"""add_station_power_index

Revision ID: 45cb62e688a6
Revises: 5d2be85a56b8
Create Date: 2025-09-26 15:59:22.486406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45cb62e688a6'
down_revision = '5d2be85a56b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'machine_fuels', 'fuels', ['id_fuel'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machine_fuels', 'years', ['year_number'], ['number'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machine_powers', 'years', ['year_number'], ['number'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machine_tes_types', 'tes_types', ['id_tes_type'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machine_tes_types', 'years', ['year_number'], ['number'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'machine_types', ['id_machine_type'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'condition_types', ['id_condition_type'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'equipment_groups', ['id_equipment_group'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'station_types', ['id_station_type'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'energy_areas', ['id_energy_area'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'gen_companies', ['id_gen_company'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'tes_machine_types', ['id_tes_machine_type'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'pgu_machine_powers', 'years', ['year_number'], ['number'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'pgu_machines', 'pgu_tes_machine_types', ['id_pgu_tes_machine_type'], ['id'], source_schema='generation', referent_schema='refdata')
    op.create_foreign_key(None, 'pgu_machines', 'equipment_groups', ['id_equipment_group_pgu'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'pgu_machines', 'condition_types', ['id_condition_type'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'pgu_machines', 'tes_machine_types', ['id_tes_machine_type'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_index('ix_station_powers_station_year', 'station_powers', ['id_station', 'year_number'], unique=False, schema='generation')
    op.create_foreign_key(None, 'station_powers', 'years', ['year_number'], ['number'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'stations', 'condition_types', ['id_condition_type'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'stations', 'energy_units', ['id_energy_unit'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'stations', 'regional_districts', ['id_regional_district'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stations', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'stations', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'stations', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'station_powers', schema='generation', type_='foreignkey')
    op.drop_index('ix_station_powers_station_year', table_name='station_powers', schema='generation')
    op.drop_constraint(None, 'pgu_machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'pgu_machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'pgu_machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'pgu_machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'pgu_machine_powers', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machine_tes_types', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machine_tes_types', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machine_powers', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machine_fuels', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machine_fuels', schema='generation', type_='foreignkey')
    # ### end Alembic commands ###
