"""Пересоздание миграций

Revision ID: 4f6a61553098
Revises: 98bc287af3d6
Create Date: 2025-04-15 10:27:38.582438

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4f6a61553098'
down_revision = '98bc287af3d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('energy_areas', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'regional_districts', ['id_regional_district'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('energy_units', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=256),
               existing_nullable=False)

    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'energy_units', ['id_energy_unit'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('energy_units', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=False)

    with op.batch_alter_table('energy_areas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('name',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
