"""add_database_version_id_to_years_table

Revision ID: 556bf0fa1b58
Revises: g1d4b3c6e8f9
Create Date: 2025-10-24 11:45:47.184771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '556bf0fa1b58'
down_revision = 'g1d4b3c6e8f9'
branch_labels = None
depends_on = None


def upgrade():
    # Идемпотентно добавляем колонку/индекс/ВК, если их нет
    bind = op.get_bind()
    col_exists = bind.execute(sa.text(
        """
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'refdata'
          AND table_name = 'years'
          AND column_name = 'database_version_id'
        """
    )).fetchone() is not None
    if not col_exists:
        op.add_column('years', sa.Column('database_version_id', sa.Integer(), nullable=True), schema='refdata')

    idx_exists = bind.execute(sa.text(
        """
        SELECT 1 FROM pg_indexes
        WHERE schemaname = 'refdata'
          AND tablename = 'years'
          AND indexname = 'ix_refdata_years_database_version_id'
        """
    )).fetchone() is not None
    if not idx_exists:
        op.create_index(op.f('ix_refdata_years_database_version_id'), 'years', ['database_version_id'], unique=False, schema='refdata')

    # Имя внешнего ключа может быть None в автогенерации — зададим свое и проверим существование
    fk_exists = bind.execute(sa.text(
        """
        SELECT 1
        FROM information_schema.table_constraints tc
        WHERE tc.table_schema = 'refdata'
          AND tc.table_name = 'years'
          AND tc.constraint_type = 'FOREIGN KEY'
          AND tc.constraint_name = 'fk_refdata_years_database_version_id'
        """
    )).fetchone() is not None
    if not fk_exists:
        op.create_foreign_key(
            'fk_refdata_years_database_version_id',
            'years', 'database_versions',
            ['database_version_id'], ['id'],
            source_schema='refdata', referent_schema='generation',
            ondelete='SET NULL'
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'years', type_='foreignkey', schema='refdata')
    op.drop_index(op.f('ix_refdata_years_database_version_id'), table_name='years', schema='refdata')
    op.drop_column('years', 'database_version_id', schema='refdata')
    # ### end Alembic commands ###
