"""скорректированы имена для станций в модели stations + взаимосвязи

Revision ID: 56f09ed7a1f2
Revises: c7bc2be701d7
Create Date: 2025-03-19 14:27:22.606941

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '56f09ed7a1f2'
down_revision = 'c7bc2be701d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_combined', sa.String(length=80), nullable=True))
        batch_op.drop_index('name_compined')
        batch_op.create_unique_constraint(None, ['name_combined'])
        batch_op.drop_column('name_compined')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_compined', mysql.VARCHAR(length=80), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('name_compined', ['name_compined'], unique=True)
        batch_op.drop_column('name_combined')

    # ### end Alembic commands ###
