"""add_performance_indexes

Revision ID: 5d2be85a56b8
Revises: 72928411edc7
Create Date: 2025-09-26 15:56:43.970396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d2be85a56b8'
down_revision = '72928411edc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_machine_fuels_machine_year', 'machine_fuels', ['id_machine', 'year_number'], unique=False, schema='generation')
    op.create_index('ix_machine_powers_station_year', 'machine_powers', ['id_machine', 'year_number'], unique=False, schema='generation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_machine_powers_station_year', table_name='machine_powers', schema='generation')
    op.drop_index('ix_machine_fuels_machine_year', table_name='machine_fuels', schema='generation')
    # ### end Alembic commands ###
