"""initial schema

Revision ID: 5f943277b415
Revises: 
Create Date: 2026-03-12 09:26:07.729450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f943277b415'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gs_business_units',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('name_full', sa.String(length=80), nullable=True),
    sa.Column('name_abr', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('database_version_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('modified_by', sa.String(length=255), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('ref_uuid', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['database_version_id'], ['gs_sys.gs_database_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('database_version_id', 'name', name='uq_refdata_business_units_ver_name'),
    sa.UniqueConstraint('database_version_id', 'name_abr', name='uq_refdata_business_units_ver_name_abr'),
    sa.UniqueConstraint('database_version_id', 'name_full', name='uq_refdata_business_units_ver_name_full'),
    schema='gs_sys'
    )
    op.create_table('gs_departments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('name_full', sa.String(length=80), nullable=True),
    sa.Column('name_abr', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('database_version_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('modified_by', sa.String(length=255), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('ref_uuid', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['database_version_id'], ['gs_sys.gs_database_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('database_version_id', 'name', name='uq_refdata_departments_ver_name'),
    sa.UniqueConstraint('database_version_id', 'name_abr', name='uq_refdata_departments_ver_name_abr'),
    sa.UniqueConstraint('database_version_id', 'name_full', name='uq_refdata_departments_ver_name_full'),
    schema='gs_sys'
    )
    op.create_foreign_key(None, 'user_roles', 'users', ['user_id'], ['id'], source_schema='gs_auth', referent_schema='gs_auth', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_roles', 'roles', ['role_id'], ['id'], source_schema='gs_auth', referent_schema='gs_auth', ondelete='RESTRICT')
    op.create_foreign_key(None, 'users', 'gs_database_versions', ['last_database_version_id'], ['id'], source_schema='gs_auth', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'gs_fue_equipment_group_extra_fuel_param', 'gs_database_versions', ['database_version_id'], ['id'], source_schema='gs_fue', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'gs_fue_equipment_group_fuel_param', 'gs_database_versions', ['database_version_id'], ['id'], source_schema='gs_fue', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'gs_fue_equipment_group_type_stations', 'stations', ['station_id'], ['id'], source_schema='gs_fue', referent_schema='gs_gen', ondelete='RESTRICT')
    op.create_foreign_key(None, 'gs_fue_equipment_group_type_stations', 'gs_database_versions', ['database_version_id'], ['id'], source_schema='gs_fue', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'gs_fue_equipment_group_type_stations', 'gs_equipment_groups', ['equipment_group_type_id'], ['id'], source_schema='gs_fue', referent_schema='gs_sys', ondelete='RESTRICT')
    op.alter_column('gs_fue_equipment_groups', 'niv',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=True,
               schema='gs_fue')
    op.alter_column('gs_fue_equipment_groups', 'comp',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=True,
               schema='gs_fue')
    op.alter_column('gs_fue_equipment_groups', 'main',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=True,
               schema='gs_fue')
    op.alter_column('gs_fue_equipment_groups', 'd',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=True,
               schema='gs_fue')
    op.alter_column('gs_fue_equipment_groups', 'r',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=True,
               schema='gs_fue')
    op.alter_column('gs_fue_equipment_groups', 'forem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=True,
               schema='gs_fue')
    op.alter_column('gs_fue_equipment_groups', 'vedomstvo',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=True,
               schema='gs_fue')
    op.alter_column('gs_fue_equipment_groups', 'obl',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.Integer(),
               existing_nullable=True,
               schema='gs_fue')
    op.alter_column('gs_fue_equipment_groups', 'dep',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.Integer(),
               existing_nullable=True,
               schema='gs_fue')
    op.alter_column('gs_fue_equipment_groups', 'oes',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.Integer(),
               existing_nullable=True,
               schema='gs_fue')
    op.alter_column('gs_fue_equipment_groups', 'er',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.Integer(),
               existing_nullable=True,
               schema='gs_fue')
    op.alter_column('gs_fue_equipment_groups', 'fo',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.Integer(),
               existing_nullable=True,
               schema='gs_fue')
    op.alter_column('gs_fue_equipment_groups', 'numb',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=True,
               schema='gs_fue')
    op.alter_column('gs_fue_equipment_groups', 'codegor',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=True,
               schema='gs_fue')
    op.alter_column('gs_fue_equipment_groups', 'be',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.Integer(),
               existing_nullable=True,
               schema='gs_fue')
    op.alter_column('gs_fue_equipment_groups', 'gk',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.Integer(),
               existing_nullable=True,
               schema='gs_fue')
    op.alter_column('gs_fue_equipment_groups', 'gkf',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.Integer(),
               existing_nullable=True,
               schema='gs_fue')
    op.create_foreign_key(None, 'gs_fue_equipment_groups', 'gs_regional_districts', ['regional_district_id'], ['id'], source_schema='gs_fue', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'gs_fue_equipment_groups', 'gs_regional_energy_systems', ['regional_energy_system_id'], ['id'], source_schema='gs_fue', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'gs_fue_equipment_groups', 'gs_database_versions', ['database_version_id'], ['id'], source_schema='gs_fue', referent_schema='gs_sys', ondelete='SET NULL')
    op.alter_column('gs_fue_machine_fuel_param', 'note',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True,
               schema='gs_fue')
    op.create_foreign_key(None, 'gs_fue_machine_fuel_param', 'gs_database_versions', ['database_version_id'], ['id'], source_schema='gs_fue', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'gs_fue_machine_fuel_param', 'machines', ['machine_id'], ['id'], source_schema='gs_fue', referent_schema='gs_gen', ondelete='CASCADE')
    op.create_foreign_key(None, 'boilers', 'stations', ['id_station'], ['id'], source_schema='gs_gen', referent_schema='gs_gen', ondelete='RESTRICT')
    op.create_foreign_key(None, 'boilers', 'gs_database_versions', ['database_version_id'], ['id'], source_schema='gs_gen', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'documents_kommod', 'gs_database_versions', ['database_version_id'], ['id'], source_schema='gs_gen', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'machine_fuels', 'gs_database_versions', ['database_version_id'], ['id'], source_schema='gs_gen', referent_schema='gs_sys', ondelete='SET NULL')
    # FK на gs_years по одному полю number не создаем, т.к. number не уникален между версиями БД.
    op.create_foreign_key(None, 'machine_fuels', 'gs_fuels', ['id_fuel'], ['id'], source_schema='gs_gen', referent_schema='gs_sys', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machine_fuels', 'machines', ['id_machine'], ['id'], source_schema='gs_gen', referent_schema='gs_gen', ondelete='RESTRICT')
    # Аналогично не создаем FK machine_names/machine_powers/machine_tes_types/pgu_machine_powers/station_powers на gs_years.number
    op.create_foreign_key(None, 'machine_names', 'gs_database_versions', ['database_version_id'], ['id'], source_schema='gs_gen', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'machine_powers', 'machines', ['id_machine'], ['id'], source_schema='gs_gen', referent_schema='gs_gen', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machine_powers', 'gs_database_versions', ['database_version_id'], ['id'], source_schema='gs_gen', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'machine_tes_types', 'gs_tes_types', ['id_tes_type'], ['id'], source_schema='gs_gen', referent_schema='gs_sys', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machine_tes_types', 'gs_database_versions', ['database_version_id'], ['id'], source_schema='gs_gen', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'machine_tes_types', 'machines', ['id_machine'], ['id'], source_schema='gs_gen', referent_schema='gs_gen', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'gs_energy_areas', ['id_energy_area'], ['id'], source_schema='gs_gen', referent_schema='gs_sys', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'gs_machine_types', ['id_machine_type'], ['id'], source_schema='gs_gen', referent_schema='gs_sys', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'gs_tes_machine_types', ['id_tes_machine_type'], ['id'], source_schema='gs_gen', referent_schema='gs_sys', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'gs_technology_types', ['id_technology_type'], ['id'], source_schema='gs_gen', referent_schema='gs_sys', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'gs_technology_availabilities', ['id_technology_availability'], ['id'], source_schema='gs_gen', referent_schema='gs_sys', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'gs_condition_types', ['id_condition_type'], ['id'], source_schema='gs_gen', referent_schema='gs_sys', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'stations', ['id_station'], ['id'], source_schema='gs_gen', referent_schema='gs_gen', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'gs_equipment_groups', ['id_equipment_group'], ['id'], source_schema='gs_gen', referent_schema='gs_sys', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'gs_companies', ['id_gen_company'], ['id'], source_schema='gs_gen', referent_schema='gs_sys', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'gs_database_versions', ['database_version_id'], ['id'], source_schema='gs_gen', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'pgu_machine_powers', 'gs_database_versions', ['database_version_id'], ['id'], source_schema='gs_gen', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'pgu_machine_powers', 'pgu_machines', ['id_pgu_machine'], ['id'], source_schema='gs_gen', referent_schema='gs_gen', ondelete='CASCADE')
    op.create_foreign_key(None, 'pgu_machines', 'gs_tes_machine_types', ['id_tes_machine_type'], ['id'], source_schema='gs_gen', referent_schema='gs_sys', ondelete='RESTRICT')
    op.create_foreign_key(None, 'pgu_machines', 'gs_condition_types', ['id_condition_type'], ['id'], source_schema='gs_gen', referent_schema='gs_sys', ondelete='RESTRICT')
    op.create_foreign_key(None, 'pgu_machines', 'gs_pgu_tes_machine_types', ['id_pgu_tes_machine_type'], ['id'], source_schema='gs_gen', referent_schema='gs_sys')
    op.create_foreign_key(None, 'pgu_machines', 'gs_database_versions', ['database_version_id'], ['id'], source_schema='gs_gen', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'pgu_machines', 'machines', ['id_parent_machine'], ['id'], source_schema='gs_gen', referent_schema='gs_gen', ondelete='CASCADE')
    op.create_foreign_key(None, 'station_groups', 'gs_database_versions', ['database_version_id'], ['id'], source_schema='gs_gen', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'station_powers', 'stations', ['id_station'], ['id'], source_schema='gs_gen', referent_schema='gs_gen', ondelete='RESTRICT')
    op.create_foreign_key(None, 'station_powers', 'gs_database_versions', ['database_version_id'], ['id'], source_schema='gs_gen', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_unique_constraint(None, 'stations', ['name_archive'], schema='gs_gen')
    op.create_unique_constraint(None, 'stations', ['name_combined'], schema='gs_gen')
    op.create_unique_constraint(None, 'stations', ['kto'], schema='gs_gen')
    op.create_unique_constraint(None, 'stations', ['location'], schema='gs_gen')
    op.create_unique_constraint(None, 'stations', ['name_so'], schema='gs_gen')
    op.create_foreign_key(None, 'stations', 'gs_regional_districts', ['id_regional_district'], ['id'], source_schema='gs_gen', referent_schema='gs_sys', ondelete='RESTRICT')
    op.create_foreign_key(None, 'stations', 'gs_station_types', ['id_station_type'], ['id'], source_schema='gs_gen', referent_schema='gs_sys', ondelete='RESTRICT')
    op.create_foreign_key(None, 'stations', 'station_groups', ['id_station_group'], ['id'], source_schema='gs_gen', referent_schema='gs_gen', ondelete='RESTRICT')
    op.create_foreign_key(None, 'stations', 'gs_energy_units', ['id_energy_unit'], ['id'], source_schema='gs_gen', referent_schema='gs_sys', ondelete='RESTRICT')
    op.create_foreign_key(None, 'stations', 'gs_condition_types', ['id_condition_type'], ['id'], source_schema='gs_gen', referent_schema='gs_sys', ondelete='RESTRICT')
    op.create_foreign_key(None, 'stations', 'gs_regional_energy_systems', ['id_regional_energy_system'], ['id'], source_schema='gs_gen', referent_schema='gs_sys', ondelete='RESTRICT')
    op.create_foreign_key(None, 'stations', 'gs_database_versions', ['database_version_id'], ['id'], source_schema='gs_gen', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'logs', 'gs_database_versions', ['database_version_id'], ['id'], source_schema='gs_logs', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'gs_companies', 'gs_database_versions', ['database_version_id'], ['id'], source_schema='gs_sys', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'gs_condition_types', 'gs_database_versions', ['database_version_id'], ['id'], source_schema='gs_sys', referent_schema='gs_sys', ondelete='SET NULL')
    op.alter_column('gs_database_versions', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False,
               schema='gs_sys')
    op.create_foreign_key(None, 'gs_energy_areas', 'gs_regional_districts', ['id_regional_district'], ['id'], source_schema='gs_sys', referent_schema='gs_sys', ondelete='RESTRICT')
    op.create_foreign_key(None, 'gs_energy_areas', 'gs_database_versions', ['database_version_id'], ['id'], source_schema='gs_sys', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'gs_energy_system_types', 'gs_database_versions', ['database_version_id'], ['id'], source_schema='gs_sys', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'gs_energy_units', 'gs_regional_energy_systems', ['id_regional_energy_system'], ['id'], source_schema='gs_sys', referent_schema='gs_sys', ondelete='RESTRICT')
    op.create_foreign_key(None, 'gs_energy_units', 'gs_database_versions', ['database_version_id'], ['id'], source_schema='gs_sys', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'gs_energy_units', 'gs_regional_districts', ['id_regional_district'], ['id'], source_schema='gs_sys', referent_schema='gs_sys', ondelete='RESTRICT')
    op.create_foreign_key(None, 'gs_energy_zones', 'gs_database_versions', ['database_version_id'], ['id'], source_schema='gs_sys', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'gs_equipment_groups', 'gs_database_versions', ['database_version_id'], ['id'], source_schema='gs_sys', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'gs_equipment_groups', 'gs_technology_types', ['id_technology_type'], ['id'], source_schema='gs_sys', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'gs_equipment_groups', 'gs_technology_availabilities', ['id_technology_availability'], ['id'], source_schema='gs_sys', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'gs_federal_districts', 'gs_database_versions', ['database_version_id'], ['id'], source_schema='gs_sys', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'gs_fuel_categories', 'gs_database_versions', ['database_version_id'], ['id'], source_schema='gs_sys', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'gs_fuel_types', 'gs_database_versions', ['database_version_id'], ['id'], source_schema='gs_sys', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'gs_fuels', 'gs_fuel_types', ['id_fuel_type'], ['id'], source_schema='gs_sys', referent_schema='gs_sys', ondelete='RESTRICT')
    op.create_foreign_key(None, 'gs_fuels', 'gs_database_versions', ['database_version_id'], ['id'], source_schema='gs_sys', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'gs_machine_types', 'gs_database_versions', ['database_version_id'], ['id'], source_schema='gs_sys', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'gs_pgu_tes_machine_types', 'gs_database_versions', ['database_version_id'], ['id'], source_schema='gs_sys', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'gs_regional_district_regional_energy_system', 'gs_regional_energy_systems', ['regional_energy_system_id'], ['id'], source_schema='gs_sys', referent_schema='gs_sys', ondelete='RESTRICT')
    op.create_foreign_key(None, 'gs_regional_district_regional_energy_system', 'gs_regional_districts', ['regional_district_id'], ['id'], source_schema='gs_sys', referent_schema='gs_sys', ondelete='RESTRICT')
    op.alter_column('gs_regional_districts', 'name_full',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=255),
               nullable=False,
               schema='gs_sys')
    op.create_foreign_key(None, 'gs_regional_districts', 'gs_database_versions', ['database_version_id'], ['id'], source_schema='gs_sys', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'gs_regional_districts', 'gs_synchronous_areas', ['id_synchronous_area'], ['id'], source_schema='gs_sys', referent_schema='gs_sys', onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'gs_regional_districts', 'gs_federal_districts', ['id_federal_district'], ['id'], source_schema='gs_sys', referent_schema='gs_sys', ondelete='RESTRICT')
    op.create_foreign_key(None, 'gs_regional_districts', 'gs_energy_zones', ['id_energy_zone'], ['id'], source_schema='gs_sys', referent_schema='gs_sys', onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'gs_regional_energy_systems', 'gs_database_versions', ['database_version_id'], ['id'], source_schema='gs_sys', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'gs_regional_energy_systems', 'gs_union_energy_systems', ['id_union_energy_system'], ['id'], source_schema='gs_sys', referent_schema='gs_sys', ondelete='RESTRICT')
    op.create_foreign_key(None, 'gs_station_types', 'gs_database_versions', ['database_version_id'], ['id'], source_schema='gs_sys', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'gs_synchronous_areas', 'gs_database_versions', ['database_version_id'], ['id'], source_schema='gs_sys', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'gs_technology_availabilities', 'gs_database_versions', ['database_version_id'], ['id'], source_schema='gs_sys', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'gs_technology_types', 'gs_database_versions', ['database_version_id'], ['id'], source_schema='gs_sys', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'gs_tes_machine_types', 'gs_database_versions', ['database_version_id'], ['id'], source_schema='gs_sys', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'gs_tes_types', 'gs_database_versions', ['database_version_id'], ['id'], source_schema='gs_sys', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'gs_union_energy_systems', 'gs_database_versions', ['database_version_id'], ['id'], source_schema='gs_sys', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'gs_union_energy_systems', 'gs_energy_system_types', ['id_energy_system_type'], ['id'], source_schema='gs_sys', referent_schema='gs_sys', ondelete='RESTRICT')
    op.create_foreign_key(None, 'gs_year_features', 'gs_database_versions', ['database_version_id'], ['id'], source_schema='gs_sys', referent_schema='gs_sys', ondelete='SET NULL')
    op.create_foreign_key(None, 'gs_years', 'gs_year_features', ['id_year_feature'], ['id'], source_schema='gs_sys', referent_schema='gs_sys', ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gs_years', schema='gs_sys', type_='foreignkey')
    op.drop_constraint(None, 'gs_year_features', schema='gs_sys', type_='foreignkey')
    op.drop_constraint(None, 'gs_union_energy_systems', schema='gs_sys', type_='foreignkey')
    op.drop_constraint(None, 'gs_union_energy_systems', schema='gs_sys', type_='foreignkey')
    op.drop_constraint(None, 'gs_tes_types', schema='gs_sys', type_='foreignkey')
    op.drop_constraint(None, 'gs_tes_machine_types', schema='gs_sys', type_='foreignkey')
    op.drop_constraint(None, 'gs_technology_types', schema='gs_sys', type_='foreignkey')
    op.drop_constraint(None, 'gs_technology_availabilities', schema='gs_sys', type_='foreignkey')
    op.drop_constraint(None, 'gs_synchronous_areas', schema='gs_sys', type_='foreignkey')
    op.drop_constraint(None, 'gs_station_types', schema='gs_sys', type_='foreignkey')
    op.drop_constraint(None, 'gs_regional_energy_systems', schema='gs_sys', type_='foreignkey')
    op.drop_constraint(None, 'gs_regional_energy_systems', schema='gs_sys', type_='foreignkey')
    op.drop_constraint(None, 'gs_regional_districts', schema='gs_sys', type_='foreignkey')
    op.drop_constraint(None, 'gs_regional_districts', schema='gs_sys', type_='foreignkey')
    op.drop_constraint(None, 'gs_regional_districts', schema='gs_sys', type_='foreignkey')
    op.drop_constraint(None, 'gs_regional_districts', schema='gs_sys', type_='foreignkey')
    op.alter_column('gs_regional_districts', 'name_full',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=80),
               nullable=True,
               schema='gs_sys')
    op.drop_constraint(None, 'gs_regional_district_regional_energy_system', schema='gs_sys', type_='foreignkey')
    op.drop_constraint(None, 'gs_regional_district_regional_energy_system', schema='gs_sys', type_='foreignkey')
    op.drop_constraint(None, 'gs_pgu_tes_machine_types', schema='gs_sys', type_='foreignkey')
    op.drop_constraint(None, 'gs_machine_types', schema='gs_sys', type_='foreignkey')
    op.drop_constraint(None, 'gs_fuels', schema='gs_sys', type_='foreignkey')
    op.drop_constraint(None, 'gs_fuels', schema='gs_sys', type_='foreignkey')
    op.drop_constraint(None, 'gs_fuel_types', schema='gs_sys', type_='foreignkey')
    op.drop_constraint(None, 'gs_fuel_categories', schema='gs_sys', type_='foreignkey')
    op.drop_constraint(None, 'gs_federal_districts', schema='gs_sys', type_='foreignkey')
    op.drop_constraint(None, 'gs_equipment_groups', schema='gs_sys', type_='foreignkey')
    op.drop_constraint(None, 'gs_equipment_groups', schema='gs_sys', type_='foreignkey')
    op.drop_constraint(None, 'gs_equipment_groups', schema='gs_sys', type_='foreignkey')
    op.drop_constraint(None, 'gs_energy_zones', schema='gs_sys', type_='foreignkey')
    op.drop_constraint(None, 'gs_energy_units', schema='gs_sys', type_='foreignkey')
    op.drop_constraint(None, 'gs_energy_units', schema='gs_sys', type_='foreignkey')
    op.drop_constraint(None, 'gs_energy_units', schema='gs_sys', type_='foreignkey')
    op.drop_constraint(None, 'gs_energy_system_types', schema='gs_sys', type_='foreignkey')
    op.drop_constraint(None, 'gs_energy_areas', schema='gs_sys', type_='foreignkey')
    op.drop_constraint(None, 'gs_energy_areas', schema='gs_sys', type_='foreignkey')
    op.alter_column('gs_database_versions', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False,
               schema='gs_sys')
    op.drop_constraint(None, 'gs_condition_types', schema='gs_sys', type_='foreignkey')
    op.drop_constraint(None, 'gs_companies', schema='gs_sys', type_='foreignkey')
    op.drop_constraint(None, 'logs', schema='gs_logs', type_='foreignkey')
    op.drop_constraint(None, 'stations', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'stations', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'stations', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'stations', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'stations', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'stations', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'stations', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'stations', schema='gs_gen', type_='unique')
    op.drop_constraint(None, 'stations', schema='gs_gen', type_='unique')
    op.drop_constraint(None, 'stations', schema='gs_gen', type_='unique')
    op.drop_constraint(None, 'stations', schema='gs_gen', type_='unique')
    op.drop_constraint(None, 'stations', schema='gs_gen', type_='unique')
    op.drop_constraint(None, 'station_powers', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'station_powers', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'station_powers', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'station_groups', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'pgu_machines', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'pgu_machines', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'pgu_machines', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'pgu_machines', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'pgu_machines', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'pgu_machine_powers', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'pgu_machine_powers', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'pgu_machine_powers', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'machine_tes_types', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'machine_tes_types', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'machine_tes_types', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'machine_tes_types', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'machine_powers', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'machine_powers', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'machine_powers', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'machine_names', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'machine_names', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'machine_fuels', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'machine_fuels', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'machine_fuels', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'machine_fuels', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'documents_kommod', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'boilers', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'boilers', schema='gs_gen', type_='foreignkey')
    op.drop_constraint(None, 'gs_fue_machine_fuel_param', schema='gs_fue', type_='foreignkey')
    op.drop_constraint(None, 'gs_fue_machine_fuel_param', schema='gs_fue', type_='foreignkey')
    op.alter_column('gs_fue_machine_fuel_param', 'note',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True,
               schema='gs_fue')
    op.drop_constraint(None, 'gs_fue_equipment_groups', schema='gs_fue', type_='foreignkey')
    op.drop_constraint(None, 'gs_fue_equipment_groups', schema='gs_fue', type_='foreignkey')
    op.drop_constraint(None, 'gs_fue_equipment_groups', schema='gs_fue', type_='foreignkey')
    op.alter_column('gs_fue_equipment_groups', 'gkf',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True,
               schema='gs_fue')
    op.alter_column('gs_fue_equipment_groups', 'gk',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True,
               schema='gs_fue')
    op.alter_column('gs_fue_equipment_groups', 'be',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True,
               schema='gs_fue')
    op.alter_column('gs_fue_equipment_groups', 'codegor',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True,
               schema='gs_fue')
    op.alter_column('gs_fue_equipment_groups', 'numb',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True,
               schema='gs_fue')
    op.alter_column('gs_fue_equipment_groups', 'fo',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True,
               schema='gs_fue')
    op.alter_column('gs_fue_equipment_groups', 'er',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True,
               schema='gs_fue')
    op.alter_column('gs_fue_equipment_groups', 'oes',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True,
               schema='gs_fue')
    op.alter_column('gs_fue_equipment_groups', 'dep',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True,
               schema='gs_fue')
    op.alter_column('gs_fue_equipment_groups', 'obl',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True,
               schema='gs_fue')
    op.alter_column('gs_fue_equipment_groups', 'vedomstvo',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True,
               schema='gs_fue')
    op.alter_column('gs_fue_equipment_groups', 'forem',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True,
               schema='gs_fue')
    op.alter_column('gs_fue_equipment_groups', 'r',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True,
               schema='gs_fue')
    op.alter_column('gs_fue_equipment_groups', 'd',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True,
               schema='gs_fue')
    op.alter_column('gs_fue_equipment_groups', 'main',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True,
               schema='gs_fue')
    op.alter_column('gs_fue_equipment_groups', 'comp',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True,
               schema='gs_fue')
    op.alter_column('gs_fue_equipment_groups', 'niv',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True,
               schema='gs_fue')
    op.drop_constraint(None, 'gs_fue_equipment_group_type_stations', schema='gs_fue', type_='foreignkey')
    op.drop_constraint(None, 'gs_fue_equipment_group_type_stations', schema='gs_fue', type_='foreignkey')
    op.drop_constraint(None, 'gs_fue_equipment_group_type_stations', schema='gs_fue', type_='foreignkey')
    op.drop_constraint(None, 'gs_fue_equipment_group_fuel_param', schema='gs_fue', type_='foreignkey')
    op.drop_constraint(None, 'gs_fue_equipment_group_extra_fuel_param', schema='gs_fue', type_='foreignkey')
    op.drop_constraint(None, 'users', schema='gs_auth', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', schema='gs_auth', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', schema='gs_auth', type_='foreignkey')
    op.drop_table('gs_departments', schema='gs_sys')
    op.drop_table('gs_business_units', schema='gs_sys')
    # ### end Alembic commands ###
