"""обновлена модель Station в части уникальности названия в привязке к субъекту

Revision ID: 5fbfe53b59eb
Revises: 65165c595ac1
Create Date: 2025-05-07 09:57:52.799244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fbfe53b59eb'
down_revision = '65165c595ac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_station_name_district', ['name', 'id_regional_district'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.drop_constraint('uq_station_name_district', type_='unique')

    # ### end Alembic commands ###
