"""обновлена модель Station мощность +

Revision ID: 631522bf302d
Revises: 546477b62d49
Create Date: 2025-05-05 15:58:03.677192

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '631522bf302d'
down_revision = '546477b62d49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine_powers', schema=None) as batch_op:
        batch_op.alter_column('p_ust',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=25, scale=15),
               existing_nullable=True)
        batch_op.alter_column('p_ogr',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=25, scale=15),
               existing_nullable=True)
        batch_op.alter_column('p_rasp',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=25, scale=15),
               existing_nullable=True)

    with op.batch_alter_table('station_powers', schema=None) as batch_op:
        batch_op.alter_column('p_ust',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=25, scale=15),
               existing_nullable=True)
        batch_op.alter_column('p_ogr',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=25, scale=15),
               existing_nullable=True)
        batch_op.alter_column('p_rasp',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=25, scale=15),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('station_powers', schema=None) as batch_op:
        batch_op.alter_column('p_rasp',
               existing_type=sa.Numeric(precision=25, scale=15),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('p_ogr',
               existing_type=sa.Numeric(precision=25, scale=15),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('p_ust',
               existing_type=sa.Numeric(precision=25, scale=15),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('machine_powers', schema=None) as batch_op:
        batch_op.alter_column('p_rasp',
               existing_type=sa.Numeric(precision=25, scale=15),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('p_ogr',
               existing_type=sa.Numeric(precision=25, scale=15),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('p_ust',
               existing_type=sa.Numeric(precision=25, scale=15),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###
