"""обновлена модель Machine

Revision ID: 6b4fb40fff93
Revises: e830376ebb7f
Create Date: 2025-04-23 10:04:42.440775

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b4fb40fff93'
down_revision = 'e830376ebb7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aggregated_power', schema=None) as batch_op:
        batch_op.drop_index('uq_aggregated_power')

    op.drop_table('aggregated_power')
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.drop_constraint('machines_ibfk_7', type_='foreignkey')
        batch_op.drop_column('id_tes_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_tes_type', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('machines_ibfk_7', 'tes_types', ['id_tes_type'], ['id'], ondelete='RESTRICT')

    op.create_table('aggregated_power',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('level', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('level_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('p_ust', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('p_ogr', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('p_rasp', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('aggregated_power', schema=None) as batch_op:
        batch_op.create_index('uq_aggregated_power', ['year', 'level', 'level_id'], unique=True)

    # ### end Alembic commands ###
