"""исправлена модель eneryunit

Revision ID: 6df72582cdc5
Revises: 87b144d908db
Create Date: 2025-09-19 13:04:31.261275

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6df72582cdc5'
down_revision = '87b144d908db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_generation_station_groups_name', table_name='station_groups')
    op.drop_table('station_groups')
    op.drop_index('ix_refdata_fuels_id_fuel_type', table_name='fuels')
    op.drop_index('ix_refdata_fuels_name', table_name='fuels')
    op.drop_table('fuels')
    op.drop_index('ix_refdata_energy_areas_id_regional_district', table_name='energy_areas')
    op.drop_index('ix_refdata_energy_areas_name', table_name='energy_areas')
    op.drop_table('energy_areas')
    op.drop_index('ix_auth_roles_name', table_name='roles')
    op.drop_index('ix_auth_roles_name_full', table_name='roles')
    op.drop_table('roles')
    op.drop_index('ix_auth_users_email', table_name='users')
    op.drop_index('ix_auth_users_username', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_refdata_tes_types_name', table_name='tes_types')
    op.drop_table('tes_types')
    op.drop_index('ix_refdata_federal_districts_name', table_name='federal_districts')
    op.drop_table('federal_districts')
    op.drop_index('ix_generation_machine_fuels_id_fuel', table_name='machine_fuels')
    op.drop_index('ix_generation_machine_fuels_id_machine', table_name='machine_fuels')
    op.drop_index('ix_generation_machine_fuels_year_number', table_name='machine_fuels')
    op.drop_index('ix_machine_fuel_id_fuel', table_name='machine_fuels')
    op.drop_index('ix_machine_fuel_id_machine', table_name='machine_fuels')
    op.drop_index('ix_machine_fuel_id_year_number', table_name='machine_fuels')
    op.drop_table('machine_fuels')
    op.drop_index('ix_generation_station_powers_id_station', table_name='station_powers')
    op.drop_index('ix_generation_station_powers_year_number', table_name='station_powers')
    op.drop_index('ix_station_power_id_station', table_name='station_powers')
    op.drop_index('ix_station_power_year_number', table_name='station_powers')
    op.drop_table('station_powers')
    op.drop_index('ix_logs_logs_action', table_name='logs')
    op.drop_index('ix_logs_logs_timestamp', table_name='logs')
    op.drop_index('ix_logs_logs_username', table_name='logs')
    op.drop_table('logs')
    op.drop_index('ix_refdata_equipment_groups_name', table_name='equipment_groups')
    op.drop_table('equipment_groups')
    op.drop_index('ix_refdata_fuel_types_name', table_name='fuel_types')
    op.drop_table('fuel_types')
    op.drop_index('ix_generation_machines_id_condition_type', table_name='machines')
    op.drop_index('ix_generation_machines_id_energy_area', table_name='machines')
    op.drop_index('ix_generation_machines_id_equipment_group', table_name='machines')
    op.drop_index('ix_generation_machines_id_gen_company', table_name='machines')
    op.drop_index('ix_generation_machines_id_machine_type', table_name='machines')
    op.drop_index('ix_generation_machines_id_station', table_name='machines')
    op.drop_index('ix_generation_machines_id_station_type', table_name='machines')
    op.drop_index('ix_generation_machines_id_tes_machine_type', table_name='machines')
    op.drop_index('ix_generation_machines_machine_name', table_name='machines')
    op.drop_index('ix_generation_machines_machine_number', table_name='machines')
    op.drop_index('ix_machine_date_decompressing_expected', table_name='machines')
    op.drop_index('ix_machine_date_exploitation', table_name='machines')
    op.drop_index('ix_machine_date_modernization_expected', table_name='machines')
    op.drop_index('ix_machine_id_condition_type', table_name='machines')
    op.drop_index('ix_machine_id_energy_area', table_name='machines')
    op.drop_index('ix_machine_id_equipment_group', table_name='machines')
    op.drop_index('ix_machine_id_gen_company', table_name='machines')
    op.drop_index('ix_machine_id_station', table_name='machines')
    op.drop_index('ix_machine_id_station_type', table_name='machines')
    op.drop_index('ix_machine_id_tes_machine_type', table_name='machines')
    op.drop_table('machines')
    op.drop_index('ix_refdata_regional_district_regional_energy_system_reg_56e6', table_name='regional_district_regional_energy_system')
    op.drop_index('ix_refdata_regional_district_regional_energy_system_reg_e9e7', table_name='regional_district_regional_energy_system')
    op.drop_table('regional_district_regional_energy_system')
    op.drop_index('ix_generation_machine_powers_id_machine', table_name='machine_powers')
    op.drop_index('ix_generation_machine_powers_year_number', table_name='machine_powers')
    op.drop_index('ix_machine_power_id_machine', table_name='machine_powers')
    op.drop_index('ix_machine_power_year_number', table_name='machine_powers')
    op.drop_table('machine_powers')
    op.drop_index('ix_refdata_energy_zones_name', table_name='energy_zones')
    op.drop_index('ix_refdata_energy_zones_number', table_name='energy_zones')
    op.drop_table('energy_zones')
    op.drop_index('ix_generation_pgu_machines_id_condition_type', table_name='pgu_machines')
    op.drop_index('ix_generation_pgu_machines_id_equipment_group_pgu', table_name='pgu_machines')
    op.drop_index('ix_generation_pgu_machines_id_parent_machine', table_name='pgu_machines')
    op.drop_index('ix_generation_pgu_machines_id_pgu_tes_machine_type', table_name='pgu_machines')
    op.drop_index('ix_generation_pgu_machines_id_tes_machine_type', table_name='pgu_machines')
    op.drop_index('ix_generation_pgu_machines_machine_name', table_name='pgu_machines')
    op.drop_index('ix_generation_pgu_machines_machine_number', table_name='pgu_machines')
    op.drop_index('ix_pgu_machine_id_condition_type', table_name='pgu_machines')
    op.drop_index('ix_pgu_machine_id_equipment_group_pgu', table_name='pgu_machines')
    op.drop_index('ix_pgu_machine_id_parent_machine', table_name='pgu_machines')
    op.drop_index('ix_pgu_machine_id_tes_machine_type', table_name='pgu_machines')
    op.drop_table('pgu_machines')
    op.drop_index('ix_refdata_energy_units_id_regional_district', table_name='energy_units')
    op.drop_index('ix_refdata_energy_units_id_regional_energy_system', table_name='energy_units')
    op.drop_index('ix_refdata_energy_units_name', table_name='energy_units')
    op.drop_table('energy_units')
    op.drop_index('ix_refdata_years_id_year_feature', table_name='years')
    op.drop_index('ix_refdata_years_number', table_name='years')
    op.drop_table('years')
    op.drop_index('ix_refdata_fuel_categories_name', table_name='fuel_categories')
    op.drop_table('fuel_categories')
    op.drop_index('ix_refdata_regional_energy_systems_id_union_energy_system', table_name='regional_energy_systems')
    op.drop_index('ix_refdata_regional_energy_systems_name', table_name='regional_energy_systems')
    op.drop_table('regional_energy_systems')
    op.drop_index('ix_refdata_machine_types_name', table_name='machine_types')
    op.drop_table('machine_types')
    op.drop_index('ix_refdata_energy_system_types_name', table_name='energy_system_types')
    op.drop_table('energy_system_types')
    op.drop_index('ix_refdata_union_energy_systems_id_energy_system_type', table_name='union_energy_systems')
    op.drop_index('ix_refdata_union_energy_systems_name', table_name='union_energy_systems')
    op.drop_table('union_energy_systems')
    op.drop_index('ix_refdata_year_features_name', table_name='year_features')
    op.drop_table('year_features')
    op.drop_table('alembic_version', schema='auth')
    op.drop_index('ix_refdata_gen_companies_name', table_name='gen_companies')
    op.drop_table('gen_companies')
    op.drop_index('ix_generation_boilers_id_station', table_name='boilers')
    op.drop_index('ix_generation_boilers_name', table_name='boilers')
    op.drop_table('boilers')
    op.drop_index('ix_refdata_tes_machine_types_name', table_name='tes_machine_types')
    op.drop_table('tes_machine_types')
    op.drop_index('ix_generation_machine_tes_types_id_machine', table_name='machine_tes_types')
    op.drop_index('ix_generation_machine_tes_types_id_tes_type', table_name='machine_tes_types')
    op.drop_index('ix_generation_machine_tes_types_year_number', table_name='machine_tes_types')
    op.drop_index('ix_machine_tes_type_id_machine', table_name='machine_tes_types')
    op.drop_index('ix_machine_tes_type_id_tes_type', table_name='machine_tes_types')
    op.drop_index('ix_machine_tes_type_year_number', table_name='machine_tes_types')
    op.drop_table('machine_tes_types')
    op.drop_index('ix_generation_stations_id_condition_type', table_name='stations')
    op.drop_index('ix_generation_stations_id_energy_unit', table_name='stations')
    op.drop_index('ix_generation_stations_id_regional_district', table_name='stations')
    op.drop_index('ix_generation_stations_id_station_group', table_name='stations')
    op.drop_index('ix_station_id_regional_district', table_name='stations')
    op.drop_index('ix_station_id_station_group', table_name='stations')
    op.drop_index('ix_station_name', table_name='stations')
    op.drop_table('stations')
    op.drop_index('ix_refdata_regional_districts_id_energy_zone', table_name='regional_districts')
    op.drop_index('ix_refdata_regional_districts_id_federal_district', table_name='regional_districts')
    op.drop_index('ix_refdata_regional_districts_id_synchronous_area', table_name='regional_districts')
    op.drop_index('ix_refdata_regional_districts_name', table_name='regional_districts')
    op.drop_index('ix_refdata_regional_districts_region_id', table_name='regional_districts')
    op.drop_index('ix_refdata_regional_districts_region_number', table_name='regional_districts')
    op.drop_table('regional_districts')
    op.drop_index('ix_refdata_synchronous_areas_name', table_name='synchronous_areas')
    op.drop_index('ix_refdata_synchronous_areas_number', table_name='synchronous_areas')
    op.drop_table('synchronous_areas')
    op.drop_index('ix_refdata_condition_types_name', table_name='condition_types')
    op.drop_table('condition_types')
    op.drop_index('ix_generation_pgu_machine_powers_id_pgu_machine', table_name='pgu_machine_powers')
    op.drop_index('ix_generation_pgu_machine_powers_year_number', table_name='pgu_machine_powers')
    op.drop_index('ix_pgu_machine_power_id_pgu_machine', table_name='pgu_machine_powers')
    op.drop_index('ix_pgu_machine_power_year_number', table_name='pgu_machine_powers')
    op.drop_table('pgu_machine_powers')
    op.drop_index('ix_refdata_station_types_name', table_name='station_types')
    op.drop_table('station_types')
    op.drop_index('ix_refdata_pgu_tes_machine_types_name', table_name='pgu_tes_machine_types')
    op.drop_table('pgu_tes_machine_types')
    op.drop_table('user_roles')
    op.drop_constraint('machine_fuels_year_number_fkey', 'machine_fuels', schema='generation', type_='foreignkey')
    op.drop_constraint('machine_fuels_id_fuel_fkey', 'machine_fuels', schema='generation', type_='foreignkey')
    op.create_foreign_key(None, 'machine_fuels', 'years', ['year_number'], ['number'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machine_fuels', 'fuels', ['id_fuel'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.drop_constraint('machine_powers_year_number_fkey', 'machine_powers', schema='generation', type_='foreignkey')
    op.create_foreign_key(None, 'machine_powers', 'years', ['year_number'], ['number'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.drop_constraint('machine_tes_types_id_tes_type_fkey', 'machine_tes_types', schema='generation', type_='foreignkey')
    op.drop_constraint('machine_tes_types_year_number_fkey', 'machine_tes_types', schema='generation', type_='foreignkey')
    op.create_foreign_key(None, 'machine_tes_types', 'tes_types', ['id_tes_type'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machine_tes_types', 'years', ['year_number'], ['number'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.drop_constraint('machines_id_equipment_group_fkey', 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint('machines_id_energy_area_fkey', 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint('machines_id_gen_company_fkey', 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint('machines_id_machine_type_fkey', 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint('machines_id_condition_type_fkey', 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint('machines_id_tes_machine_type_fkey', 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint('machines_id_station_type_fkey', 'machines', schema='generation', type_='foreignkey')
    op.create_foreign_key(None, 'machines', 'condition_types', ['id_condition_type'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'tes_machine_types', ['id_tes_machine_type'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'gen_companies', ['id_gen_company'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'energy_areas', ['id_energy_area'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'equipment_groups', ['id_equipment_group'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'machine_types', ['id_machine_type'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'station_types', ['id_station_type'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.drop_constraint('pgu_machine_powers_year_number_fkey', 'pgu_machine_powers', schema='generation', type_='foreignkey')
    op.create_foreign_key(None, 'pgu_machine_powers', 'years', ['year_number'], ['number'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.drop_constraint('pgu_machines_id_tes_machine_type_fkey', 'pgu_machines', schema='generation', type_='foreignkey')
    op.drop_constraint('pgu_machines_id_condition_type_fkey', 'pgu_machines', schema='generation', type_='foreignkey')
    op.drop_constraint('pgu_machines_id_equipment_group_pgu_fkey', 'pgu_machines', schema='generation', type_='foreignkey')
    op.drop_constraint('pgu_machines_id_pgu_tes_machine_type_fkey', 'pgu_machines', schema='generation', type_='foreignkey')
    op.create_foreign_key(None, 'pgu_machines', 'equipment_groups', ['id_equipment_group_pgu'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'pgu_machines', 'pgu_tes_machine_types', ['id_pgu_tes_machine_type'], ['id'], source_schema='generation', referent_schema='refdata')
    op.create_foreign_key(None, 'pgu_machines', 'tes_machine_types', ['id_tes_machine_type'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'pgu_machines', 'condition_types', ['id_condition_type'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.drop_constraint('station_powers_year_number_fkey', 'station_powers', schema='generation', type_='foreignkey')
    op.create_foreign_key(None, 'station_powers', 'years', ['year_number'], ['number'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.drop_constraint('stations_id_regional_district_fkey', 'stations', schema='generation', type_='foreignkey')
    op.drop_constraint('stations_id_energy_unit_fkey', 'stations', schema='generation', type_='foreignkey')
    op.drop_constraint('stations_id_condition_type_fkey', 'stations', schema='generation', type_='foreignkey')
    op.create_foreign_key(None, 'stations', 'energy_units', ['id_energy_unit'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'stations', 'regional_districts', ['id_regional_district'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'stations', 'condition_types', ['id_condition_type'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.add_column('energy_zones', sa.Column('id_regional_district', sa.Integer(), nullable=False), schema='refdata')
    op.create_index(op.f('ix_refdata_energy_zones_id_regional_district'), 'energy_zones', ['id_regional_district'], unique=False, schema='refdata')
    op.create_foreign_key(None, 'energy_zones', 'regional_districts', ['id_regional_district'], ['id'], source_schema='refdata', referent_schema='refdata', ondelete='RESTRICT')
    op.alter_column('regional_districts', 'region_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=3),
               existing_nullable=True,
               schema='refdata')
    op.drop_index('ix_refdata_regional_districts_id_energy_zone', table_name='regional_districts', schema='refdata')
    op.drop_constraint('rd_id_energy_zone_fkey', 'regional_districts', schema='refdata', type_='foreignkey')
    op.drop_column('regional_districts', 'id_energy_zone', schema='refdata')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regional_districts', sa.Column('id_energy_zone', sa.INTEGER(), autoincrement=False, nullable=True), schema='refdata')
    op.create_foreign_key('rd_id_energy_zone_fkey', 'regional_districts', 'energy_zones', ['id_energy_zone'], ['id'], source_schema='refdata', referent_schema='refdata', onupdate='CASCADE', ondelete='SET NULL')
    op.create_index('ix_refdata_regional_districts_id_energy_zone', 'regional_districts', ['id_energy_zone'], unique=False, schema='refdata')
    op.alter_column('regional_districts', 'region_id',
               existing_type=sa.String(length=3),
               type_=sa.INTEGER(),
               existing_nullable=True,
               schema='refdata')
    op.drop_constraint(None, 'energy_zones', schema='refdata', type_='foreignkey')
    op.drop_index(op.f('ix_refdata_energy_zones_id_regional_district'), table_name='energy_zones', schema='refdata')
    op.drop_column('energy_zones', 'id_regional_district', schema='refdata')
    op.drop_constraint(None, 'stations', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'stations', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'stations', schema='generation', type_='foreignkey')
    op.create_foreign_key('stations_id_condition_type_fkey', 'stations', 'condition_types', ['id_condition_type'], ['id'], source_schema='generation', ondelete='RESTRICT')
    op.create_foreign_key('stations_id_energy_unit_fkey', 'stations', 'energy_units', ['id_energy_unit'], ['id'], source_schema='generation', ondelete='RESTRICT')
    op.create_foreign_key('stations_id_regional_district_fkey', 'stations', 'regional_districts', ['id_regional_district'], ['id'], source_schema='generation', ondelete='RESTRICT')
    op.drop_constraint(None, 'station_powers', schema='generation', type_='foreignkey')
    op.create_foreign_key('station_powers_year_number_fkey', 'station_powers', 'years', ['year_number'], ['number'], source_schema='generation', ondelete='RESTRICT')
    op.drop_constraint(None, 'pgu_machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'pgu_machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'pgu_machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'pgu_machines', schema='generation', type_='foreignkey')
    op.create_foreign_key('pgu_machines_id_pgu_tes_machine_type_fkey', 'pgu_machines', 'pgu_tes_machine_types', ['id_pgu_tes_machine_type'], ['id'], source_schema='generation')
    op.create_foreign_key('pgu_machines_id_equipment_group_pgu_fkey', 'pgu_machines', 'equipment_groups', ['id_equipment_group_pgu'], ['id'], source_schema='generation', ondelete='RESTRICT')
    op.create_foreign_key('pgu_machines_id_condition_type_fkey', 'pgu_machines', 'condition_types', ['id_condition_type'], ['id'], source_schema='generation', ondelete='RESTRICT')
    op.create_foreign_key('pgu_machines_id_tes_machine_type_fkey', 'pgu_machines', 'tes_machine_types', ['id_tes_machine_type'], ['id'], source_schema='generation', ondelete='RESTRICT')
    op.drop_constraint(None, 'pgu_machine_powers', schema='generation', type_='foreignkey')
    op.create_foreign_key('pgu_machine_powers_year_number_fkey', 'pgu_machine_powers', 'years', ['year_number'], ['number'], source_schema='generation', ondelete='RESTRICT')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.create_foreign_key('machines_id_station_type_fkey', 'machines', 'station_types', ['id_station_type'], ['id'], source_schema='generation', ondelete='RESTRICT')
    op.create_foreign_key('machines_id_tes_machine_type_fkey', 'machines', 'tes_machine_types', ['id_tes_machine_type'], ['id'], source_schema='generation', ondelete='RESTRICT')
    op.create_foreign_key('machines_id_condition_type_fkey', 'machines', 'condition_types', ['id_condition_type'], ['id'], source_schema='generation', ondelete='RESTRICT')
    op.create_foreign_key('machines_id_machine_type_fkey', 'machines', 'machine_types', ['id_machine_type'], ['id'], source_schema='generation', ondelete='RESTRICT')
    op.create_foreign_key('machines_id_gen_company_fkey', 'machines', 'gen_companies', ['id_gen_company'], ['id'], source_schema='generation', ondelete='RESTRICT')
    op.create_foreign_key('machines_id_energy_area_fkey', 'machines', 'energy_areas', ['id_energy_area'], ['id'], source_schema='generation', ondelete='RESTRICT')
    op.create_foreign_key('machines_id_equipment_group_fkey', 'machines', 'equipment_groups', ['id_equipment_group'], ['id'], source_schema='generation', ondelete='RESTRICT')
    op.drop_constraint(None, 'machine_tes_types', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machine_tes_types', schema='generation', type_='foreignkey')
    op.create_foreign_key('machine_tes_types_year_number_fkey', 'machine_tes_types', 'years', ['year_number'], ['number'], source_schema='generation', ondelete='RESTRICT')
    op.create_foreign_key('machine_tes_types_id_tes_type_fkey', 'machine_tes_types', 'tes_types', ['id_tes_type'], ['id'], source_schema='generation', ondelete='RESTRICT')
    op.drop_constraint(None, 'machine_powers', schema='generation', type_='foreignkey')
    op.create_foreign_key('machine_powers_year_number_fkey', 'machine_powers', 'years', ['year_number'], ['number'], source_schema='generation', ondelete='RESTRICT')
    op.drop_constraint(None, 'machine_fuels', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machine_fuels', schema='generation', type_='foreignkey')
    op.create_foreign_key('machine_fuels_id_fuel_fkey', 'machine_fuels', 'fuels', ['id_fuel'], ['id'], source_schema='generation', ondelete='RESTRICT')
    op.create_foreign_key('machine_fuels_year_number_fkey', 'machine_fuels', 'years', ['year_number'], ['number'], source_schema='generation', ondelete='RESTRICT')
    op.create_table('user_roles',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='user_roles_role_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_roles_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name='user_roles_pkey')
    )
    op.create_table('pgu_tes_machine_types',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('pgu_tes_machine_types_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pgu_tes_machine_types_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_refdata_pgu_tes_machine_types_name', 'pgu_tes_machine_types', ['name'], unique=True)
    op.create_table('station_types',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('station_types_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='station_types_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_refdata_station_types_name', 'station_types', ['name'], unique=True)
    op.create_table('pgu_machine_powers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('year_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_pgu_machine', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('p_ust', sa.NUMERIC(precision=25, scale=15), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_pgu_machine'], ['pgu_machines.id'], name='pgu_machine_powers_id_pgu_machine_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['year_number'], ['years.number'], name='pgu_machine_powers_year_number_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='pgu_machine_powers_pkey')
    )
    op.create_index('ix_pgu_machine_power_year_number', 'pgu_machine_powers', ['year_number'], unique=False)
    op.create_index('ix_pgu_machine_power_id_pgu_machine', 'pgu_machine_powers', ['id_pgu_machine'], unique=False)
    op.create_index('ix_generation_pgu_machine_powers_year_number', 'pgu_machine_powers', ['year_number'], unique=False)
    op.create_index('ix_generation_pgu_machine_powers_id_pgu_machine', 'pgu_machine_powers', ['id_pgu_machine'], unique=False)
    op.create_table('condition_types',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('condition_types_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='condition_types_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_refdata_condition_types_name', 'condition_types', ['name'], unique=True)
    op.create_table('synchronous_areas',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('synchronous_areas_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('number', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='synchronous_areas_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_refdata_synchronous_areas_number', 'synchronous_areas', ['number'], unique=True)
    op.create_index('ix_refdata_synchronous_areas_name', 'synchronous_areas', ['name'], unique=True)
    op.create_table('regional_districts',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('regional_districts_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('region_number', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('name_full', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('id_federal_district', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_energy_zone', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_synchronous_area', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_energy_zone'], ['energy_zones.id'], name='rd_id_energy_zone_fkey', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_federal_district'], ['federal_districts.id'], name='regional_districts_id_federal_district_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_synchronous_area'], ['synchronous_areas.id'], name='rd_id_synchronous_area_fkey', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='regional_districts_pkey'),
    sa.UniqueConstraint('name_full', name='regional_districts_name_full_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_refdata_regional_districts_region_number', 'regional_districts', ['region_number'], unique=False)
    op.create_index('ix_refdata_regional_districts_region_id', 'regional_districts', ['region_id'], unique=False)
    op.create_index('ix_refdata_regional_districts_name', 'regional_districts', ['name'], unique=True)
    op.create_index('ix_refdata_regional_districts_id_synchronous_area', 'regional_districts', ['id_synchronous_area'], unique=False)
    op.create_index('ix_refdata_regional_districts_id_federal_district', 'regional_districts', ['id_federal_district'], unique=False)
    op.create_index('ix_refdata_regional_districts_id_energy_zone', 'regional_districts', ['id_energy_zone'], unique=False)
    op.create_table('stations',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('stations_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('id_condition_type', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name_so', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('name_combined', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('name_archive', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('id_regional_district', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_energy_unit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('kto', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('note', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('id_station_group', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_condition_type'], ['condition_types.id'], name='stations_id_condition_type_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_energy_unit'], ['energy_units.id'], name='stations_id_energy_unit_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_regional_district'], ['regional_districts.id'], name='stations_id_regional_district_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_station_group'], ['station_groups.id'], name='stations_id_station_group_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='stations_pkey'),
    sa.UniqueConstraint('kto', name='stations_kto_key'),
    sa.UniqueConstraint('location', name='stations_location_key'),
    sa.UniqueConstraint('name', 'id_regional_district', name='uq_station_name_district'),
    sa.UniqueConstraint('name_archive', name='stations_name_archive_key'),
    sa.UniqueConstraint('name_combined', name='stations_name_combined_key'),
    sa.UniqueConstraint('name_so', name='stations_name_so_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_station_name', 'stations', ['name'], unique=False)
    op.create_index('ix_station_id_station_group', 'stations', ['id_station_group'], unique=False)
    op.create_index('ix_station_id_regional_district', 'stations', ['id_regional_district'], unique=False)
    op.create_index('ix_generation_stations_id_station_group', 'stations', ['id_station_group'], unique=False)
    op.create_index('ix_generation_stations_id_regional_district', 'stations', ['id_regional_district'], unique=False)
    op.create_index('ix_generation_stations_id_energy_unit', 'stations', ['id_energy_unit'], unique=False)
    op.create_index('ix_generation_stations_id_condition_type', 'stations', ['id_condition_type'], unique=False)
    op.create_table('machine_tes_types',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('year_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_machine', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_tes_type', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_machine'], ['machines.id'], name='machine_tes_types_id_machine_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_tes_type'], ['tes_types.id'], name='machine_tes_types_id_tes_type_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['year_number'], ['years.number'], name='machine_tes_types_year_number_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='machine_tes_types_pkey')
    )
    op.create_index('ix_machine_tes_type_year_number', 'machine_tes_types', ['year_number'], unique=False)
    op.create_index('ix_machine_tes_type_id_tes_type', 'machine_tes_types', ['id_tes_type'], unique=False)
    op.create_index('ix_machine_tes_type_id_machine', 'machine_tes_types', ['id_machine'], unique=False)
    op.create_index('ix_generation_machine_tes_types_year_number', 'machine_tes_types', ['year_number'], unique=False)
    op.create_index('ix_generation_machine_tes_types_id_tes_type', 'machine_tes_types', ['id_tes_type'], unique=False)
    op.create_index('ix_generation_machine_tes_types_id_machine', 'machine_tes_types', ['id_machine'], unique=False)
    op.create_table('tes_machine_types',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('tes_machine_types_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tes_machine_types_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_refdata_tes_machine_types_name', 'tes_machine_types', ['name'], unique=True)
    op.create_table('boilers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('id_station', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_station'], ['stations.id'], name='boilers_id_station_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='boilers_pkey')
    )
    op.create_index('ix_generation_boilers_name', 'boilers', ['name'], unique=True)
    op.create_index('ix_generation_boilers_id_station', 'boilers', ['id_station'], unique=False)
    op.create_table('gen_companies',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('gen_companies_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='gen_companies_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_refdata_gen_companies_name', 'gen_companies', ['name'], unique=True)
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_pkc'),
    schema='auth'
    )
    op.create_table('year_features',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('year_features_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='year_features_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_refdata_year_features_name', 'year_features', ['name'], unique=True)
    op.create_table('union_energy_systems',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('union_energy_systems_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('name_full', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('id_energy_system_type', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_energy_system_type'], ['energy_system_types.id'], name='union_energy_systems_id_energy_system_type_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='union_energy_systems_pkey'),
    sa.UniqueConstraint('name_full', name='union_energy_systems_name_full_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_refdata_union_energy_systems_name', 'union_energy_systems', ['name'], unique=True)
    op.create_index('ix_refdata_union_energy_systems_id_energy_system_type', 'union_energy_systems', ['id_energy_system_type'], unique=False)
    op.create_table('energy_system_types',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('energy_system_types_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='energy_system_types_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_refdata_energy_system_types_name', 'energy_system_types', ['name'], unique=True)
    op.create_table('machine_types',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('machine_types_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='machine_types_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_refdata_machine_types_name', 'machine_types', ['name'], unique=True)
    op.create_table('regional_energy_systems',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('regional_energy_systems_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name_full', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id_union_energy_system', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_union_energy_system'], ['union_energy_systems.id'], name='regional_energy_systems_id_union_energy_system_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='regional_energy_systems_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_refdata_regional_energy_systems_name', 'regional_energy_systems', ['name'], unique=False)
    op.create_index('ix_refdata_regional_energy_systems_id_union_energy_system', 'regional_energy_systems', ['id_union_energy_system'], unique=False)
    op.create_table('fuel_categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='fuel_categories_pkey')
    )
    op.create_index('ix_refdata_fuel_categories_name', 'fuel_categories', ['name'], unique=True)
    op.create_table('years',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('years_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_year_feature', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_year_feature'], ['year_features.id'], name='years_id_year_feature_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='years_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_refdata_years_number', 'years', ['number'], unique=True)
    op.create_index('ix_refdata_years_id_year_feature', 'years', ['id_year_feature'], unique=False)
    op.create_table('energy_units',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('energy_units_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('id_regional_district', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_regional_energy_system', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_regional_district'], ['regional_districts.id'], name='energy_units_id_regional_district_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_regional_energy_system'], ['regional_energy_systems.id'], name='energy_units_id_regional_energy_system_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='energy_units_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_refdata_energy_units_name', 'energy_units', ['name'], unique=True)
    op.create_index('ix_refdata_energy_units_id_regional_energy_system', 'energy_units', ['id_regional_energy_system'], unique=False)
    op.create_index('ix_refdata_energy_units_id_regional_district', 'energy_units', ['id_regional_district'], unique=False)
    op.create_table('pgu_machines',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_ti', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_equipment_group_pgu', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_condition_type', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_parent_machine', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('machine_number', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('machine_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id_tes_machine_type', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_pgu_tes_machine_type', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_exploitation', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_commission_fact', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('date_joining_expected', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('date_joining_fact', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('date_detatchment_fact', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('date_decompressing_expected', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_decompressing_fact', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('date_modernization_expected', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_relabing_fact', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('date_update_fact', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('note', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('year_modern', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('year_demontaz', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('resurs_gas', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_condition_type'], ['condition_types.id'], name='pgu_machines_id_condition_type_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_equipment_group_pgu'], ['equipment_groups.id'], name='pgu_machines_id_equipment_group_pgu_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_parent_machine'], ['machines.id'], name='pgu_machines_id_parent_machine_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_pgu_tes_machine_type'], ['pgu_tes_machine_types.id'], name='pgu_machines_id_pgu_tes_machine_type_fkey'),
    sa.ForeignKeyConstraint(['id_tes_machine_type'], ['tes_machine_types.id'], name='pgu_machines_id_tes_machine_type_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='pgu_machines_pkey')
    )
    op.create_index('ix_pgu_machine_id_tes_machine_type', 'pgu_machines', ['id_tes_machine_type'], unique=False)
    op.create_index('ix_pgu_machine_id_parent_machine', 'pgu_machines', ['id_parent_machine'], unique=False)
    op.create_index('ix_pgu_machine_id_equipment_group_pgu', 'pgu_machines', ['id_equipment_group_pgu'], unique=False)
    op.create_index('ix_pgu_machine_id_condition_type', 'pgu_machines', ['id_condition_type'], unique=False)
    op.create_index('ix_generation_pgu_machines_machine_number', 'pgu_machines', ['machine_number'], unique=False)
    op.create_index('ix_generation_pgu_machines_machine_name', 'pgu_machines', ['machine_name'], unique=False)
    op.create_index('ix_generation_pgu_machines_id_tes_machine_type', 'pgu_machines', ['id_tes_machine_type'], unique=False)
    op.create_index('ix_generation_pgu_machines_id_pgu_tes_machine_type', 'pgu_machines', ['id_pgu_tes_machine_type'], unique=False)
    op.create_index('ix_generation_pgu_machines_id_parent_machine', 'pgu_machines', ['id_parent_machine'], unique=False)
    op.create_index('ix_generation_pgu_machines_id_equipment_group_pgu', 'pgu_machines', ['id_equipment_group_pgu'], unique=False)
    op.create_index('ix_generation_pgu_machines_id_condition_type', 'pgu_machines', ['id_condition_type'], unique=False)
    op.create_table('energy_zones',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('energy_zones_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('number', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='energy_zones_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_refdata_energy_zones_number', 'energy_zones', ['number'], unique=True)
    op.create_index('ix_refdata_energy_zones_name', 'energy_zones', ['name'], unique=True)
    op.create_table('machine_powers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('year_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_machine', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('p_ust', sa.NUMERIC(precision=25, scale=15), autoincrement=False, nullable=True),
    sa.Column('p_ogr', sa.NUMERIC(precision=25, scale=15), autoincrement=False, nullable=True),
    sa.Column('p_rasp', sa.NUMERIC(precision=25, scale=15), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_machine'], ['machines.id'], name='machine_powers_id_machine_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['year_number'], ['years.number'], name='machine_powers_year_number_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='machine_powers_pkey')
    )
    op.create_index('ix_machine_power_year_number', 'machine_powers', ['year_number'], unique=False)
    op.create_index('ix_machine_power_id_machine', 'machine_powers', ['id_machine'], unique=False)
    op.create_index('ix_generation_machine_powers_year_number', 'machine_powers', ['year_number'], unique=False)
    op.create_index('ix_generation_machine_powers_id_machine', 'machine_powers', ['id_machine'], unique=False)
    op.create_table('regional_district_regional_energy_system',
    sa.Column('regional_district_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('regional_energy_system_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['regional_district_id'], ['regional_districts.id'], name='regional_district_regional_energy_sys_regional_district_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['regional_energy_system_id'], ['regional_energy_systems.id'], name='regional_district_regional_energ_regional_energy_system_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('regional_district_id', 'regional_energy_system_id', name='regional_district_regional_energy_system_pkey')
    )
    op.create_index('ix_refdata_regional_district_regional_energy_system_reg_e9e7', 'regional_district_regional_energy_system', ['regional_district_id'], unique=False)
    op.create_index('ix_refdata_regional_district_regional_energy_system_reg_56e6', 'regional_district_regional_energy_system', ['regional_energy_system_id'], unique=False)
    op.create_table('machines',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('machines_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('id_ti', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_equipment_group', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_condition_type', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_gen_company', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_station', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_energy_area', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('machine_number', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('machine_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('machine_group', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fuel_so', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('id_station_type', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_machine_type', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_tes_machine_type', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_exploitation', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_commission_fact', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('date_joining_expected', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('date_joining_fact', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('date_detatchment_fact', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('date_decompressing_expected', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_decompressing_fact', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('date_modernization_expected', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_relabing_fact', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('date_update_fact', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('note', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('year_modern', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('year_demontaz', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('resurs_coal', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('resurs_gas', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_condition_type'], ['condition_types.id'], name='machines_id_condition_type_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_energy_area'], ['energy_areas.id'], name='machines_id_energy_area_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_equipment_group'], ['equipment_groups.id'], name='machines_id_equipment_group_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_gen_company'], ['gen_companies.id'], name='machines_id_gen_company_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_machine_type'], ['machine_types.id'], name='machines_id_machine_type_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_station'], ['stations.id'], name='machines_id_station_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_station_type'], ['station_types.id'], name='machines_id_station_type_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_tes_machine_type'], ['tes_machine_types.id'], name='machines_id_tes_machine_type_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='machines_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_machine_id_tes_machine_type', 'machines', ['id_tes_machine_type'], unique=False)
    op.create_index('ix_machine_id_station_type', 'machines', ['id_station_type'], unique=False)
    op.create_index('ix_machine_id_station', 'machines', ['id_station'], unique=False)
    op.create_index('ix_machine_id_gen_company', 'machines', ['id_gen_company'], unique=False)
    op.create_index('ix_machine_id_equipment_group', 'machines', ['id_equipment_group'], unique=False)
    op.create_index('ix_machine_id_energy_area', 'machines', ['id_energy_area'], unique=False)
    op.create_index('ix_machine_id_condition_type', 'machines', ['id_condition_type'], unique=False)
    op.create_index('ix_machine_date_modernization_expected', 'machines', ['date_modernization_expected'], unique=False)
    op.create_index('ix_machine_date_exploitation', 'machines', ['date_exploitation'], unique=False)
    op.create_index('ix_machine_date_decompressing_expected', 'machines', ['date_decompressing_expected'], unique=False)
    op.create_index('ix_generation_machines_machine_number', 'machines', ['machine_number'], unique=False)
    op.create_index('ix_generation_machines_machine_name', 'machines', ['machine_name'], unique=False)
    op.create_index('ix_generation_machines_id_tes_machine_type', 'machines', ['id_tes_machine_type'], unique=False)
    op.create_index('ix_generation_machines_id_station_type', 'machines', ['id_station_type'], unique=False)
    op.create_index('ix_generation_machines_id_station', 'machines', ['id_station'], unique=False)
    op.create_index('ix_generation_machines_id_machine_type', 'machines', ['id_machine_type'], unique=False)
    op.create_index('ix_generation_machines_id_gen_company', 'machines', ['id_gen_company'], unique=False)
    op.create_index('ix_generation_machines_id_equipment_group', 'machines', ['id_equipment_group'], unique=False)
    op.create_index('ix_generation_machines_id_energy_area', 'machines', ['id_energy_area'], unique=False)
    op.create_index('ix_generation_machines_id_condition_type', 'machines', ['id_condition_type'], unique=False)
    op.create_table('fuel_types',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('fuel_types_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='fuel_types_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_refdata_fuel_types_name', 'fuel_types', ['name'], unique=True)
    op.create_table('equipment_groups',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('equipment_groups_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='equipment_groups_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_refdata_equipment_groups_name', 'equipment_groups', ['name'], unique=True)
    op.create_table('logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='logs_pkey')
    )
    op.create_index('ix_logs_logs_username', 'logs', ['username'], unique=False)
    op.create_index('ix_logs_logs_timestamp', 'logs', ['timestamp'], unique=False)
    op.create_index('ix_logs_logs_action', 'logs', ['action'], unique=False)
    op.create_table('station_powers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('year_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_station', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('p_ust', sa.NUMERIC(precision=25, scale=15), autoincrement=False, nullable=True),
    sa.Column('p_ogr', sa.NUMERIC(precision=25, scale=15), autoincrement=False, nullable=True),
    sa.Column('p_rasp', sa.NUMERIC(precision=25, scale=15), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_station'], ['stations.id'], name='station_powers_id_station_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['year_number'], ['years.number'], name='station_powers_year_number_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='station_powers_pkey')
    )
    op.create_index('ix_station_power_year_number', 'station_powers', ['year_number'], unique=False)
    op.create_index('ix_station_power_id_station', 'station_powers', ['id_station'], unique=False)
    op.create_index('ix_generation_station_powers_year_number', 'station_powers', ['year_number'], unique=False)
    op.create_index('ix_generation_station_powers_id_station', 'station_powers', ['id_station'], unique=False)
    op.create_table('machine_fuels',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('year_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_machine', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_fuel', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_fuel'], ['fuels.id'], name='machine_fuels_id_fuel_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_machine'], ['machines.id'], name='machine_fuels_id_machine_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['year_number'], ['years.number'], name='machine_fuels_year_number_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='machine_fuels_pkey')
    )
    op.create_index('ix_machine_fuel_id_year_number', 'machine_fuels', ['year_number'], unique=False)
    op.create_index('ix_machine_fuel_id_machine', 'machine_fuels', ['id_machine'], unique=False)
    op.create_index('ix_machine_fuel_id_fuel', 'machine_fuels', ['id_fuel'], unique=False)
    op.create_index('ix_generation_machine_fuels_year_number', 'machine_fuels', ['year_number'], unique=False)
    op.create_index('ix_generation_machine_fuels_id_machine', 'machine_fuels', ['id_machine'], unique=False)
    op.create_index('ix_generation_machine_fuels_id_fuel', 'machine_fuels', ['id_fuel'], unique=False)
    op.create_table('federal_districts',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('federal_districts_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('name_full', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('name_abr', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='federal_districts_pkey'),
    sa.UniqueConstraint('name_abr', name='federal_districts_name_abr_key'),
    sa.UniqueConstraint('name_full', name='federal_districts_name_full_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_refdata_federal_districts_name', 'federal_districts', ['name'], unique=True)
    op.create_table('tes_types',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tes_types_pkey')
    )
    op.create_index('ix_refdata_tes_types_name', 'tes_types', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_index('ix_auth_users_username', 'users', ['username'], unique=False)
    op.create_index('ix_auth_users_email', 'users', ['email'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('name_full', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='roles_pkey')
    )
    op.create_index('ix_auth_roles_name_full', 'roles', ['name_full'], unique=True)
    op.create_index('ix_auth_roles_name', 'roles', ['name'], unique=True)
    op.create_table('energy_areas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('id_regional_district', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_regional_district'], ['regional_districts.id'], name='energy_areas_id_regional_district_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='energy_areas_pkey')
    )
    op.create_index('ix_refdata_energy_areas_name', 'energy_areas', ['name'], unique=True)
    op.create_index('ix_refdata_energy_areas_id_regional_district', 'energy_areas', ['id_regional_district'], unique=False)
    op.create_table('fuels',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('id_fuel_type', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_fuel_type'], ['fuel_types.id'], name='fuels_id_fuel_type_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='fuels_pkey')
    )
    op.create_index('ix_refdata_fuels_name', 'fuels', ['name'], unique=True)
    op.create_index('ix_refdata_fuels_id_fuel_type', 'fuels', ['id_fuel_type'], unique=False)
    op.create_table('station_groups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='station_groups_pkey')
    )
    op.create_index('ix_generation_station_groups_name', 'station_groups', ['name'], unique=True)
    # ### end Alembic commands ###
