"""Initial full schema

Revision ID: 709f0ad98a55
Revises: 
Create Date: 2025-08-12 15:46:01.296454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '709f0ad98a55'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    with op.batch_alter_table('roles', schema='auth') as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_roles_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    with op.batch_alter_table('users', schema='auth') as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_auth_users_username'), ['username'], unique=False)

    op.create_table('station_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='generation'
    )
    with op.batch_alter_table('station_groups', schema='generation') as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_station_groups_name'), ['name'], unique=True)

    op.create_table('logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=500), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='logs'
    )
    with op.batch_alter_table('logs', schema='logs') as batch_op:
        batch_op.create_index(batch_op.f('ix_logs_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_logs_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_logs_logs_username'), ['username'], unique=False)

    op.create_table('condition_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='refdata'
    )
    with op.batch_alter_table('condition_types', schema='refdata') as batch_op:
        batch_op.create_index(batch_op.f('ix_refdata_condition_types_name'), ['name'], unique=True)

    op.create_table('energy_system_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='refdata'
    )
    with op.batch_alter_table('energy_system_types', schema='refdata') as batch_op:
        batch_op.create_index(batch_op.f('ix_refdata_energy_system_types_name'), ['name'], unique=True)

    op.create_table('energy_zones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='refdata'
    )
    with op.batch_alter_table('energy_zones', schema='refdata') as batch_op:
        batch_op.create_index(batch_op.f('ix_refdata_energy_zones_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_refdata_energy_zones_number'), ['number'], unique=True)

    op.create_table('equipment_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='refdata'
    )
    with op.batch_alter_table('equipment_groups', schema='refdata') as batch_op:
        batch_op.create_index(batch_op.f('ix_refdata_equipment_groups_name'), ['name'], unique=True)

    op.create_table('federal_districts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('name_full', sa.String(length=80), nullable=True),
    sa.Column('name_abr', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_abr'),
    sa.UniqueConstraint('name_full'),
    schema='refdata'
    )
    with op.batch_alter_table('federal_districts', schema='refdata') as batch_op:
        batch_op.create_index(batch_op.f('ix_refdata_federal_districts_name'), ['name'], unique=True)

    op.create_table('fuel_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='refdata'
    )
    with op.batch_alter_table('fuel_categories', schema='refdata') as batch_op:
        batch_op.create_index(batch_op.f('ix_refdata_fuel_categories_name'), ['name'], unique=True)

    op.create_table('fuel_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='refdata'
    )
    with op.batch_alter_table('fuel_types', schema='refdata') as batch_op:
        batch_op.create_index(batch_op.f('ix_refdata_fuel_types_name'), ['name'], unique=True)

    op.create_table('gen_companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='refdata'
    )
    with op.batch_alter_table('gen_companies', schema='refdata') as batch_op:
        batch_op.create_index(batch_op.f('ix_refdata_gen_companies_name'), ['name'], unique=True)

    op.create_table('machine_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='refdata'
    )
    with op.batch_alter_table('machine_types', schema='refdata') as batch_op:
        batch_op.create_index(batch_op.f('ix_refdata_machine_types_name'), ['name'], unique=True)

    op.create_table('pgu_tes_machine_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='refdata'
    )
    with op.batch_alter_table('pgu_tes_machine_types', schema='refdata') as batch_op:
        batch_op.create_index(batch_op.f('ix_refdata_pgu_tes_machine_types_name'), ['name'], unique=True)

    op.create_table('station_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='refdata'
    )
    with op.batch_alter_table('station_types', schema='refdata') as batch_op:
        batch_op.create_index(batch_op.f('ix_refdata_station_types_name'), ['name'], unique=True)

    op.create_table('synchronous_areas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='refdata'
    )
    with op.batch_alter_table('synchronous_areas', schema='refdata') as batch_op:
        batch_op.create_index(batch_op.f('ix_refdata_synchronous_areas_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_refdata_synchronous_areas_number'), ['number'], unique=True)

    op.create_table('tes_machine_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='refdata'
    )
    with op.batch_alter_table('tes_machine_types', schema='refdata') as batch_op:
        batch_op.create_index(batch_op.f('ix_refdata_tes_machine_types_name'), ['name'], unique=True)

    op.create_table('tes_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='refdata'
    )
    with op.batch_alter_table('tes_types', schema='refdata') as batch_op:
        batch_op.create_index(batch_op.f('ix_refdata_tes_types_name'), ['name'], unique=True)

    op.create_table('year_features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='refdata'
    )
    with op.batch_alter_table('year_features', schema='refdata') as batch_op:
        batch_op.create_index(batch_op.f('ix_refdata_year_features_name'), ['name'], unique=True)

    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['auth.roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    schema='auth'
    )
    op.create_table('fuels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('id_fuel_type', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_fuel_type'], ['refdata.fuel_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='refdata'
    )
    with op.batch_alter_table('fuels', schema='refdata') as batch_op:
        batch_op.create_index(batch_op.f('ix_refdata_fuels_id_fuel_type'), ['id_fuel_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_refdata_fuels_name'), ['name'], unique=True)

    op.create_table('regional_districts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region_number', sa.String(length=3), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('name_full', sa.String(length=80), nullable=True),
    sa.Column('id_federal_district', sa.Integer(), nullable=True),
    sa.Column('id_energy_zone', sa.Integer(), nullable=True),
    sa.Column('id_synchronous_area', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_energy_zone'], ['refdata.energy_zones.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_federal_district'], ['refdata.federal_districts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_synchronous_area'], ['refdata.synchronous_areas.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_full'),
    schema='refdata'
    )
    with op.batch_alter_table('regional_districts', schema='refdata') as batch_op:
        batch_op.create_index(batch_op.f('ix_refdata_regional_districts_id_energy_zone'), ['id_energy_zone'], unique=False)
        batch_op.create_index(batch_op.f('ix_refdata_regional_districts_id_federal_district'), ['id_federal_district'], unique=False)
        batch_op.create_index(batch_op.f('ix_refdata_regional_districts_id_synchronous_area'), ['id_synchronous_area'], unique=False)
        batch_op.create_index(batch_op.f('ix_refdata_regional_districts_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_refdata_regional_districts_region_number'), ['region_number'], unique=False)

    op.create_table('union_energy_systems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('name_full', sa.String(length=80), nullable=False),
    sa.Column('id_energy_system_type', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_energy_system_type'], ['refdata.energy_system_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_full'),
    schema='refdata'
    )
    with op.batch_alter_table('union_energy_systems', schema='refdata') as batch_op:
        batch_op.create_index(batch_op.f('ix_refdata_union_energy_systems_id_energy_system_type'), ['id_energy_system_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_refdata_union_energy_systems_name'), ['name'], unique=True)

    op.create_table('years',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('id_year_feature', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_year_feature'], ['refdata.year_features.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='refdata'
    )
    with op.batch_alter_table('years', schema='refdata') as batch_op:
        batch_op.create_index(batch_op.f('ix_refdata_years_id_year_feature'), ['id_year_feature'], unique=False)
        batch_op.create_index(batch_op.f('ix_refdata_years_number'), ['number'], unique=True)

    op.create_table('regional_energy_systems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_full', sa.String(length=255), nullable=False),
    sa.Column('id_union_energy_system', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_union_energy_system'], ['refdata.union_energy_systems.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='refdata'
    )
    with op.batch_alter_table('regional_energy_systems', schema='refdata') as batch_op:
        batch_op.create_index(batch_op.f('ix_refdata_regional_energy_systems_id_union_energy_system'), ['id_union_energy_system'], unique=False)
        batch_op.create_index(batch_op.f('ix_refdata_regional_energy_systems_name'), ['name'], unique=False)

    op.create_table('energy_areas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('id_regional_district', sa.Integer(), nullable=False),
    sa.Column('id_regional_energy_system', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_regional_district'], ['refdata.regional_districts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_regional_energy_system'], ['refdata.regional_energy_systems.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='refdata'
    )
    with op.batch_alter_table('energy_areas', schema='refdata') as batch_op:
        batch_op.create_index(batch_op.f('ix_refdata_energy_areas_id_regional_district'), ['id_regional_district'], unique=False)
        batch_op.create_index(batch_op.f('ix_refdata_energy_areas_id_regional_energy_system'), ['id_regional_energy_system'], unique=False)
        batch_op.create_index(batch_op.f('ix_refdata_energy_areas_name'), ['name'], unique=True)

    op.create_table('energy_units',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('id_regional_district', sa.Integer(), nullable=False),
    sa.Column('id_regional_energy_system', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_regional_district'], ['refdata.regional_districts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_regional_energy_system'], ['refdata.regional_energy_systems.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='refdata'
    )
    with op.batch_alter_table('energy_units', schema='refdata') as batch_op:
        batch_op.create_index(batch_op.f('ix_refdata_energy_units_id_regional_district'), ['id_regional_district'], unique=False)
        batch_op.create_index(batch_op.f('ix_refdata_energy_units_id_regional_energy_system'), ['id_regional_energy_system'], unique=False)
        batch_op.create_index(batch_op.f('ix_refdata_energy_units_name'), ['name'], unique=True)

    op.create_table('regional_district_regional_energy_system',
    sa.Column('regional_district_id', sa.Integer(), nullable=False),
    sa.Column('regional_energy_system_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['regional_district_id'], ['refdata.regional_districts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['regional_energy_system_id'], ['refdata.regional_energy_systems.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('regional_district_id', 'regional_energy_system_id'),
    schema='refdata'
    )
    with op.batch_alter_table('regional_district_regional_energy_system', schema='refdata') as batch_op:
        batch_op.create_index(batch_op.f('ix_refdata_regional_district_regional_energy_system_regional_energy_system_id'), ['regional_energy_system_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refdata_regional_district_regional_energy_system_regional_district_id'), ['regional_district_id'], unique=False)

    op.create_table('stations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_station_group', sa.Integer(), nullable=True),
    sa.Column('id_condition_type', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_so', sa.String(length=80), nullable=True),
    sa.Column('name_combined', sa.String(length=80), nullable=True),
    sa.Column('name_archive', sa.String(length=80), nullable=True),
    sa.Column('id_regional_district', sa.Integer(), nullable=True),
    sa.Column('id_energy_unit', sa.Integer(), nullable=True),
    sa.Column('kto', sa.String(length=80), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_condition_type'], ['refdata.condition_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_energy_unit'], ['refdata.energy_units.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_regional_district'], ['refdata.regional_districts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_station_group'], ['generation.station_groups.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kto'),
    sa.UniqueConstraint('location'),
    sa.UniqueConstraint('name', 'id_regional_district', name='uq_station_name_district'),
    sa.UniqueConstraint('name_archive'),
    sa.UniqueConstraint('name_combined'),
    sa.UniqueConstraint('name_so'),
    schema='generation'
    )
    with op.batch_alter_table('stations', schema='generation') as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_stations_id_condition_type'), ['id_condition_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_stations_id_energy_unit'), ['id_energy_unit'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_stations_id_regional_district'), ['id_regional_district'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_stations_id_station_group'), ['id_station_group'], unique=False)
        batch_op.create_index('ix_station_id_regional_district', ['id_regional_district'], unique=False)
        batch_op.create_index('ix_station_id_station_group', ['id_station_group'], unique=False)
        batch_op.create_index('ix_station_name', ['name'], unique=False)

    op.create_table('boilers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('id_station', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_station'], ['generation.stations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='generation'
    )
    with op.batch_alter_table('boilers', schema='generation') as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_boilers_id_station'), ['id_station'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_boilers_name'), ['name'], unique=True)

    op.create_table('machines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_ti', sa.Integer(), nullable=True),
    sa.Column('id_equipment_group', sa.Integer(), nullable=True),
    sa.Column('id_condition_type', sa.Integer(), nullable=True),
    sa.Column('id_gen_company', sa.Integer(), nullable=True),
    sa.Column('id_station', sa.Integer(), nullable=True),
    sa.Column('id_energy_area', sa.Integer(), nullable=True),
    sa.Column('machine_number', sa.String(length=80), nullable=False),
    sa.Column('machine_name', sa.String(length=255), nullable=False),
    sa.Column('machine_group', sa.String(length=255), nullable=True),
    sa.Column('fuel_so', sa.String(length=255), nullable=True),
    sa.Column('id_station_type', sa.Integer(), nullable=True),
    sa.Column('id_machine_type', sa.Integer(), nullable=True),
    sa.Column('id_tes_machine_type', sa.Integer(), nullable=True),
    sa.Column('date_exploitation', sa.Integer(), nullable=True),
    sa.Column('date_commission_fact', sa.String(length=10), nullable=True),
    sa.Column('date_joining_expected', sa.String(length=10), nullable=True),
    sa.Column('date_joining_fact', sa.String(length=10), nullable=True),
    sa.Column('date_detatchment_fact', sa.String(length=10), nullable=True),
    sa.Column('date_decompressing_expected', sa.Integer(), nullable=True),
    sa.Column('date_decompressing_fact', sa.String(length=10), nullable=True),
    sa.Column('date_modernization_expected', sa.Integer(), nullable=True),
    sa.Column('date_relabing_fact', sa.String(length=10), nullable=True),
    sa.Column('date_update_fact', sa.String(length=10), nullable=True),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('year_modern', sa.String(length=10), nullable=True),
    sa.Column('year_demontaz', sa.String(length=10), nullable=True),
    sa.Column('resurs_coal', sa.String(length=10), nullable=True),
    sa.Column('resurs_gas', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_condition_type'], ['refdata.condition_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_energy_area'], ['refdata.energy_areas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_equipment_group'], ['refdata.equipment_groups.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_gen_company'], ['refdata.gen_companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_machine_type'], ['refdata.machine_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_station'], ['generation.stations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_station_type'], ['refdata.station_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_tes_machine_type'], ['refdata.tes_machine_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='generation'
    )
    with op.batch_alter_table('machines', schema='generation') as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_machines_id_condition_type'), ['id_condition_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_machines_id_energy_area'), ['id_energy_area'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_machines_id_equipment_group'), ['id_equipment_group'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_machines_id_gen_company'), ['id_gen_company'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_machines_id_machine_type'), ['id_machine_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_machines_id_station'), ['id_station'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_machines_id_station_type'), ['id_station_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_machines_id_tes_machine_type'), ['id_tes_machine_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_machines_machine_name'), ['machine_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_machines_machine_number'), ['machine_number'], unique=False)
        batch_op.create_index('ix_machine_date_decompressing_expected', ['date_decompressing_expected'], unique=False)
        batch_op.create_index('ix_machine_date_exploitation', ['date_exploitation'], unique=False)
        batch_op.create_index('ix_machine_date_modernization_expected', ['date_modernization_expected'], unique=False)
        batch_op.create_index('ix_machine_id_condition_type', ['id_condition_type'], unique=False)
        batch_op.create_index('ix_machine_id_energy_area', ['id_energy_area'], unique=False)
        batch_op.create_index('ix_machine_id_equipment_group', ['id_equipment_group'], unique=False)
        batch_op.create_index('ix_machine_id_gen_company', ['id_gen_company'], unique=False)
        batch_op.create_index('ix_machine_id_station', ['id_station'], unique=False)
        batch_op.create_index('ix_machine_id_station_type', ['id_station_type'], unique=False)
        batch_op.create_index('ix_machine_id_tes_machine_type', ['id_tes_machine_type'], unique=False)

    op.create_table('station_powers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year_number', sa.Integer(), nullable=True),
    sa.Column('id_station', sa.Integer(), nullable=True),
    sa.Column('p_ust', sa.Numeric(precision=25, scale=15), nullable=True),
    sa.Column('p_ogr', sa.Numeric(precision=25, scale=15), nullable=True),
    sa.Column('p_rasp', sa.Numeric(precision=25, scale=15), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_station'], ['generation.stations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['year_number'], ['refdata.years.number'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='generation'
    )
    with op.batch_alter_table('station_powers', schema='generation') as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_station_powers_id_station'), ['id_station'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_station_powers_year_number'), ['year_number'], unique=False)
        batch_op.create_index('ix_station_power_id_station', ['id_station'], unique=False)
        batch_op.create_index('ix_station_power_year_number', ['year_number'], unique=False)

    op.create_table('machine_fuels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year_number', sa.Integer(), nullable=True),
    sa.Column('id_machine', sa.Integer(), nullable=True),
    sa.Column('id_fuel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_fuel'], ['refdata.fuels.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_machine'], ['generation.machines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['year_number'], ['refdata.years.number'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='generation'
    )
    with op.batch_alter_table('machine_fuels', schema='generation') as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_machine_fuels_id_fuel'), ['id_fuel'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_machine_fuels_id_machine'), ['id_machine'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_machine_fuels_year_number'), ['year_number'], unique=False)
        batch_op.create_index('ix_machine_fuel_id_fuel', ['id_fuel'], unique=False)
        batch_op.create_index('ix_machine_fuel_id_machine', ['id_machine'], unique=False)
        batch_op.create_index('ix_machine_fuel_id_year_number', ['year_number'], unique=False)

    op.create_table('machine_powers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year_number', sa.Integer(), nullable=True),
    sa.Column('id_machine', sa.Integer(), nullable=True),
    sa.Column('p_ust', sa.Numeric(precision=25, scale=15), nullable=True),
    sa.Column('p_ogr', sa.Numeric(precision=25, scale=15), nullable=True),
    sa.Column('p_rasp', sa.Numeric(precision=25, scale=15), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_machine'], ['generation.machines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['year_number'], ['refdata.years.number'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='generation'
    )
    with op.batch_alter_table('machine_powers', schema='generation') as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_machine_powers_id_machine'), ['id_machine'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_machine_powers_year_number'), ['year_number'], unique=False)
        batch_op.create_index('ix_machine_power_id_machine', ['id_machine'], unique=False)
        batch_op.create_index('ix_machine_power_year_number', ['year_number'], unique=False)

    op.create_table('machine_tes_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year_number', sa.Integer(), nullable=True),
    sa.Column('id_machine', sa.Integer(), nullable=True),
    sa.Column('id_tes_type', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_machine'], ['generation.machines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_tes_type'], ['refdata.tes_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['year_number'], ['refdata.years.number'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='generation'
    )
    with op.batch_alter_table('machine_tes_types', schema='generation') as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_machine_tes_types_id_machine'), ['id_machine'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_machine_tes_types_id_tes_type'), ['id_tes_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_machine_tes_types_year_number'), ['year_number'], unique=False)
        batch_op.create_index('ix_machine_tes_type_id_machine', ['id_machine'], unique=False)
        batch_op.create_index('ix_machine_tes_type_id_tes_type', ['id_tes_type'], unique=False)
        batch_op.create_index('ix_machine_tes_type_year_number', ['year_number'], unique=False)

    op.create_table('pgu_machines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_ti', sa.Integer(), nullable=True),
    sa.Column('id_equipment_group_pgu', sa.Integer(), nullable=True),
    sa.Column('id_condition_type', sa.Integer(), nullable=True),
    sa.Column('id_parent_machine', sa.Integer(), nullable=False),
    sa.Column('machine_number', sa.String(length=80), nullable=True),
    sa.Column('machine_name', sa.String(length=255), nullable=False),
    sa.Column('id_tes_machine_type', sa.Integer(), nullable=True),
    sa.Column('id_pgu_tes_machine_type', sa.Integer(), nullable=True),
    sa.Column('date_exploitation', sa.Integer(), nullable=True),
    sa.Column('date_commission_fact', sa.String(length=10), nullable=True),
    sa.Column('date_joining_expected', sa.String(length=10), nullable=True),
    sa.Column('date_joining_fact', sa.String(length=10), nullable=True),
    sa.Column('date_detatchment_fact', sa.String(length=10), nullable=True),
    sa.Column('date_decompressing_expected', sa.Integer(), nullable=True),
    sa.Column('date_decompressing_fact', sa.String(length=10), nullable=True),
    sa.Column('date_modernization_expected', sa.Integer(), nullable=True),
    sa.Column('date_relabing_fact', sa.String(length=10), nullable=True),
    sa.Column('date_update_fact', sa.String(length=10), nullable=True),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('year_modern', sa.String(length=10), nullable=True),
    sa.Column('year_demontaz', sa.String(length=10), nullable=True),
    sa.Column('resurs_gas', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_condition_type'], ['refdata.condition_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_equipment_group_pgu'], ['refdata.equipment_groups.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_parent_machine'], ['generation.machines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_pgu_tes_machine_type'], ['refdata.pgu_tes_machine_types.id'], ),
    sa.ForeignKeyConstraint(['id_tes_machine_type'], ['refdata.tes_machine_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='generation'
    )
    with op.batch_alter_table('pgu_machines', schema='generation') as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_pgu_machines_id_condition_type'), ['id_condition_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_pgu_machines_id_equipment_group_pgu'), ['id_equipment_group_pgu'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_pgu_machines_id_parent_machine'), ['id_parent_machine'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_pgu_machines_id_pgu_tes_machine_type'), ['id_pgu_tes_machine_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_pgu_machines_id_tes_machine_type'), ['id_tes_machine_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_pgu_machines_machine_name'), ['machine_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_pgu_machines_machine_number'), ['machine_number'], unique=False)
        batch_op.create_index('ix_pgu_machine_id_condition_type', ['id_condition_type'], unique=False)
        batch_op.create_index('ix_pgu_machine_id_equipment_group_pgu', ['id_equipment_group_pgu'], unique=False)
        batch_op.create_index('ix_pgu_machine_id_parent_machine', ['id_parent_machine'], unique=False)
        batch_op.create_index('ix_pgu_machine_id_tes_machine_type', ['id_tes_machine_type'], unique=False)

    op.create_table('pgu_machine_powers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year_number', sa.Integer(), nullable=True),
    sa.Column('id_pgu_machine', sa.Integer(), nullable=True),
    sa.Column('p_ust', sa.Numeric(precision=25, scale=15), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_pgu_machine'], ['generation.pgu_machines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['year_number'], ['refdata.years.number'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='generation'
    )
    with op.batch_alter_table('pgu_machine_powers', schema='generation') as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_pgu_machine_powers_id_pgu_machine'), ['id_pgu_machine'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_pgu_machine_powers_year_number'), ['year_number'], unique=False)
        batch_op.create_index('ix_pgu_machine_power_id_pgu_machine', ['id_pgu_machine'], unique=False)
        batch_op.create_index('ix_pgu_machine_power_year_number', ['year_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pgu_machine_powers', schema='generation') as batch_op:
        batch_op.drop_index('ix_pgu_machine_power_year_number')
        batch_op.drop_index('ix_pgu_machine_power_id_pgu_machine')
        batch_op.drop_index(batch_op.f('ix_generation_pgu_machine_powers_year_number'))
        batch_op.drop_index(batch_op.f('ix_generation_pgu_machine_powers_id_pgu_machine'))

    op.drop_table('pgu_machine_powers', schema='generation')
    with op.batch_alter_table('pgu_machines', schema='generation') as batch_op:
        batch_op.drop_index('ix_pgu_machine_id_tes_machine_type')
        batch_op.drop_index('ix_pgu_machine_id_parent_machine')
        batch_op.drop_index('ix_pgu_machine_id_equipment_group_pgu')
        batch_op.drop_index('ix_pgu_machine_id_condition_type')
        batch_op.drop_index(batch_op.f('ix_generation_pgu_machines_machine_number'))
        batch_op.drop_index(batch_op.f('ix_generation_pgu_machines_machine_name'))
        batch_op.drop_index(batch_op.f('ix_generation_pgu_machines_id_tes_machine_type'))
        batch_op.drop_index(batch_op.f('ix_generation_pgu_machines_id_pgu_tes_machine_type'))
        batch_op.drop_index(batch_op.f('ix_generation_pgu_machines_id_parent_machine'))
        batch_op.drop_index(batch_op.f('ix_generation_pgu_machines_id_equipment_group_pgu'))
        batch_op.drop_index(batch_op.f('ix_generation_pgu_machines_id_condition_type'))

    op.drop_table('pgu_machines', schema='generation')
    with op.batch_alter_table('machine_tes_types', schema='generation') as batch_op:
        batch_op.drop_index('ix_machine_tes_type_year_number')
        batch_op.drop_index('ix_machine_tes_type_id_tes_type')
        batch_op.drop_index('ix_machine_tes_type_id_machine')
        batch_op.drop_index(batch_op.f('ix_generation_machine_tes_types_year_number'))
        batch_op.drop_index(batch_op.f('ix_generation_machine_tes_types_id_tes_type'))
        batch_op.drop_index(batch_op.f('ix_generation_machine_tes_types_id_machine'))

    op.drop_table('machine_tes_types', schema='generation')
    with op.batch_alter_table('machine_powers', schema='generation') as batch_op:
        batch_op.drop_index('ix_machine_power_year_number')
        batch_op.drop_index('ix_machine_power_id_machine')
        batch_op.drop_index(batch_op.f('ix_generation_machine_powers_year_number'))
        batch_op.drop_index(batch_op.f('ix_generation_machine_powers_id_machine'))

    op.drop_table('machine_powers', schema='generation')
    with op.batch_alter_table('machine_fuels', schema='generation') as batch_op:
        batch_op.drop_index('ix_machine_fuel_id_year_number')
        batch_op.drop_index('ix_machine_fuel_id_machine')
        batch_op.drop_index('ix_machine_fuel_id_fuel')
        batch_op.drop_index(batch_op.f('ix_generation_machine_fuels_year_number'))
        batch_op.drop_index(batch_op.f('ix_generation_machine_fuels_id_machine'))
        batch_op.drop_index(batch_op.f('ix_generation_machine_fuels_id_fuel'))

    op.drop_table('machine_fuels', schema='generation')
    with op.batch_alter_table('station_powers', schema='generation') as batch_op:
        batch_op.drop_index('ix_station_power_year_number')
        batch_op.drop_index('ix_station_power_id_station')
        batch_op.drop_index(batch_op.f('ix_generation_station_powers_year_number'))
        batch_op.drop_index(batch_op.f('ix_generation_station_powers_id_station'))

    op.drop_table('station_powers', schema='generation')
    with op.batch_alter_table('machines', schema='generation') as batch_op:
        batch_op.drop_index('ix_machine_id_tes_machine_type')
        batch_op.drop_index('ix_machine_id_station_type')
        batch_op.drop_index('ix_machine_id_station')
        batch_op.drop_index('ix_machine_id_gen_company')
        batch_op.drop_index('ix_machine_id_equipment_group')
        batch_op.drop_index('ix_machine_id_energy_area')
        batch_op.drop_index('ix_machine_id_condition_type')
        batch_op.drop_index('ix_machine_date_modernization_expected')
        batch_op.drop_index('ix_machine_date_exploitation')
        batch_op.drop_index('ix_machine_date_decompressing_expected')
        batch_op.drop_index(batch_op.f('ix_generation_machines_machine_number'))
        batch_op.drop_index(batch_op.f('ix_generation_machines_machine_name'))
        batch_op.drop_index(batch_op.f('ix_generation_machines_id_tes_machine_type'))
        batch_op.drop_index(batch_op.f('ix_generation_machines_id_station_type'))
        batch_op.drop_index(batch_op.f('ix_generation_machines_id_station'))
        batch_op.drop_index(batch_op.f('ix_generation_machines_id_machine_type'))
        batch_op.drop_index(batch_op.f('ix_generation_machines_id_gen_company'))
        batch_op.drop_index(batch_op.f('ix_generation_machines_id_equipment_group'))
        batch_op.drop_index(batch_op.f('ix_generation_machines_id_energy_area'))
        batch_op.drop_index(batch_op.f('ix_generation_machines_id_condition_type'))

    op.drop_table('machines', schema='generation')
    with op.batch_alter_table('boilers', schema='generation') as batch_op:
        batch_op.drop_index(batch_op.f('ix_generation_boilers_name'))
        batch_op.drop_index(batch_op.f('ix_generation_boilers_id_station'))

    op.drop_table('boilers', schema='generation')
    with op.batch_alter_table('stations', schema='generation') as batch_op:
        batch_op.drop_index('ix_station_name')
        batch_op.drop_index('ix_station_id_station_group')
        batch_op.drop_index('ix_station_id_regional_district')
        batch_op.drop_index(batch_op.f('ix_generation_stations_id_station_group'))
        batch_op.drop_index(batch_op.f('ix_generation_stations_id_regional_district'))
        batch_op.drop_index(batch_op.f('ix_generation_stations_id_energy_unit'))
        batch_op.drop_index(batch_op.f('ix_generation_stations_id_condition_type'))

    op.drop_table('stations', schema='generation')
    with op.batch_alter_table('regional_district_regional_energy_system', schema='refdata') as batch_op:
        batch_op.drop_index(batch_op.f('ix_refdata_regional_district_regional_energy_system_regional_district_id'))
        batch_op.drop_index(batch_op.f('ix_refdata_regional_district_regional_energy_system_regional_energy_system_id'))

    op.drop_table('regional_district_regional_energy_system', schema='refdata')
    with op.batch_alter_table('energy_units', schema='refdata') as batch_op:
        batch_op.drop_index(batch_op.f('ix_refdata_energy_units_name'))
        batch_op.drop_index(batch_op.f('ix_refdata_energy_units_id_regional_energy_system'))
        batch_op.drop_index(batch_op.f('ix_refdata_energy_units_id_regional_district'))

    op.drop_table('energy_units', schema='refdata')
    with op.batch_alter_table('energy_areas', schema='refdata') as batch_op:
        batch_op.drop_index(batch_op.f('ix_refdata_energy_areas_name'))
        batch_op.drop_index(batch_op.f('ix_refdata_energy_areas_id_regional_energy_system'))
        batch_op.drop_index(batch_op.f('ix_refdata_energy_areas_id_regional_district'))

    op.drop_table('energy_areas', schema='refdata')
    with op.batch_alter_table('regional_energy_systems', schema='refdata') as batch_op:
        batch_op.drop_index(batch_op.f('ix_refdata_regional_energy_systems_name'))
        batch_op.drop_index(batch_op.f('ix_refdata_regional_energy_systems_id_union_energy_system'))

    op.drop_table('regional_energy_systems', schema='refdata')
    with op.batch_alter_table('years', schema='refdata') as batch_op:
        batch_op.drop_index(batch_op.f('ix_refdata_years_number'))
        batch_op.drop_index(batch_op.f('ix_refdata_years_id_year_feature'))

    op.drop_table('years', schema='refdata')
    with op.batch_alter_table('union_energy_systems', schema='refdata') as batch_op:
        batch_op.drop_index(batch_op.f('ix_refdata_union_energy_systems_name'))
        batch_op.drop_index(batch_op.f('ix_refdata_union_energy_systems_id_energy_system_type'))

    op.drop_table('union_energy_systems', schema='refdata')
    with op.batch_alter_table('regional_districts', schema='refdata') as batch_op:
        batch_op.drop_index(batch_op.f('ix_refdata_regional_districts_region_number'))
        batch_op.drop_index(batch_op.f('ix_refdata_regional_districts_name'))
        batch_op.drop_index(batch_op.f('ix_refdata_regional_districts_id_synchronous_area'))
        batch_op.drop_index(batch_op.f('ix_refdata_regional_districts_id_federal_district'))
        batch_op.drop_index(batch_op.f('ix_refdata_regional_districts_id_energy_zone'))

    op.drop_table('regional_districts', schema='refdata')
    with op.batch_alter_table('fuels', schema='refdata') as batch_op:
        batch_op.drop_index(batch_op.f('ix_refdata_fuels_name'))
        batch_op.drop_index(batch_op.f('ix_refdata_fuels_id_fuel_type'))

    op.drop_table('fuels', schema='refdata')
    op.drop_table('user_roles', schema='auth')
    with op.batch_alter_table('year_features', schema='refdata') as batch_op:
        batch_op.drop_index(batch_op.f('ix_refdata_year_features_name'))

    op.drop_table('year_features', schema='refdata')
    with op.batch_alter_table('tes_types', schema='refdata') as batch_op:
        batch_op.drop_index(batch_op.f('ix_refdata_tes_types_name'))

    op.drop_table('tes_types', schema='refdata')
    with op.batch_alter_table('tes_machine_types', schema='refdata') as batch_op:
        batch_op.drop_index(batch_op.f('ix_refdata_tes_machine_types_name'))

    op.drop_table('tes_machine_types', schema='refdata')
    with op.batch_alter_table('synchronous_areas', schema='refdata') as batch_op:
        batch_op.drop_index(batch_op.f('ix_refdata_synchronous_areas_number'))
        batch_op.drop_index(batch_op.f('ix_refdata_synchronous_areas_name'))

    op.drop_table('synchronous_areas', schema='refdata')
    with op.batch_alter_table('station_types', schema='refdata') as batch_op:
        batch_op.drop_index(batch_op.f('ix_refdata_station_types_name'))

    op.drop_table('station_types', schema='refdata')
    with op.batch_alter_table('pgu_tes_machine_types', schema='refdata') as batch_op:
        batch_op.drop_index(batch_op.f('ix_refdata_pgu_tes_machine_types_name'))

    op.drop_table('pgu_tes_machine_types', schema='refdata')
    with op.batch_alter_table('machine_types', schema='refdata') as batch_op:
        batch_op.drop_index(batch_op.f('ix_refdata_machine_types_name'))

    op.drop_table('machine_types', schema='refdata')
    with op.batch_alter_table('gen_companies', schema='refdata') as batch_op:
        batch_op.drop_index(batch_op.f('ix_refdata_gen_companies_name'))

    op.drop_table('gen_companies', schema='refdata')
    with op.batch_alter_table('fuel_types', schema='refdata') as batch_op:
        batch_op.drop_index(batch_op.f('ix_refdata_fuel_types_name'))

    op.drop_table('fuel_types', schema='refdata')
    with op.batch_alter_table('fuel_categories', schema='refdata') as batch_op:
        batch_op.drop_index(batch_op.f('ix_refdata_fuel_categories_name'))

    op.drop_table('fuel_categories', schema='refdata')
    with op.batch_alter_table('federal_districts', schema='refdata') as batch_op:
        batch_op.drop_index(batch_op.f('ix_refdata_federal_districts_name'))

    op.drop_table('federal_districts', schema='refdata')
    with op.batch_alter_table('equipment_groups', schema='refdata') as batch_op:
        batch_op.drop_index(batch_op.f('ix_refdata_equipment_groups_name'))

    op.drop_table('equipment_groups', schema='refdata')
    with op.batch_alter_table('energy_zones', schema='refdata') as batch_op:
        batch_op.drop_index(batch_op.f('ix_refdata_energy_zones_number'))
        batch_op.drop_index(batch_op.f('ix_refdata_energy_zones_name'))

    op.drop_table('energy_zones', schema='refdata')
    with op.batch_alter_table('energy_system_types', schema='refdata') as batch_op:
        batch_op.drop_index(batch_op.f('ix_refdata_energy_system_types_name'))

    op.drop_table('energy_system_types', schema='refdata')
    with op.batch_alter_table('condition_types', schema='refdata') as batch_op:
        batch_op.drop_index(batch_op.f('ix_refdata_condition_types_name'))

    op.drop_table('condition_types', schema='refdata')
    with op.batch_alter_table('logs', schema='logs') as batch_op:
        batch_op.drop_index(batch_op.f('ix_logs_logs_username'))
        batch_op.drop_index(batch_op.f('ix_logs_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_logs_logs_action'))

    op.drop_table('logs', schema='logs')
    with op.batch_alter_table('station_groups', schema='generation') as batch_op:
        batch_op.drop_index(batch_op.f('ix_generation_station_groups_name'))

    op.drop_table('station_groups', schema='generation')
    with op.batch_alter_table('users', schema='auth') as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_users_username'))
        batch_op.drop_index(batch_op.f('ix_auth_users_email'))

    op.drop_table('users', schema='auth')
    with op.batch_alter_table('roles', schema='auth') as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_roles_name'))

    op.drop_table('roles', schema='auth')
    # ### end Alembic commands ###
