"""исправлена модель синхронной зоны

Revision ID: 72928411edc7
Revises: 876f3ec37a4a
Create Date: 2025-09-22 10:37:13.789930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72928411edc7'
down_revision = '876f3ec37a4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('synchronous_areas', 'number',
               existing_type=sa.VARCHAR(length=256),
               nullable=True,
               schema='refdata')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('synchronous_areas', 'number',
               existing_type=sa.VARCHAR(length=256),
               nullable=False,
               schema='refdata')
    # ### end Alembic commands ###
