"""добавлены параметры техинспекции для машин

Revision ID: 78658ab94c24
Revises: 
Create Date: 2025-06-04 15:51:32.683654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78658ab94c24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_ti', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_equipment_group', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'equipment_groups', ['id_equipment_group'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_equipment_group')
        batch_op.drop_column('id_ti')

    # ### end Alembic commands ###
