"""fix_years_unique_constraint_for_versioning_v2

Revision ID: 8264aa5b0a0b
Revises: 386e0650141a
Create Date: 2025-10-24 12:01:51.494177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8264aa5b0a0b'
down_revision = '386e0650141a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем старый уникальный индекс по number с CASCADE
    op.execute('DROP INDEX IF EXISTS refdata.ix_refdata_years_number CASCADE')
    
    # Создаем составной уникальный индекс по number и database_version_id
    op.create_index('ix_refdata_years_number_database_version_id', 'years', ['number', 'database_version_id'], unique=True, schema='refdata')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем составной уникальный индекс
    op.drop_index('ix_refdata_years_number_database_version_id', table_name='years', schema='refdata')
    
    # Восстанавливаем старый уникальный индекс по number
    op.create_index('ix_refdata_years_number', 'years', ['number'], unique=True, schema='refdata')
    # ### end Alembic commands ###
