"""add equipment_group_type and technology_type to EquipmentGroup

Revision ID: 843ddbe65156
Revises: ffbd4f9038d6
Create Date: 2025-10-02 16:46:08.773720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '843ddbe65156'
down_revision = 'ffbd4f9038d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'machine_fuels', 'years', ['year_number'], ['number'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machine_fuels', 'fuels', ['id_fuel'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machine_powers', 'years', ['year_number'], ['number'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machine_tes_types', 'tes_types', ['id_tes_type'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machine_tes_types', 'years', ['year_number'], ['number'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'gen_companies', ['id_gen_company'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'machine_types', ['id_machine_type'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'tes_machine_types', ['id_tes_machine_type'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'equipment_groups', ['id_equipment_group'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'station_types', ['id_station_type'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'energy_areas', ['id_energy_area'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'condition_types', ['id_condition_type'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'pgu_machine_powers', 'years', ['year_number'], ['number'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'pgu_machines', 'equipment_groups', ['id_equipment_group_pgu'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'pgu_machines', 'tes_machine_types', ['id_tes_machine_type'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'pgu_machines', 'condition_types', ['id_condition_type'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'pgu_machines', 'pgu_tes_machine_types', ['id_pgu_tes_machine_type'], ['id'], source_schema='generation', referent_schema='refdata')
    op.create_foreign_key(None, 'station_powers', 'years', ['year_number'], ['number'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'stations', 'regional_districts', ['id_regional_district'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'stations', 'energy_units', ['id_energy_unit'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'stations', 'condition_types', ['id_condition_type'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stations', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'stations', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'stations', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'station_powers', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'pgu_machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'pgu_machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'pgu_machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'pgu_machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'pgu_machine_powers', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machine_tes_types', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machine_tes_types', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machine_powers', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machine_fuels', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machine_fuels', schema='generation', type_='foreignkey')
    # ### end Alembic commands ###
