"""Add database_version_id to logs table

Revision ID: 867a868671bb
Revises: bulk_refdata_unique_20251029
Create Date: 2025-10-29 12:58:09.892241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '867a868671bb'
down_revision = 'bulk_refdata_unique_20251029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('logs', sa.Column('database_version_id', sa.Integer(), nullable=True), schema='logs')
    op.create_index(op.f('ix_logs_logs_action'), 'logs', ['action'], unique=False, schema='logs')
    op.create_index(op.f('ix_logs_logs_database_version_id'), 'logs', ['database_version_id'], unique=False, schema='logs')
    op.create_index(op.f('ix_logs_logs_entity_id'), 'logs', ['entity_id'], unique=False, schema='logs')
    op.create_index(op.f('ix_logs_logs_entity_type'), 'logs', ['entity_type'], unique=False, schema='logs')
    op.create_index(op.f('ix_logs_logs_timestamp'), 'logs', ['timestamp'], unique=False, schema='logs')
    op.create_index(op.f('ix_logs_logs_username'), 'logs', ['username'], unique=False, schema='logs')
    op.create_foreign_key(None, 'logs', 'database_versions', ['database_version_id'], ['id'], source_schema='logs', referent_schema='generation', ondelete='SET NULL')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'logs', schema='logs', type_='foreignkey')
    op.drop_index(op.f('ix_logs_logs_username'), table_name='logs', schema='logs')
    op.drop_index(op.f('ix_logs_logs_timestamp'), table_name='logs', schema='logs')
    op.drop_index(op.f('ix_logs_logs_entity_type'), table_name='logs', schema='logs')
    op.drop_index(op.f('ix_logs_logs_entity_id'), table_name='logs', schema='logs')
    op.drop_index(op.f('ix_logs_logs_database_version_id'), table_name='logs', schema='logs')
    op.drop_index(op.f('ix_logs_logs_action'), table_name='logs', schema='logs')
    op.drop_column('logs', 'database_version_id', schema='logs')
    
    # ### end Alembic commands ###
