"""Добавлена разбивка на агрегаты ПГУ корр модел

Revision ID: 87740ed6db48
Revises: 075db04d97e0
Create Date: 2025-07-07 11:04:27.600639

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '87740ed6db48'
down_revision = '075db04d97e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pgu_machine_powers', schema=None) as batch_op:
        batch_op.alter_column('year_number',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('id_pgu_machine',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('p_ust',
               existing_type=mysql.DECIMAL(precision=25, scale=15),
               nullable=True)

    with op.batch_alter_table('pgu_machines', schema=None) as batch_op:
        batch_op.alter_column('machine_number',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pgu_machines', schema=None) as batch_op:
        batch_op.alter_column('machine_number',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)

    with op.batch_alter_table('pgu_machine_powers', schema=None) as batch_op:
        batch_op.alter_column('p_ust',
               existing_type=mysql.DECIMAL(precision=25, scale=15),
               nullable=False)
        batch_op.alter_column('id_pgu_machine',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('year_number',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
