"""скорректирована модел stations и eneryarea

Revision ID: 89738a7ad278
Revises: d8da66fe1fb9
Create Date: 2025-04-09 15:36:45.824638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89738a7ad278'
down_revision = 'd8da66fe1fb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_energy_area', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'energy_areas', ['id_energy_area'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_energy_area')

    # ### end Alembic commands ###
