"""добавлено топливо со еэс в модель machines

Revision ID: 8a8bc761c645
Revises: b46db86362c0
Create Date: 2025-03-17 09:29:41.429605

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a8bc761c645'
down_revision = 'b46db86362c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fuel_so', sa.String(length=255), nullable=False))

    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.drop_column('fuel')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fuel', mysql.VARCHAR(length=80), nullable=True))

    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.drop_column('fuel_so')

    # ### end Alembic commands ###
