"""добавлены индексы

Revision ID: 8b053f7f64ba
Revises: e84047ae762f
Create Date: 2025-06-30 15:47:15.130436

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b053f7f64ba'
down_revision = 'e84047ae762f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine_fuels', schema=None) as batch_op:
        batch_op.create_index('ix_machine_fuel_id_fuel', ['id_fuel'], unique=False)
        batch_op.create_index('ix_machine_fuel_id_machine', ['id_machine'], unique=False)

    with op.batch_alter_table('machine_tes_types', schema=None) as batch_op:
        batch_op.create_index('ix_machine_tes_type_id_machine', ['id_machine'], unique=False)
        batch_op.create_index('ix_machine_tes_type_id_tes_type', ['id_tes_type'], unique=False)
        batch_op.create_index('ix_machine_tes_type_year_number', ['year_number'], unique=False)

    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.create_index('ix_machine_date_decompressing_expected', ['date_decompressing_expected'], unique=False)
        batch_op.create_index('ix_machine_date_exploitation', ['date_exploitation'], unique=False)
        batch_op.create_index('ix_machine_date_modernization_expected', ['date_modernization_expected'], unique=False)
        batch_op.create_index('ix_machine_id_condition_type', ['id_condition_type'], unique=False)
        batch_op.create_index('ix_machine_id_station', ['id_station'], unique=False)
        batch_op.create_index('ix_machine_id_station_type', ['id_station_type'], unique=False)
        batch_op.create_index('ix_machine_id_tes_machine_type', ['id_tes_machine_type'], unique=False)

    with op.batch_alter_table('regional_districts', schema=None) as batch_op:
        batch_op.alter_column('region_number',
               existing_type=mysql.VARCHAR(length=3),
               nullable=True)
        batch_op.create_unique_constraint(None, ['region_number'])

    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.create_index('ix_station_id_regional_district', ['id_regional_district'], unique=False)
        batch_op.create_index('ix_station_name', ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.drop_index('ix_station_name')
        batch_op.drop_index('ix_station_id_regional_district')

    with op.batch_alter_table('regional_districts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('region_number',
               existing_type=mysql.VARCHAR(length=3),
               nullable=False)

    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.drop_index('ix_machine_id_tes_machine_type')
        batch_op.drop_index('ix_machine_id_station_type')
        batch_op.drop_index('ix_machine_id_station')
        batch_op.drop_index('ix_machine_id_condition_type')
        batch_op.drop_index('ix_machine_date_modernization_expected')
        batch_op.drop_index('ix_machine_date_exploitation')
        batch_op.drop_index('ix_machine_date_decompressing_expected')

    with op.batch_alter_table('machine_tes_types', schema=None) as batch_op:
        batch_op.drop_index('ix_machine_tes_type_year_number')
        batch_op.drop_index('ix_machine_tes_type_id_tes_type')
        batch_op.drop_index('ix_machine_tes_type_id_machine')

    with op.batch_alter_table('machine_fuels', schema=None) as batch_op:
        batch_op.drop_index('ix_machine_fuel_id_machine')
        batch_op.drop_index('ix_machine_fuel_id_fuel')

    # ### end Alembic commands ###
