"""create_documents_kommod_table

Revision ID: 9191beb069db
Revises: bcee7b415f5d
Create Date: 2025-10-15 10:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9191beb069db'
down_revision = 'bcee7b415f5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Создание таблицы documents_kommod в схеме generation
    op.create_table('documents_kommod',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('display_order', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('display_order'),
        sa.UniqueConstraint('name'),
        schema='generation'
    )
    
    # Создание индексов
    op.create_index(op.f('ix_generation_documents_kommod_display_order'), 'documents_kommod', ['display_order'], unique=True, schema='generation')
    op.create_index(op.f('ix_generation_documents_kommod_name'), 'documents_kommod', ['name'], unique=True, schema='generation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаление индексов
    op.drop_index(op.f('ix_generation_documents_kommod_name'), table_name='documents_kommod', schema='generation')
    op.drop_index(op.f('ix_generation_documents_kommod_display_order'), table_name='documents_kommod', schema='generation')
    
    # Удаление таблицы documents_kommod из схемы generation
    op.drop_table('documents_kommod', schema='generation')
    # ### end Alembic commands ###

