"""add_file_fields_to_documents_kommod

Revision ID: 94c8f8d6f836
Revises: 9191beb069db
Create Date: 2025-10-15 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94c8f8d6f836'
down_revision = '9191beb069db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавление полей для хранения файлов в таблицу documents_kommod
    op.add_column('documents_kommod', sa.Column('file_path', sa.String(length=500), nullable=True), schema='generation')
    op.add_column('documents_kommod', sa.Column('file_name', sa.String(length=255), nullable=True), schema='generation')
    op.add_column('documents_kommod', sa.Column('file_size', sa.Integer(), nullable=True), schema='generation')
    op.add_column('documents_kommod', sa.Column('file_type', sa.String(length=100), nullable=True), schema='generation')
    op.add_column('documents_kommod', sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True), schema='generation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаление полей для хранения файлов из таблицы documents_kommod
    op.drop_column('documents_kommod', 'uploaded_at', schema='generation')
    op.drop_column('documents_kommod', 'file_type', schema='generation')
    op.drop_column('documents_kommod', 'file_size', schema='generation')
    op.drop_column('documents_kommod', 'file_name', schema='generation')
    op.drop_column('documents_kommod', 'file_path', schema='generation')
    # ### end Alembic commands ###

