"""добавлено поле в пользователя для поиска

Revision ID: 94fa19439b16
Revises: e63319f0c381
Create Date: 2025-08-20 15:56:38.014136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94fa19439b16'
down_revision = 'e63319f0c381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_roles_name_full', table_name='roles', schema='auth')
    op.drop_constraint('uq_roles_name_full', 'roles', schema='auth', type_='unique')
    op.create_index(op.f('ix_auth_roles_name_full'), 'roles', ['name_full'], unique=True, schema='auth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_roles_name_full'), table_name='roles', schema='auth')
    op.create_unique_constraint('uq_roles_name_full', 'roles', ['name_full'], schema='auth')
    op.create_index('ix_roles_name_full', 'roles', ['name_full'], unique=False, schema='auth')
    # ### end Alembic commands ###
