"""remove_display_order_from_documents

Revision ID: 9862b899207c
Revises: 94c8f8d6f836
Create Date: 2025-10-16 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9862b899207c'
down_revision = '94c8f8d6f836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаление индекса для display_order
    op.drop_index('ix_generation_documents_kommod_display_order', table_name='documents_kommod', schema='generation')
    
    # Удаление столбца display_order
    op.drop_column('documents_kommod', 'display_order', schema='generation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавление столбца display_order обратно
    op.add_column('documents_kommod', sa.Column('display_order', sa.Integer(), nullable=True), schema='generation')
    
    # Создание индекса для display_order
    op.create_index('ix_generation_documents_kommod_display_order', 'documents_kommod', ['display_order'], unique=True, schema='generation')
    # ### end Alembic commands ###

