"""добавлена модель energyunit и скорректированы остальные модели

Revision ID: 98bc287af3d6
Revises: 89738a7ad278
Create Date: 2025-04-11 10:49:39.529420

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '98bc287af3d6'
down_revision = '89738a7ad278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_energy_unit', sa.Integer(), nullable=False))
        batch_op.drop_constraint('stations_ibfk_4', type_='foreignkey')
        batch_op.create_foreign_key(None, 'energy_units', ['id_energy_unit'], ['id'], ondelete='RESTRICT')
        batch_op.drop_column('id_energy_area')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_energy_area', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('stations_ibfk_4', 'energy_areas', ['id_energy_area'], ['id'], ondelete='RESTRICT')
        batch_op.drop_column('id_energy_unit')

    with op.batch_alter_table('energy_areas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_regional_energy_system', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('energy_areas_ibfk_1', 'regional_energy_systems', ['id_regional_energy_system'], ['id'], ondelete='RESTRICT')
        batch_op.drop_column('id_regional_district')

    # ### end Alembic commands ###
