"""переопределение полей для годов в модели machine

Revision ID: a66982ee17a3
Revises: b76c1114a0a0
Create Date: 2025-05-07 15:29:29.733304

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a66982ee17a3'
down_revision = 'b76c1114a0a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.alter_column('date_decompressing_expected',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('date_modernization_expected',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_commission_expected', mysql.VARCHAR(length=10), nullable=True))
        batch_op.alter_column('date_modernization_expected',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)


    # ### end Alembic commands ###
