"""обновлена модель Station в части уникальности названия в привязке к субъекту повторно

Revision ID: b6ef013451bf
Revises: 5fbfe53b59eb
Create Date: 2025-05-07 10:11:42.923342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6ef013451bf'
down_revision = '5fbfe53b59eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stations_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stations_name'))

    # ### end Alembic commands ###
