"""initial schema

Revision ID: b7c452cfc164
Revises: f7b27212e10f
Create Date: 2025-10-03 10:38:13.202354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7c452cfc164'
down_revision = 'f7b27212e10f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'machine_fuels', 'fuels', ['id_fuel'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machine_fuels', 'years', ['year_number'], ['number'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machine_powers', 'years', ['year_number'], ['number'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machine_tes_types', 'years', ['year_number'], ['number'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machine_tes_types', 'tes_types', ['id_tes_type'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'tes_machine_types', ['id_tes_machine_type'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'machine_types', ['id_machine_type'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'condition_types', ['id_condition_type'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'gen_companies', ['id_gen_company'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'energy_areas', ['id_energy_area'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'equipment_groups', ['id_equipment_group'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'station_types', ['id_station_type'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'pgu_machine_powers', 'years', ['year_number'], ['number'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'pgu_machines', 'condition_types', ['id_condition_type'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'pgu_machines', 'equipment_groups', ['id_equipment_group_pgu'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'pgu_machines', 'pgu_tes_machine_types', ['id_pgu_tes_machine_type'], ['id'], source_schema='generation', referent_schema='refdata')
    op.create_foreign_key(None, 'pgu_machines', 'tes_machine_types', ['id_tes_machine_type'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'station_powers', 'years', ['year_number'], ['number'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'stations', 'energy_units', ['id_energy_unit'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'stations', 'condition_types', ['id_condition_type'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'stations', 'regional_districts', ['id_regional_district'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.add_column('equipment_groups', sa.Column('equipment_group_type', sa.String(length=50), nullable=True, comment='Тип группы оборудования'), schema='refdata')
    op.add_column('equipment_groups', sa.Column('technology_type', sa.Enum('открытая', 'закрытая', 'перспективная', name='technology_type_enum'), nullable=True, comment='Тип технологии'), schema='refdata')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment_groups', 'technology_type', schema='refdata')
    op.drop_column('equipment_groups', 'equipment_group_type', schema='refdata')
    op.drop_constraint(None, 'stations', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'stations', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'stations', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'station_powers', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'pgu_machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'pgu_machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'pgu_machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'pgu_machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'pgu_machine_powers', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machine_tes_types', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machine_tes_types', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machine_powers', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machine_fuels', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machine_fuels', schema='generation', type_='foreignkey')
    # ### end Alembic commands ###
