"""Fix migration issue

Revision ID: b95eb3c42e5e
Revises: 8fa600b0611b
Create Date: 2025-03-10 12:01:10.695802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b95eb3c42e5e'
down_revision = '8fa600b0611b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('machine_fuel_year_association')
    op.drop_table('machine_power_year_association')
    op.drop_table('machine_tes_type_year_association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine_tes_type_year_association',
    sa.Column('machine_tes_type_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('year_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['machine_tes_type_id'], ['machine_tes_types.id'], name='machine_tes_type_year_association_ibfk_1', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['year_id'], ['years.id'], name='machine_tes_type_year_association_ibfk_2', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('machine_tes_type_id', 'year_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('machine_power_year_association',
    sa.Column('machine_power_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('year_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['machine_power_id'], ['machine_powers.id'], name='machine_power_year_association_ibfk_1', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['year_id'], ['years.id'], name='machine_power_year_association_ibfk_2', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('machine_power_id', 'year_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('machine_fuel_year_association',
    sa.Column('machine_fuel_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('year_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['machine_fuel_id'], ['machine_fuels.id'], name='machine_fuel_year_association_ibfk_1', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['year_id'], ['years.id'], name='machine_fuel_year_association_ibfk_2', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('machine_fuel_id', 'year_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
