"""add_display_order_to_union_energy_system

Revision ID: bcee7b415f5d
Revises: e03500c2c57c
Create Date: 2025-10-13 10:51:30.405207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcee7b415f5d'
down_revision = 'e03500c2c57c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавление столбца display_order в таблицу union_energy_systems
    op.add_column('union_energy_systems', sa.Column('display_order', sa.Integer(), nullable=True), schema='refdata')
    op.create_index(op.f('ix_refdata_union_energy_systems_display_order'), 'union_energy_systems', ['display_order'], unique=False, schema='refdata')
  
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаление столбца display_order из таблицы union_energy_systems
    op.drop_index(op.f('ix_refdata_union_energy_systems_display_order'), table_name='union_energy_systems', schema='refdata')
    op.drop_column('union_energy_systems', 'display_order', schema='refdata')

    # ### end Alembic commands ###
