"""скорректированы имена для станций в модели stations

Revision ID: c7bc2be701d7
Revises: 8a8bc761c645
Create Date: 2025-03-19 14:08:05.348649

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7bc2be701d7'
down_revision = '8a8bc761c645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_so', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('name_archive', sa.String(length=80), nullable=True))
        batch_op.drop_index('name_additional')
        batch_op.drop_index('name_owner')
        batch_op.create_unique_constraint(None, ['name_archive'])
        batch_op.create_unique_constraint(None, ['name_so'])
        batch_op.drop_column('name_owner')
        batch_op.drop_column('name_additional')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_additional', mysql.VARCHAR(length=80), nullable=True))
        batch_op.add_column(sa.Column('name_owner', mysql.VARCHAR(length=80), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('name_owner', ['name_owner'], unique=True)
        batch_op.create_index('name_additional', ['name_additional'], unique=True)
        batch_op.drop_column('name_archive')
        batch_op.drop_column('name_so')

    # ### end Alembic commands ###
