"""поменяны технологии

Revision ID: d6fecf8ccd7b
Revises: b7c452cfc164
Create Date: 2025-10-08 12:10:56.587247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6fecf8ccd7b'
down_revision = 'b7c452cfc164'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technologies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='refdata'
    )
    op.create_index(op.f('ix_refdata_technologies_name'), 'technologies', ['name'], unique=True, schema='refdata')
    op.create_table('technology_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='refdata'
    )
    op.create_index(op.f('ix_refdata_technology_types_name'), 'technology_types', ['name'], unique=True, schema='refdata')
    op.create_foreign_key(None, 'machine_fuels', 'years', ['year_number'], ['number'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machine_fuels', 'fuels', ['id_fuel'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machine_powers', 'years', ['year_number'], ['number'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machine_tes_types', 'tes_types', ['id_tes_type'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machine_tes_types', 'years', ['year_number'], ['number'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.add_column('machines', sa.Column('id_technology', sa.Integer(), nullable=True), schema='generation')
    op.add_column('machines', sa.Column('id_technology_type', sa.Integer(), nullable=True), schema='generation')
    op.create_index(op.f('ix_generation_machines_id_technology'), 'machines', ['id_technology'], unique=False, schema='generation')
    op.create_index(op.f('ix_generation_machines_id_technology_type'), 'machines', ['id_technology_type'], unique=False, schema='generation')
    op.create_foreign_key(None, 'machines', 'equipment_groups', ['id_equipment_group'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'condition_types', ['id_condition_type'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'machine_types', ['id_machine_type'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'tes_machine_types', ['id_tes_machine_type'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'energy_areas', ['id_energy_area'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'technology_types', ['id_technology_type'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'technologies', ['id_technology'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'station_types', ['id_station_type'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'machines', 'gen_companies', ['id_gen_company'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'pgu_machine_powers', 'years', ['year_number'], ['number'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'pgu_machines', 'condition_types', ['id_condition_type'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'pgu_machines', 'pgu_tes_machine_types', ['id_pgu_tes_machine_type'], ['id'], source_schema='generation', referent_schema='refdata')
    op.create_foreign_key(None, 'pgu_machines', 'tes_machine_types', ['id_tes_machine_type'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'station_powers', 'years', ['year_number'], ['number'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'stations', 'condition_types', ['id_condition_type'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'stations', 'energy_units', ['id_energy_unit'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.create_foreign_key(None, 'stations', 'regional_districts', ['id_regional_district'], ['id'], source_schema='generation', referent_schema='refdata', ondelete='RESTRICT')
    op.add_column('equipment_groups', sa.Column('id_technology', sa.Integer(), nullable=True), schema='refdata')
    op.add_column('equipment_groups', sa.Column('id_technology_type', sa.Integer(), nullable=True), schema='refdata')
    op.create_index(op.f('ix_refdata_equipment_groups_id_technology'), 'equipment_groups', ['id_technology'], unique=False, schema='refdata')
    op.create_index(op.f('ix_refdata_equipment_groups_id_technology_type'), 'equipment_groups', ['id_technology_type'], unique=False, schema='refdata')
    op.create_foreign_key(None, 'equipment_groups', 'technologies', ['id_technology'], ['id'], source_schema='refdata', referent_schema='refdata', ondelete='SET NULL')
    op.create_foreign_key(None, 'equipment_groups', 'technology_types', ['id_technology_type'], ['id'], source_schema='refdata', referent_schema='refdata', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'equipment_groups', schema='refdata', type_='foreignkey')
    op.drop_constraint(None, 'equipment_groups', schema='refdata', type_='foreignkey')
    op.drop_index(op.f('ix_refdata_equipment_groups_id_technology_type'), table_name='equipment_groups', schema='refdata')
    op.drop_index(op.f('ix_refdata_equipment_groups_id_technology'), table_name='equipment_groups', schema='refdata')
    op.drop_column('equipment_groups', 'id_technology_type', schema='refdata')
    op.drop_column('equipment_groups', 'id_technology', schema='refdata')
    op.drop_constraint(None, 'stations', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'stations', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'stations', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'station_powers', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'pgu_machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'pgu_machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'pgu_machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'pgu_machine_powers', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machines', schema='generation', type_='foreignkey')
    op.drop_index(op.f('ix_generation_machines_id_technology_type'), table_name='machines', schema='generation')
    op.drop_index(op.f('ix_generation_machines_id_technology'), table_name='machines', schema='generation')
    op.drop_column('machines', 'id_technology_type', schema='generation')
    op.drop_column('machines', 'id_technology', schema='generation')
    op.drop_constraint(None, 'machine_tes_types', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machine_tes_types', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machine_powers', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machine_fuels', schema='generation', type_='foreignkey')
    op.drop_constraint(None, 'machine_fuels', schema='generation', type_='foreignkey')
    op.drop_index(op.f('ix_refdata_technology_types_name'), table_name='technology_types', schema='refdata')
    op.drop_table('technology_types', schema='refdata')
    op.drop_index(op.f('ix_refdata_technologies_name'), table_name='technologies', schema='refdata')
    op.drop_table('technologies', schema='refdata')
    # ### end Alembic commands ###
