"""Пересоздание миграций

Revision ID: e830376ebb7f
Revises: 33bafce6a387
Create Date: 2025-04-15 15:29:22.783887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e830376ebb7f'
down_revision = '33bafce6a387'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('energy_units', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'regional_energy_systems', ['id_regional_energy_system'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('energy_units', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
