"""add_entity_fields_to_logs

Revision ID: ffbd4f9038d6
Revises: 45cb62e688a6
Create Date: 2025-09-29 11:11:31.426948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffbd4f9038d6'
down_revision = '45cb62e688a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('entity_type', sa.String(length=50), nullable=True), schema='logs')
    op.add_column('logs', sa.Column('entity_id', sa.Integer(), nullable=True), schema='logs')
    op.create_index(op.f('ix_logs_logs_entity_type'), 'logs', ['entity_type'], unique=False, schema='logs')
    op.create_index(op.f('ix_logs_logs_entity_id'), 'logs', ['entity_id'], unique=False, schema='logs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_logs_entity_id'), table_name='logs', schema='logs')
    op.drop_index(op.f('ix_logs_logs_entity_type'), table_name='logs', schema='logs')
    op.drop_column('logs', 'entity_id', schema='logs')
    op.drop_column('logs', 'entity_type', schema='logs')
    # ### end Alembic commands ###
