# -*- coding: utf-8 -*-
"""Комментарии к таблицам и полям схем gs_ec, gs_pd и gs_fue (по классам моделей).

Revision ID: s2t3u4v5w6x7
Revises: q0r1s2t3u4v5
Create Date: 2026-06-05
"""
import os
import sys

from alembic import op
from sqlalchemy import text

_MIGRATIONS = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))
if _MIGRATIONS not in sys.path:
    sys.path.insert(0, _MIGRATIONS)
import column_utils  # noqa: E402

revision = "s2t3u4v5w6x7"
down_revision = "q0r1s2t3u4v5"
branch_labels = None
depends_on = None

_SCHEMA_COMMENTS: dict[str, dict[str, dict[str, str]]] = {
    'gs_ec': {
        'gs_ec_centralized_zone_consumption_params': {
            "_table": 'Параметры потребления электроэнергии для централизованной зоны (агрегат без FK)',
            'created_at': 'Дата и время создания записи',
            'created_by': 'Пользователь, создавший запись',
            'database_version_id': 'Версия базы данных (FK -> gs_sys.gs_database_versions)',
            'energy_consumption_mln_kvt_ch': 'Потребление электрической энергии, млн кВтч',
            'energy_consumption_sipr_mln_kvt_ch': 'Потребление электрической энергии (СиПР), млн кВтч',
            'id': 'Уникальный идентификатор записи',
            'modified_by': 'Пользователь, последним изменивший запись',
            'note': 'Примечание',
            'perimeter_variant_code': 'Код варианта периметра (NULL — без варианта)',
            'updated_at': 'Дата и время последнего изменения записи',
            'year_number': 'Год',
        },
        'gs_ec_ees_consumption_params': {
            "_table": 'Параметры потребления электроэнергии для ЭЭС (без FK на справочник)',
            'created_at': 'Дата и время создания записи',
            'created_by': 'Пользователь, создавший запись',
            'database_version_id': 'Версия базы данных (FK -> gs_sys.gs_database_versions)',
            'energy_consumption_mln_kvt_ch': 'Потребление электроэнергии, млн кВтч',
            'energy_consumption_sipr_mln_kvt_ch': 'Потребление электроэнергии (СИПР), млн кВтч',
            'id': 'Уникальный идентификатор записи',
            'modified_by': 'Пользователь, последним изменивший запись',
            'note': 'Примечание',
            'perimeter_variant_code': 'Код варианта периметра (NULL — без варианта)',
            'updated_at': 'Дата и время последнего изменения записи',
            'year_number': 'Номер года',
        },
        'gs_ec_ees_russia_consumption_params': {
            "_table": 'Параметры потребления для ЕЭС России',
            'created_at': 'Дата и время создания записи',
            'created_by': 'Пользователь, создавший запись',
            'database_version_id': 'Версия базы данных (FK -> gs_sys.gs_database_versions)',
            'energy_consumption_mln_kvt_ch': 'Потребление электроэнергии, млн кВтч',
            'energy_consumption_sipr_mln_kvt_ch': 'Потребление электроэнергии (СИПР), млн кВтч',
            'id': 'Уникальный идентификатор записи',
            'modified_by': 'Пользователь, последним изменивший запись',
            'note': 'Примечание',
            'perimeter_variant_code': 'Код варианта периметра (NULL — без варианта)',
            'updated_at': 'Дата и время последнего изменения записи',
            'year_number': 'Номер года',
        },
        'gs_ec_electrical_intensity_formula_texts': {
            "_table": 'Переопределения текстов формул для страницы электроёмкости',
            'created_at': 'Дата и время создания записи',
            'created_by': 'Пользователь, создавший запись',
            'formula_key': 'Ключ формулы',
            'formula_text': 'Текст формулы',
            'id': 'Уникальный идентификатор записи',
            'modified_by': 'Пользователь, последним изменивший запись',
            'updated_at': 'Дата и время последнего изменения записи',
        },
        'gs_ec_energy_area_consumption_params': {
            "_table": 'Параметры потребления для энергорайона (EnergyArea)',
            'created_at': 'Дата и время создания записи',
            'created_by': 'Пользователь, создавший запись',
            'database_version_id': 'Версия базы данных (FK -> gs_sys.gs_database_versions)',
            'energy_consumption_mln_kvt_ch': 'Потребление электроэнергии, млн кВтч',
            'energy_consumption_sipr_mln_kvt_ch': 'Потребление электроэнергии (СИПР), млн кВтч',
            'id': 'Уникальный идентификатор записи',
            'id_energy_area': 'Энергорайон (FK -> gs_sys.gs_sys_energy_areas)',
            'modified_by': 'Пользователь, последним изменивший запись',
            'note': 'Примечание',
            'perimeter_variant_code': 'Код варианта периметра (NULL — без варианта)',
            'updated_at': 'Дата и время последнего изменения записи',
            'year_number': 'Номер года',
        },
        'gs_ec_energy_system_type_consumption_params': {
            "_table": 'Параметры потребления для типа энергосистемы',
            'created_at': 'Дата и время создания записи',
            'created_by': 'Пользователь, создавший запись',
            'database_version_id': 'Версия базы данных (FK -> gs_sys.gs_database_versions)',
            'energy_consumption_mln_kvt_ch': 'Потребление электроэнергии, млн кВтч',
            'energy_consumption_sipr_mln_kvt_ch': 'Потребление электроэнергии (СИПР), млн кВтч',
            'id': 'Уникальный идентификатор записи',
            'id_energy_system_type': 'Тип энергосистемы (FK -> gs_sys.gs_sys_energy_system_types)',
            'modified_by': 'Пользователь, последним изменивший запись',
            'note': 'Примечание',
            'perimeter_variant_code': 'Код варианта периметра (NULL — без варианта)',
            'updated_at': 'Дата и время последнего изменения записи',
            'year_number': 'Номер года',
        },
        'gs_ec_energy_unit_consumption_params': {
            "_table": 'Параметры потребления для энергоузла',
            'created_at': 'Дата и время создания записи',
            'created_by': 'Пользователь, создавший запись',
            'database_version_id': 'Версия базы данных (FK -> gs_sys.gs_database_versions)',
            'energy_consumption_mln_kvt_ch': 'Потребление электроэнергии, млн кВтч',
            'energy_consumption_sipr_mln_kvt_ch': 'Потребление электроэнергии (СИПР), млн кВтч',
            'id': 'Уникальный идентификатор записи',
            'id_energy_unit': 'Энергоузел (FK -> gs_sys.gs_sys_energy_units)',
            'modified_by': 'Пользователь, последним изменивший запись',
            'note': 'Примечание',
            'perimeter_variant_code': 'Код варианта периметра (NULL — без варианта)',
            'updated_at': 'Дата и время последнего изменения записи',
            'year_number': 'Номер года',
        },
        'gs_ec_energy_zone_consumption_params': {
            "_table": 'Параметры потребления для энергозоны',
            'created_at': 'Дата и время создания записи',
            'created_by': 'Пользователь, создавший запись',
            'database_version_id': 'Версия базы данных (FK -> gs_sys.gs_database_versions)',
            'energy_consumption_mln_kvt_ch': 'Потребление электроэнергии, млн кВтч',
            'energy_consumption_sipr_mln_kvt_ch': 'Потребление электроэнергии (СИПР), млн кВтч',
            'id': 'Уникальный идентификатор записи',
            'id_energy_zone': 'Энергозона (FK -> gs_sys.gs_sys_energy_zones)',
            'modified_by': 'Пользователь, последним изменивший запись',
            'note': 'Примечание',
            'perimeter_variant_code': 'Код варианта периметра (NULL — без варианта)',
            'updated_at': 'Дата и время последнего изменения записи',
            'year_number': 'Номер года',
        },
        'gs_ec_federal_district_consumption_params': {
            "_table": 'Параметры потребления для федерального округа',
            'created_at': 'Дата и время создания записи',
            'created_by': 'Пользователь, создавший запись',
            'database_version_id': 'Версия базы данных (FK -> gs_sys.gs_database_versions)',
            'energy_consumption_mln_kvt_ch': 'Потребление электроэнергии, млн кВтч',
            'energy_consumption_sipr_mln_kvt_ch': 'Потребление электроэнергии (СИПР), млн кВтч',
            'id': 'Уникальный идентификатор записи',
            'id_federal_district': 'Федеральный округ (FK -> gs_sys.gs_sys_federal_districts)',
            'modified_by': 'Пользователь, последним изменивший запись',
            'note': 'Примечание',
            'perimeter_variant_code': 'Код варианта периметра (NULL — без варианта)',
            'updated_at': 'Дата и время последнего изменения записи',
            'year_number': 'Номер года',
        },
        'gs_ec_federal_district_electrical_intensity_coefficients': {
            "_table": 'Коэффициенты A и X электроёмкости для федерального округа',
            'coefficient_a': 'Коэффициент A',
            'coefficient_x': 'Коэффициент X',
            'created_at': 'Дата и время создания записи',
            'created_by': 'Пользователь, создавший запись',
            'database_version_id': 'Версия базы данных (FK -> gs_sys.gs_database_versions)',
            'id': 'Уникальный идентификатор записи',
            'id_economic_activity_type': 'Вид экономической деятельности (FK -> gs_sys.gs_sys_economic_activity_types)',
            'id_federal_district': 'Федеральный округ (FK -> gs_sys.gs_sys_federal_districts)',
            'modified_by': 'Пользователь, последним изменивший запись',
            'note': 'Примечание',
            'updated_at': 'Дата и время последнего изменения записи',
        },
        'gs_ec_federal_district_electrical_intensity_year_params': {
            "_table": 'Электроёмкость по годам для федерального округа (долгосрочный прогноз)',
            'created_at': 'Дата и время создания записи',
            'created_by': 'Пользователь, создавший запись',
            'database_version_id': 'Версия базы данных (FK -> gs_sys.gs_database_versions)',
            'id': 'Уникальный идентификатор записи',
            'id_economic_activity_type': 'Вид экономической деятельности (FK -> gs_sys.gs_sys_economic_activity_types)',
            'id_federal_district': 'Федеральный округ (FK -> gs_sys.gs_sys_federal_districts)',
            'modified_by': 'Пользователь, последним изменивший запись',
            'note': 'Примечание',
            'parameter_value': 'Значение показателя за год (кВтч/тыс. руб., зависит от row_kind)',
            'row_kind': 'Тип строки показателя (intensity, graph_point, calculated, delta)',
            'updated_at': 'Дата и время последнего изменения записи',
            'year_number': 'Номер года',
        },
        'gs_ec_federal_district_population_consumption_coefficients': {
            "_table": 'Коэффициенты A и X блока «Население» на странице электроёмкости (ФО)',
            'coefficient_a': 'Коэффициент A',
            'coefficient_x': 'Коэффициент X',
            'created_at': 'Дата и время создания записи',
            'created_by': 'Пользователь, создавший запись',
            'database_version_id': 'Версия базы данных (FK -> gs_sys.gs_database_versions)',
            'id': 'Уникальный идентификатор записи',
            'id_federal_district': 'Федеральный округ (FK -> gs_sys.gs_sys_federal_districts)',
            'modified_by': 'Пользователь, последним изменивший запись',
            'note': 'Примечание',
            'updated_at': 'Дата и время последнего изменения записи',
        },
        'gs_ec_federal_district_population_consumption_year_params': {
            "_table": 'Показатели блока «Население» по годам для федерального округа',
            'created_at': 'Дата и время создания записи',
            'created_by': 'Пользователь, создавший запись',
            'database_version_id': 'Версия базы данных (FK -> gs_sys.gs_database_versions)',
            'id': 'Уникальный идентификатор записи',
            'id_federal_district': 'Федеральный округ (FK -> gs_sys.gs_sys_federal_districts)',
            'modified_by': 'Пользователь, последним изменивший запись',
            'note': 'Примечание',
            'parameter_value': 'Значение показателя за год (кВтч/чел., зависит от row_kind)',
            'row_kind': 'Тип строки показателя (intensity, graph_point, calculated, delta)',
            'updated_at': 'Дата и время последнего изменения записи',
            'year_number': 'Номер года',
        },
        'gs_ec_regional_district_consumption_params': {
            "_table": 'Параметры потребления для субъекта РФ',
            'created_at': 'Дата и время создания записи',
            'created_by': 'Пользователь, создавший запись',
            'database_version_id': 'Версия базы данных (FK -> gs_sys.gs_database_versions)',
            'energy_consumption_mln_kvt_ch': 'Потребление электроэнергии, млн кВтч',
            'energy_consumption_sipr_mln_kvt_ch': 'Потребление электроэнергии (СИПР), млн кВтч',
            'id': 'Уникальный идентификатор записи',
            'id_regional_district': 'Субъект РФ (FK -> gs_sys.gs_sys_regional_districts)',
            'modified_by': 'Пользователь, последним изменивший запись',
            'note': 'Примечание',
            'perimeter_variant_code': 'Код варианта периметра (NULL — без варианта)',
            'updated_at': 'Дата и время последнего изменения записи',
            'year_number': 'Номер года',
        },
        'gs_ec_regional_energy_system_consumption_params': {
            "_table": 'Параметры потребления для региональной энергосистемы',
            'created_at': 'Дата и время создания записи',
            'created_by': 'Пользователь, создавший запись',
            'database_version_id': 'Версия базы данных (FK -> gs_sys.gs_database_versions)',
            'energy_consumption_mln_kvt_ch': 'Потребление электроэнергии, млн кВтч',
            'energy_consumption_sipr_mln_kvt_ch': 'Потребление электроэнергии (СИПР), млн кВтч',
            'id': 'Уникальный идентификатор записи',
            'id_regional_energy_system': 'Региональная энергосистема (FK -> gs_sys.gs_sys_regional_energy_systems)',
            'modified_by': 'Пользователь, последним изменивший запись',
            'note': 'Примечание',
            'perimeter_variant_code': 'Код варианта периметра (NULL — без варианта)',
            'updated_at': 'Дата и время последнего изменения записи',
            'year_number': 'Номер года',
        },
        'gs_ec_russia_federation_consumption_params': {
            "_table": 'Параметры потребления для РФ (агрегат без строки справочника)',
            'created_at': 'Дата и время создания записи',
            'created_by': 'Пользователь, создавший запись',
            'database_version_id': 'Версия базы данных (FK -> gs_sys.gs_database_versions)',
            'energy_consumption_mln_kvt_ch': 'Потребление электроэнергии, млн кВтч',
            'energy_consumption_sipr_mln_kvt_ch': 'Потребление электроэнергии (СИПР), млн кВтч',
            'id': 'Уникальный идентификатор записи',
            'modified_by': 'Пользователь, последним изменивший запись',
            'note': 'Примечание',
            'perimeter_variant_code': 'Код варианта периметра (NULL — без варианта)',
            'updated_at': 'Дата и время последнего изменения записи',
            'year_number': 'Номер года',
        },
        'gs_ec_russia_federation_electrical_intensity_coefficients': {
            "_table": 'Коэффициенты A и X электроёмкости для РФ в целом',
            'coefficient_a': 'Коэффициент A',
            'coefficient_x': 'Коэффициент X',
            'created_at': 'Дата и время создания записи',
            'created_by': 'Пользователь, создавший запись',
            'database_version_id': 'Версия базы данных (FK -> gs_sys.gs_database_versions)',
            'id': 'Уникальный идентификатор записи',
            'modified_by': 'Пользователь, последним изменивший запись',
            'note': 'Примечание',
            'updated_at': 'Дата и время последнего изменения записи',
        },
        'gs_ec_russia_federation_electrical_intensity_year_params': {
            "_table": 'Электроёмкость по годам для РФ в целом (долгосрочный прогноз)',
            'created_at': 'Дата и время создания записи',
            'created_by': 'Пользователь, создавший запись',
            'database_version_id': 'Версия базы данных (FK -> gs_sys.gs_database_versions)',
            'id': 'Уникальный идентификатор записи',
            'modified_by': 'Пользователь, последним изменивший запись',
            'note': 'Примечание',
            'parameter_value': 'Значение показателя за год (кВтч/тыс. руб., зависит от row_kind)',
            'row_kind': 'Тип строки показателя (intensity, graph_point, calculated, delta)',
            'updated_at': 'Дата и время последнего изменения записи',
            'year_number': 'Номер года',
        },
        'gs_ec_summary_formula_texts': {
            "_table": 'Переопределения текстов формул (подсказки «i») для сводок потребления ЭЭ',
            'created_at': 'Дата и время создания записи',
            'created_by': 'Пользователь, создавший запись',
            'formula_key': 'Ключ формулы',
            'formula_text': 'Текст формулы',
            'id': 'Уникальный идентификатор записи',
            'modified_by': 'Пользователь, последним изменивший запись',
            'updated_at': 'Дата и время последнего изменения записи',
        },
        'gs_ec_synchronous_area_consumption_params': {
            "_table": 'Параметры потребления для синхронной зоны',
            'created_at': 'Дата и время создания записи',
            'created_by': 'Пользователь, создавший запись',
            'database_version_id': 'Версия базы данных (FK -> gs_sys.gs_database_versions)',
            'energy_consumption_mln_kvt_ch': 'Потребление электроэнергии, млн кВтч',
            'energy_consumption_sipr_mln_kvt_ch': 'Потребление электроэнергии (СИПР), млн кВтч',
            'id': 'Уникальный идентификатор записи',
            'id_synchronous_area': 'Синхронная зона (FK -> gs_sys.gs_sys_synchronous_areas)',
            'modified_by': 'Пользователь, последним изменивший запись',
            'note': 'Примечание',
            'perimeter_variant_code': 'Код варианта периметра (NULL — без варианта)',
            'updated_at': 'Дата и время последнего изменения записи',
            'year_number': 'Номер года',
        },
        'gs_ec_union_energy_system_consumption_params': {
            "_table": 'Параметры потребления для объединённой энергосистемы',
            'created_at': 'Дата и время создания записи',
            'created_by': 'Пользователь, создавший запись',
            'database_version_id': 'Версия базы данных (FK -> gs_sys.gs_database_versions)',
            'energy_consumption_mln_kvt_ch': 'Потребление электроэнергии, млн кВтч',
            'energy_consumption_sipr_mln_kvt_ch': 'Потребление электроэнергии (СИПР), млн кВтч',
            'id': 'Уникальный идентификатор записи',
            'id_union_energy_system': 'Объединённая энергосистема (FK -> gs_sys.gs_sys_union_energy_systems)',
            'modified_by': 'Пользователь, последним изменивший запись',
            'note': 'Примечание',
            'perimeter_variant_code': 'Код варианта периметра (NULL — без варианта)',
            'updated_at': 'Дата и время последнего изменения записи',
            'year_number': 'Номер года',
        },
    },
    'gs_pd': {
        'gs_pd_centralized_zone_demand_params': {
            "_table": 'Параметры нагрузки для Централизованной зоны (без FK на справочник)',
            'avg_daily_air_temp_c': 'Средняя дневная температура воздуха, °C',
            'created_at': 'Дата и время создания записи',
            'created_by': 'Пользователь, создавший запись',
            'database_version_id': 'Версия базы данных (FK -> gs_sys.gs_database_versions)',
            'id': 'Уникальный идентификатор записи',
            'is_historical_maximum': 'Признак исторического максимума (true — без года)',
            'max_power_consumption_mw': 'Максимальное потребление мощности, МВт',
            'modified_by': 'Пользователь, последним изменивший запись',
            'note': 'Примечание',
            'peak_datetime_msk': 'Дата и время максимума потребления мощности, МВт',
            'updated_at': 'Дата и время последнего изменения записи',
            'year_number': 'Год',
        },
        'gs_pd_ees_demand_params': {
            "_table": 'Параметры нагрузки для ЭЭС (отдельный сценарий, без привязки к справочнику типов энергосистем)',
            'avg_daily_air_temp_c': 'Средняя дневная температура воздуха, °C',
            'created_at': 'Дата и время создания записи',
            'created_by': 'Пользователь, создавший запись',
            'database_version_id': 'Версия базы данных (FK -> gs_sys.gs_database_versions)',
            'id': 'Уникальный идентификатор записи',
            'is_historical_maximum': 'Признак исторического максимума (true — без года)',
            'max_power_consumption_mw': 'Максимальное потребление мощности, МВт',
            'modified_by': 'Пользователь, последним изменивший запись',
            'note': 'Примечание',
            'peak_datetime_msk': 'Дата и время максимума потребления мощности, МВт',
            'updated_at': 'Дата и время последнего изменения записи',
            'year_number': 'Год',
        },
        'gs_pd_ees_russia_demand_params': {
            "_table": 'Параметры нагрузки для ЕЭС России без НТ',
            'avg_daily_air_temp_c': 'Средняя дневная температура воздуха, °C',
            'created_at': 'Дата и время создания записи',
            'created_by': 'Пользователь, создавший запись',
            'database_version_id': 'Версия базы данных (FK -> gs_sys.gs_database_versions)',
            'id': 'Уникальный идентификатор записи',
            'is_historical_maximum': 'Признак исторического максимума (true — без года)',
            'max_power_consumption_mw': 'Максимальное потребление мощности, МВт',
            'modified_by': 'Пользователь, последним изменивший запись',
            'note': 'Примечание',
            'peak_datetime_msk': 'Дата и время максимума потребления мощности, МВт',
            'perimeter_variant_code': 'Код варианта периметра (NULL — без варианта)',
            'updated_at': 'Дата и время последнего изменения записи',
            'year_number': 'Год',
        },
        'gs_pd_energy_area_demand_params': {
            "_table": 'Параметры нагрузки (demand) для энергоузла (EnergyArea)',
            'avg_daily_air_temp_c': 'Средняя дневная температура воздуха, °C',
            'combined_on_ees': 'Совмещенный максимум на ЕЭС, МВт',
            'combined_on_es': 'Совмещенный максимум на РЭС, МВт',
            'combined_on_oes': 'Совмещенный максимум на ОЭС, МВт',
            'created_at': 'Дата и время создания записи',
            'created_by': 'Пользователь, создавший запись',
            'database_version_id': 'Версия базы данных (FK -> gs_sys.gs_database_versions)',
            'id': 'Уникальный идентификатор записи',
            'id_energy_area': 'Энергорайон (FK -> gs_sys.gs_sys_energy_areas)',
            'is_historical_maximum': 'Признак исторического максимума (true — без года)',
            'max_power_consumption_mw': 'Максимальное потребление мощности, МВт',
            'modified_by': 'Пользователь, последним изменивший запись',
            'note': 'Примечание',
            'peak_datetime_msk': 'Дата и время максимума потребления мощности, МВт',
            'updated_at': 'Дата и время последнего изменения записи',
            'year_number': 'Год',
        },
        'gs_pd_energy_system_type_demand_params': {
            "_table": 'Параметры нагрузки (demand) для типа энергосистемы (EnergySystemType)',
            'avg_daily_air_temp_c': 'Средняя дневная температура воздуха, °C',
            'combined_on_ees': 'Совмещенный максимум на ЕЭС, МВт',
            'created_at': 'Дата и время создания записи',
            'created_by': 'Пользователь, создавший запись',
            'database_version_id': 'Версия базы данных (FK -> gs_sys.gs_database_versions)',
            'id': 'Уникальный идентификатор записи',
            'id_energy_system_type': 'Тип энергосистемы (FK -> gs_sys.gs_sys_energy_system_types)',
            'is_historical_maximum': 'Признак исторического максимума (true — без года)',
            'max_power_consumption_mw': 'Максимальное потребление мощности, МВт',
            'modified_by': 'Пользователь, последним изменивший запись',
            'note': 'Примечание',
            'peak_datetime_msk': 'Дата и время максимума потребления мощности, МВт',
            'updated_at': 'Дата и время последнего изменения записи',
            'year_number': 'Год',
        },
        'gs_pd_energy_unit_demand_params': {
            "_table": 'Параметры нагрузки (demand) для энергоузла (EnergyUnit)',
            'avg_daily_air_temp_c': 'Средняя дневная температура воздуха, °C',
            'combined_on_ees': 'Совмещенный максимум на ЕЭС, МВт',
            'combined_on_es': 'Совмещенный максимум на РЭС, МВт',
            'combined_on_oes': 'Совмещенный максимум на ОЭС, МВт',
            'created_at': 'Дата и время создания записи',
            'created_by': 'Пользователь, создавший запись',
            'database_version_id': 'Версия базы данных (FK -> gs_sys.gs_database_versions)',
            'id': 'Уникальный идентификатор записи',
            'id_energy_unit': 'Энергоузел (FK -> gs_sys.gs_sys_energy_units)',
            'is_historical_maximum': 'Признак исторического максимума (true — без года)',
            'max_power_consumption_mw': 'Максимальное потребление мощности, МВт',
            'modified_by': 'Пользователь, последним изменивший запись',
            'note': 'Примечание',
            'peak_datetime_msk': 'Дата и время максимума потребления мощности, МВт',
            'updated_at': 'Дата и время последнего изменения записи',
            'year_number': 'Год',
        },
        'gs_pd_energy_zone_demand_params': {
            "_table": 'Параметры нагрузки (demand) для энергозоны (EnergyZone)',
            'avg_daily_air_temp_c': 'Средняя дневная температура воздуха, °C',
            'combined_on_ees': 'Совмещенный максимум на ЕЭС, МВт',
            'created_at': 'Дата и время создания записи',
            'created_by': 'Пользователь, создавший запись',
            'database_version_id': 'Версия базы данных (FK -> gs_sys.gs_database_versions)',
            'id': 'Уникальный идентификатор записи',
            'id_energy_zone': 'Энергозона (FK -> gs_sys.gs_sys_energy_zones)',
            'is_historical_maximum': 'Признак исторического максимума (true — без года)',
            'max_power_consumption_mw': 'Максимальное потребление мощности, МВт',
            'modified_by': 'Пользователь, последним изменивший запись',
            'note': 'Примечание',
            'peak_datetime_msk': 'Дата и время максимума потребления мощности, МВт',
            'updated_at': 'Дата и время последнего изменения записи',
            'year_number': 'Год',
        },
        'gs_pd_federal_district_demand_params': {
            "_table": 'Параметры нагрузки (demand) для федерального округа (FederalDistrict)',
            'avg_daily_air_temp_c': 'Средняя дневная температура воздуха, °C',
            'combined_on_cz': 'Совмещенный максимум на ЦЗ России, МВт',
            'created_at': 'Дата и время создания записи',
            'created_by': 'Пользователь, создавший запись',
            'database_version_id': 'Версия базы данных (FK -> gs_sys.gs_database_versions)',
            'id': 'Уникальный идентификатор записи',
            'id_federal_district': 'Федеральный округ (FK -> gs_sys.gs_sys_federal_districts)',
            'is_historical_maximum': 'Признак исторического максимума (true — без года)',
            'max_power_consumption_mw': 'Максимальное потребление мощности, МВт',
            'modified_by': 'Пользователь, последним изменивший запись',
            'note': 'Примечание',
            'peak_datetime_msk': 'Дата и время максимума потребления мощности, МВт',
            'updated_at': 'Дата и время последнего изменения записи',
            'year_number': 'Год',
        },
        'gs_pd_regional_district_demand_params': {
            "_table": 'Параметры нагрузки (demand) для субъекта РФ (RegionalDistrict)',
            'avg_daily_air_temp_c': 'Средняя дневная температура воздуха, °C',
            'combined_on_cz': 'Совмещенный максимум на централизованную зону, МВт',
            'combined_on_ees': 'Совмещенный максимум на ЕЭС, МВт',
            'combined_on_es': 'Совмещенный максимум на РЭС, МВт',
            'combined_on_fo': 'Совмещенный максимум на ФО, МВт',
            'combined_on_oes': 'Совмещенный максимум на ОЭС, МВт',
            'created_at': 'Дата и время создания записи',
            'created_by': 'Пользователь, создавший запись',
            'database_version_id': 'Версия базы данных (FK -> gs_sys.gs_database_versions)',
            'id': 'Уникальный идентификатор записи',
            'id_regional_district': 'Субъект РФ (FK -> gs_sys.gs_sys_regional_districts)',
            'is_historical_maximum': 'Признак исторического максимума (true — без года)',
            'max_power_consumption_mw': 'Максимальное потребление мощности, МВт',
            'modified_by': 'Пользователь, последним изменивший запись',
            'note': 'Примечание',
            'peak_datetime_msk': 'Дата и время максимума потребления мощности, МВт',
            'updated_at': 'Дата и время последнего изменения записи',
            'year_number': 'Год',
        },
        'gs_pd_regional_energy_system_demand_params': {
            "_table": 'Параметры нагрузки (demand) для региональной энергосистемы',
            'avg_daily_air_temp_c': 'Средняя дневная температура воздуха, °C',
            'coeff_k_combined_on_ees': 'Коэффициент k для показателя «Совмещённый на ЕЭС, МВт»',
            'coeff_k_combined_on_oes': 'Коэффициент k для показателя «Совмещённый на ОЭС, МВт»',
            'combined_on_cz': 'Совмещенный максимум на ЦЗ России, МВт',
            'combined_on_ees': 'Совмещенный максимум на ЕЭС, МВт',
            'combined_on_ez': 'Совмещенный максимум на энергозону, МВт',
            'combined_on_fo': 'Совмещенный максимум на ФО, МВт',
            'combined_on_oes': 'Совмещенный максимум на ОЭС, МВт',
            'created_at': 'Дата и время создания записи',
            'created_by': 'Пользователь, создавший запись',
            'database_version_id': 'Версия базы данных (FK -> gs_sys.gs_database_versions)',
            'id': 'Уникальный идентификатор записи',
            'id_regional_energy_system': 'Региональная энергосистема (FK -> gs_sys.gs_sys_regional_energy_systems)',
            'is_historical_maximum': 'Признак исторического максимума (true — без года)',
            'max_power_consumption_mw': 'Максимальное потребление мощности, МВт',
            'modified_by': 'Пользователь, последним изменивший запись',
            'note': 'Примечание',
            'peak_datetime_msk': 'Дата и время максимума потребления мощности, МВт',
            'updated_at': 'Дата и время последнего изменения записи',
            'year_number': 'Год',
        },
        'gs_pd_russia_federation_demand_params': {
            "_table": 'Параметры нагрузки (demand) для Российской Федерации в целом',
            'avg_daily_air_temp_c': 'Средняя дневная температура воздуха, °C',
            'created_at': 'Дата и время создания записи',
            'created_by': 'Пользователь, создавший запись',
            'database_version_id': 'Версия базы данных (FK -> gs_sys.gs_database_versions)',
            'id': 'Уникальный идентификатор записи',
            'is_historical_maximum': 'Признак исторического максимума (true — без года)',
            'max_power_consumption_mw': 'Максимальное потребление мощности, МВт',
            'modified_by': 'Пользователь, последним изменивший запись',
            'note': 'Примечание',
            'peak_datetime_msk': 'Дата и время максимума потребления мощности, МВт',
            'perimeter_variant_code': 'Код варианта периметра (NULL — без варианта)',
            'updated_at': 'Дата и время последнего изменения записи',
            'year_number': 'Год',
        },
        'gs_pd_summary_formula_texts': {
            "_table": 'Переопределения текстов формул (подсказки «i») для сводок модуля «Нагрузки»',
            'created_at': 'Дата и время создания записи',
            'created_by': 'Пользователь, создавший запись',
            'formula_key': 'Ключ формулы',
            'formula_text': 'Текст формулы',
            'id': 'Уникальный идентификатор записи',
            'modified_by': 'Пользователь, последним изменивший запись',
            'updated_at': 'Дата и время последнего изменения записи',
        },
        'gs_pd_synchronous_area_demand_params': {
            "_table": 'Параметры нагрузки (demand) для синхронной зоны (SynchronousArea)',
            'avg_daily_air_temp_c': 'Средняя дневная температура воздуха, °C',
            'combined_on_ees': 'Совмещенный максимум на ЕЭС, МВт',
            'created_at': 'Дата и время создания записи',
            'created_by': 'Пользователь, создавший запись',
            'database_version_id': 'Версия базы данных (FK -> gs_sys.gs_database_versions)',
            'id': 'Уникальный идентификатор записи',
            'id_synchronous_area': 'Синхронная зона (FK -> gs_sys.gs_sys_synchronous_areas)',
            'is_historical_maximum': 'Признак исторического максимума (true — без года)',
            'max_power_consumption_mw': 'Максимальное потребление мощности, МВт',
            'modified_by': 'Пользователь, последним изменивший запись',
            'note': 'Примечание',
            'peak_datetime_msk': 'Дата и время максимума потребления мощности, МВт',
            'updated_at': 'Дата и время последнего изменения записи',
            'year_number': 'Год',
        },
        'gs_pd_union_energy_system_demand_params': {
            "_table": 'Параметры нагрузки (demand) для объединённой энергосистемы (UnionEnergySystem)',
            'avg_daily_air_temp_c': 'Средняя дневная температура воздуха, °C',
            'calculated_combined_on_ees_mw': 'Расчетный совмещенный на ЕЭС, МВт',
            'calculated_max_power_mw': 'Расчетный максимум ОЭС, МВт',
            'coeff_k_calculated_combined_on_ees_mw': 'Коэффициент k для показателя «Расчетный совмещенный на ЕЭС, МВт»',
            'coeff_k_calculated_max_power_mw': 'Коэффициент k для показателя «Расчетный максимум ОЭС, МВт»',
            'coeff_k_combined_on_ees': 'Коэффициент k для показателя «Совмещённый на ЕЭС, МВт»',
            'combined_on_ees': 'Совмещенный максимум на ЕЭС, МВт',
            'created_at': 'Дата и время создания записи',
            'created_by': 'Пользователь, создавший запись',
            'database_version_id': 'Версия базы данных (FK -> gs_sys.gs_database_versions)',
            'id': 'Уникальный идентификатор записи',
            'id_union_energy_system': 'Объединённая энергосистема (FK -> gs_sys.gs_sys_union_energy_systems)',
            'is_historical_maximum': 'Признак исторического максимума (true — без года)',
            'max_power_consumption_mw': 'Максимальное потребление мощности, МВт',
            'modified_by': 'Пользователь, последним изменивший запись',
            'note': 'Примечание',
            'peak_datetime_msk': 'Дата и время максимума потребления мощности, МВт',
            'perimeter_variant_code': 'Код варианта периметра (NULL — без варианта)',
            'updated_at': 'Дата и время последнего изменения записи',
            'year_number': 'Год',
        },
    },
    'gs_fue': {
        'gs_fue_distribution_coefficient_summaries': {
            "_table": 'Агрегированный результат этапа «Коэфф» по параметру распределения',
            'base_year': 'Базовый год (номер)',
            'be': 'Сумма выработки электроэнергии (E), базовый год',
            'betp': 'Сумма теплофикационной выработки (Этц), базовый год',
            'bh': 'Удельные часы (Н), базовый год',
            'bnust': 'Сумма установленной мощности (N_уст), базовый год, МВт',
            'bptp': 'Доля тепла в электроэнергии, %, базовый год',
            'bq': 'Сумма отпуска ТЭ, тыс.Гкал (Q), базовый год',
            'bqotr': 'Сумма тепла на отработку (Q_отр), базовый год',
            'cetp': 'Сумма теплофикационной выработки (Этц), расчётный год',
            'ch': 'Удельные часы (Н), расчётный год',
            'cnust': 'Сумма установленной мощности (N_уст), расчётный год, МВт',
            'cnustn': 'Сумма мощности новых агрегатов (N_нов), расчётный год, МВт',
            'cnustngt': 'Мощность нового газотурбинного оборудования, расчётный год, МВт',
            'cnustnpg': 'Мощность нового парогазового оборудования, расчётный год, МВт',
            'cnustnps': 'Мощность нового паросилового оборудования, расчётный год, МВт',
            'cptp': 'Доля тепла в электроэнергии, %, расчётный год',
            'cq': 'Сумма отпуска ТЭ, тыс.Гкал (Q), расчётный год',
            'cqotr': 'Сумма тепла на отработку (Q_отр), расчётный год',
            'database_version_id': 'Версия базы данных (FK -> gs_sys.gs_database_versions)',
            'distribution_parameter_id': 'Параметр распределения',
            'doptim': 'Коэффициент допустимого отклонения',
            'e_target': 'Целевая выработка электроэнергии (E_целевое)',
            'hd': 'Удельные часы на действующую часть парка (hd)',
            'hngt': 'ЧЧИУМ нового газотурбинного оборудования',
            'hnpg': 'ЧЧИУМ нового парогазового оборудования',
            'hnps': 'ЧЧИУМ нового паросилового оборудования',
            'id': 'Уникальный идентификатор записи',
            'k': 'Коэффициент загрузки',
            'kmin': 'Нижняя граница коэффициента загрузки (k−)',
            'kn': 'Коэффициент загрузки нового оборудования (расчётный)',
            'kngt': 'Коэффициент загрузки нового газотурбинного оборудования (расчётный)',
            'knpg': 'Коэффициент загрузки нового парогазового оборудования (расчётный)',
            'knps': 'Коэффициент загрузки нового паросилового оборудования (расчётный)',
            'kplus': 'Верхняя граница коэффициента загрузки (k+)',
            'lim': 'Наличие ограничений по выработке для РЭС',
            'note': 'Примечание',
            'pe': 'Отношение выработки E (расчётный/базовый год)',
            'ph': 'Удельные часы на действующую часть парка (PH)',
            'ph1': 'Вспомогательный показатель удельных часов (PH1)',
            'potr': 'Отношение тепла на отработку (расчётный/базовый год)',
            'pq': 'Отношение отпуска ТЭ, тыс.Гкал (Q) (расчётный/базовый год)',
            'year_number': 'Номер года',
        },
        'gs_fue_distribution_parameters': {
            "_table": 'Параметры распределения (аналог таблицы «Параметры-распределения» из Access)',
            'bkl': 'Вспомогательный номер территоррии для распределения выработки по станциям ОЭС',
            'created_at': 'Дата и время создания записи',
            'database_version_id': 'Версия базы данных (FK -> gs_sys.gs_database_versions)',
            'dopname': 'Наименование таблицы с детализацией видов топлива',
            'doptim': 'Коэффициент допустимого отклонения',
            'e': 'Выработка ТЭС',
            'filter_text': 'Текст фильтра / можно потому удалить',
            'hngt': 'ЧЧИУМ нового газотурбинного оборудования',
            'hnpg': 'ЧЧИУМ нового парогазового оборудования',
            'hnps': 'ЧЧИУМ нового паросилового оборудования',
            'id': 'Уникальный идентификатор записи',
            'id_base_year': 'Базовый год',
            'id_union_energy_system': 'Объединенная энергосистема',
            'id_year': 'Расчитываемый год (id_year)',
            'k': 'Коэффициент загрузки',
            'kmin': 'Нижняя граница коэффициента загрузки (k−)',
            'kn': 'Коэффициент загрузки нового оборудования (расчётный)',
            'kngt': 'Коэффициент загрузки нового газотурбинного оборудования (расчётный)',
            'knpg': 'Коэффициент загрузки нового парогазового оборудования (расчётный)',
            'knps': 'Коэффициент загрузки нового паросилового оборудования (расчётный)',
            'kplus': 'Верхняя граница коэффициента загрузки (k+)',
            'lim': 'Наличие ограничений по выработке для РЭС',
            'numb': 'Порядковый номер',
            'toplname': 'Название таблицы со структурой топливного баланса групп оборудования',
            'uname': 'Наименование таблицы с удельными технико-экономическими показателями работы групп оборудования',
            'updated_at': 'Дата и время последнего изменения записи',
            'wname': 'Наименование таблицы с обобщенными показателями по станциям',
        },
        'gs_fue_equipment_group_coefficient_results': {
            "_table": 'Снимок результатов этапа «Коэфф» для группы оборудования и параметра распределения',
            'coeff_base': 'Базовый коэффициент загрузки (этап «Коэфф»)',
            'coeff_effective': 'Эффективный коэффициент загрузки (этап «Коэфф»)',
            'coeff_max': 'Верхняя граница коэффициента загрузки (этап «Коэфф»)',
            'coeff_min': 'Нижняя граница коэффициента загрузки (этап «Коэфф»)',
            'database_version_id': 'Версия базы данных (FK -> gs_sys.gs_database_versions)',
            'distribution_parameter_id': 'Параметр распределения (FK -> gs_fue.gs_fue_distribution_parameters)',
            'doptim': 'Коэффициент допустимого отклонения',
            'equipment_group_id': 'Группа оборудования (FK -> gs_fue.gs_fue_equipment_groups)',
            'hngt': 'ЧЧИУМ нового газотурбинного оборудования',
            'hnpg': 'ЧЧИУМ нового парогазового оборудования',
            'hnps': 'ЧЧИУМ нового паросилового оборудования',
            'id': 'Уникальный идентификатор записи',
            'k': 'Входные коэффициенты параметра распределения (копия/снимок)',
            'kmin': 'Нижняя граница коэффициента загрузки (k−)',
            'kn': 'Коэффициент загрузки нового оборудования (расчётный)',
            'kngt': 'Коэффициент загрузки нового газотурбинного оборудования (расчётный)',
            'knpg': 'Коэффициент загрузки нового парогазового оборудования (расчётный)',
            'knps': 'Коэффициент загрузки нового паросилового оборудования (расчётный)',
            'kplus': 'Верхняя граница коэффициента загрузки (k+)',
            'lim': 'Наличие ограничений по выработке для РЭС',
            'note': 'Примечание',
            'year_number': 'Номер года',
        },
        'gs_fue_equipment_group_extra_fuel_param': {
            "_table": 'EquipmentGroupExtraFuelParam model — дополнительные топливные параметры групп оборудования',
            'anad': 'уголь анадырский',
            'azey': 'уголь азейский',
            'berez': 'уголь березовский',
            'bering': 'уголь беринговский',
            'bikin': 'уголь бикинский (лучегорский)',
            'chel': 'уголь челябинский',
            'cher': 'уголь черемховский',
            'created_at': 'Дата и время создания записи',
            'database_version_id': 'Версия базы данных (FK -> gs_sys.gs_database_versions)',
            'disel': 'топливо дизельное',
            'domen_g': 'газ искусственный доменный',
            'ekib': 'уголь экибастузский',
            'equipment_group_id': 'Группа оборудования (FK -> gs_fue.gs_fue_equipment_groups)',
            'erk': 'уголь ерковецкий',
            'gaz_prir': 'газ естественный природный',
            'gazpp': 'газ естественный попутный',
            'gtt': 'Газотурбинное топливо',
            'gusin': 'уголь гусиноозерский',
            'hankai': 'уголь ханкайский',
            'har': 'уголь харанорский',
            'ibor': 'уголь бородинский',
            'id': 'Уникальный идентификатор записи',
            'inoe': 'Иное топливо',
            'intin': 'уголь интинский',
            'irbei': 'уголь ирбейский',
            'jer': 'уголь жеронский',
            'kansk': 'уголь канский',
            'karab': 'уголь карабульский',
            'karag': 'уголь карагандинский',
            'karajyra': 'уголь разреза Каражыра (Казахстан)',
            'kizel': 'уголь кизеловский',
            'koks_g': 'газ искусственный коксовый',
            'kuzngd': 'уголь кузнецкий марки Г, Д',
            'kuznss': 'уголь кузнецкий марки СС',
            'kuznt': 'уголь кузнецкий марки Т',
            'kuznun': 'уголь кузнецкий прочий',
            'luch': 'Лучегорское (уголь)',
            'maikub': 'уголь майкубенский',
            'maztop': 'мазут топочный',
            'mug': 'уголь мугунский',
            'name': 'Наименование',
            'nazar': 'уголь назаровский',
            'neru': 'уголь нерюнгринский',
            'nft_proch': 'нефтетопливо прочее',
            'numb1': 'Номер',
            'numb1120': 'Код группы оборудования',
            'ogodj': 'уголь огоджинский',
            'okino': 'уголь разреза Окино-Ключевской',
            'per': 'уголь переясловский',
            'prochgaz': 'газ НПЗ',
            'pyak': 'уголь якутский прочий',
            'rai': 'уголь райчихинский',
            'razdol': 'уголь раздольненский',
            'sosv': 'Доп. поля по аналогии с Access (детализация углей)',
            'sver': 'уголь свердловский',
            'svo': 'уголь свободненский',
            'szh_gaz': 'газ сжиженный',
            'tal': 'уголь таловский',
            'tarbag': 'уголь тарбагатайский',
            'tataur': 'уголь татауровский',
            'teniz': 'уголь тениз-коржункольский',
            'tugn': 'уголь тугнуйский',
            'tvproch': 'прочие виды твердого топлива',
            'updated_at': 'Дата и время последнего изменения записи',
            'urt': 'уголь уртуйский',
            'vork': 'уголь воркутинский',
            'year_number': 'Номер года',
            'zab_kam': 'уголь забайкальский каменный',
            'zyryan': 'уголь зырянский',
        },
        'gs_fue_equipment_group_fuel_formula': {
            "_table": 'EquipmentGroupFuelFormula — формулы топлива для группы оборудования',
            'created_at': 'Дата и время создания записи',
            'database_version_id': 'Версия базы данных (FK -> gs_sys.gs_database_versions)',
            'equipment_group_id': 'Группа оборудования (FK -> gs_fue.gs_fue_equipment_groups)',
            'formtxt': 'Текст формулы топлива',
            'id': 'Уникальный идентификатор записи',
            'name': 'Наименование',
            'numb1': 'Номер',
            'numb1120': 'Код группы оборудования',
            'updated_at': 'Дата и время последнего изменения записи',
            'variant_number': 'Аналог поля v из Access',
            'year_number': 'Номер года',
        },
        'gs_fue_equipment_group_fuel_param': {
            "_table": 'EquipmentGroupFuelParam model — топливные параметры для группы оборудования',
            'amur': 'уголь амурский',
            'arkt': 'уголь арктический',
            'b': 'Расход топлива, всего',
            'bashk': 'уголь башкирский (южно-уральский)',
            'be': 'be — FK -> BusinessUnitExternalMapping.external_id',
            'bur': 'уголь бурятский',
            'chit': 'уголь забайкальский',
            'chukot': 'уголь чукотский',
            'created_at': 'timestamps (UTC, server-side)',
            'database_version_id': 'Поле для связи с версией БД',
            'dep': 'dep — FK -> DepartmentExternalMapping.external_id',
            'don': 'уголь донецкий',
            'e': 'Электроэнергия в тыс.кВтч: Выр',
            'ees': 'Энергосистема (ees)',
            'eotp': 'Отпуск ЭЭ, тыс.кВтч',
            'equipment_group_id': 'Группа оборудования (FK -> gs_fue.gs_fue_equipment_groups)',
            'er': 'er — FK -> EconomicRegionExternalMapping.external_id',
            'eurt': 'Уд.расх',
            'eust': 'Расх топ ээ',
            'ewtp': 'Этц',
            'gaz': 'Расх по типам топлива',
            'gk': 'gk — FK -> GenCompanyExternalMapping.external_id',
            'hak': 'уголь хакасский',
            'id': 'Уникальный идентификатор записи',
            'irkut': 'уголь иркутский',
            'isk_gaz': 'газ искусственный (прочие виды)',
            'kamch': 'уголь камчатский',
            'kan': 'уголь канско-ачинский',
            'kazah': 'угли Казахстана',
            'kuzn': 'уголь кузнецкий',
            'mag': 'уголь магаданский',
            'mazut': 'Мазут',
            'name': 'Наименование группы оборудования',
            'nr': 'Ррасп',
            'nt': 'Тепл. мощн. отборов',
            'nt_sum': 'Сумма тепловых мощностей, Гкал/ч',
            'numb1': 'Номер',
            'numb1120': 'Код группы оборудования',
            'nust': 'Мощность: Руст',
            'obl': 'obl — FK -> TerritoriesEnergyExternalMapping.external_id',
            'obor': 'obor — FK -> EquipmentGroupExternalMapping.code',
            'oes': 'oes — FK -> UnionEnergySystemExternalMapping.external_id',
            'pech': 'уголь печорский',
            'podm': 'уголь подмосковный',
            'prim': 'уголь приморский',
            'proch': 'Прочее',
            'q': 'Отпуск ТЭ, тыс.Гкал',
            'qotr': 'Отраб',
            'sah': 'уголь сахалинский',
            'slan': 'сланцы',
            'sn_t': 'СН, кВтч/⁠Гкал',
            'snk': 'СН, %',
            'torf': 'торф',
            'tung': 'уголь тунгусский',
            'turt': 'Уд.расх',
            'tust': 'Расх топ тэ',
            'tuv': 'уголь тувинский (улуг-хемский)',
            'ugol': 'Уголь',
            'updated_at': 'Дата и время последнего изменения записи',
            'ural': 'уголь уральский',
            'urg': 'уголь ургальский',
            'ushum': 'уголь ушумунский (средне-амурский)',
            'ved': 'Ведомство (ved)',
            'yakut': 'уголь якутский',
            'year_number': 'Ссылка на год (number из gs_sys_years). Без FK: gs_sys_years.number не уникален (дубли по версиям).',
            'вед': 'Ведомство (вед)',
        },
        'gs_fue_equipment_group_sets': {
            "_table": 'EquipmentGroupSet model (link между итоговой группой и связкой станция+тип)',
            'created_at': 'Дата и время создания записи',
            'equipment_group_id': 'Группа оборудования (FK -> gs_fue.gs_fue_equipment_groups)',
            'equipment_group_set_station_id': 'Связка станция+тип группы (FK -> gs_fue.gs_fue_equipment_group_type_stations)',
            'id': 'Уникальный идентификатор записи',
            'updated_at': 'Дата и время последнего изменения записи',
        },
        'gs_fue_equipment_group_specific_fuel_consumption': {
            "_table": 'EquipmentGroupSpecificFuelConsumption model — удельные показатели групп оборудования',
            'bk': 'УРУТ на отпуск ЭЭ в конденсационном режиме, г у.т./кВтч',
            'bk_calc': 'УРУТ на отпуск ЭЭ в конденсационном режиме, г у.т./кВтч',
            'btp': 'УРУТ на отпуск ЭЭ в теплофикационном режиме, г у.т./кВтч',
            'btp_calc': 'УРУТ на отпуск ЭЭ в теплофикационном режиме, г у.т./кВтч',
            'created_at': 'Дата и время создания записи',
            'database_version_id': 'Версия базы данных (FK -> gs_sys.gs_database_versions)',
            'equipment_group_id': 'Группа оборудования (FK -> gs_fue.gs_fue_equipment_groups)',
            'id': 'Уникальный идентификатор записи',
            'k': 'Коэффициент экономии от теплофикации (привязан к году). Numeric для дробных (1.5, 0.7)',
            'name': 'Наименование',
            'numb1120': 'Код группы оборудования',
            'snk': 'Собственные нужды на выработку электроэнергии',
            'snk_calc': 'Собственные нужды на выработку электроэнергии',
            'sntp': 'Коэффициент отпуска ЭЭ в теплофикационном режиме',
            'sntp_calc': 'Коэффициент отпуска ЭЭ в теплофикационном режиме',
            'updated_at': 'Дата и время последнего изменения записи',
            'y': 'Удельная выработка ЭЭ на тепловом потреблении, кВтч/⁠Гкал',
            'y_calc': 'Удельная выработка ЭЭ на тепловом потреблении, кВтч/⁠Гкал',
            'year_number': 'Номер года',
        },
        'gs_fue_equipment_group_specific_fuel_cost': {
            "_table": 'EquipmentGroupSpecificFuelCost model — стоимость для групп оборудования',
            'amur': 'уголь амурский',
            'anad': 'уголь анадырский',
            'azey': 'уголь азейский',
            'bashk': 'уголь башкирский (южно-уральский)',
            'berez': 'уголь березовский',
            'bering': 'уголь беринговский',
            'bikin': 'уголь бикинский (лучегорский)',
            'bur': 'уголь бурятский',
            'chel': 'уголь челябинский',
            'cher': 'уголь черемховский',
            'chit': 'уголь забайкальский',
            'chukot': 'уголь чукотский',
            'created_at': 'Дата и время создания записи',
            'database_version_id': 'Версия базы данных (FK -> gs_sys.gs_database_versions)',
            'dep': 'Код департамента (внешний идентификатор)',
            'disel': 'топливо дизельное',
            'domen_g': 'газ искусственный доменный',
            'don': 'уголь донецкий',
            'ekib': 'уголь экибастузский',
            'equipment_group_id': 'Группа оборудования (FK -> gs_fue.gs_fue_equipment_groups)',
            'er': 'Код экономического района (внешний идентификатор)',
            'erk': 'уголь ерковецкий',
            'gaz': 'Топливные поля (Numeric для стоимостей)',
            'gaz_prir': 'газ естественный природный',
            'gazpp': 'газ естественный попутный',
            'gtt': 'Газотурбинное топливо',
            'gusin': 'уголь гусиноозерский',
            'hak': 'уголь хакасский',
            'hankai': 'уголь ханкайский',
            'har': 'уголь харанорский',
            'ibor': 'уголь бородинский',
            'id': 'Уникальный идентификатор записи',
            'inoe': 'Иное топливо',
            'intin': 'уголь интинский',
            'irbei': 'уголь ирбейский',
            'irkut': 'уголь иркутский',
            'isk_gaz': 'газ искусственный (прочие виды)',
            'jer': 'уголь жеронский',
            'kamch': 'уголь камчатский',
            'kan': 'уголь канско-ачинский',
            'kansk': 'уголь канский',
            'karab': 'уголь карабульский',
            'karag': 'уголь карагандинский',
            'karajyra': 'уголь разреза Каражыра (Казахстан)',
            'kazah': 'угли Казахстана',
            'kizel': 'уголь кизеловский',
            'koks_g': 'газ искусственный коксовый',
            'kuzn': 'уголь кузнецкий',
            'kuzngd': 'уголь кузнецкий марки Г, Д',
            'kuznss': 'уголь кузнецкий марки СС',
            'kuznt': 'уголь кузнецкий марки Т',
            'kuznun': 'уголь кузнецкий прочий',
            'mag': 'уголь магаданский',
            'maikub': 'уголь майкубенский',
            'maztop': 'мазут топочный',
            'mazut': 'Мазут',
            'mug': 'уголь мугунский',
            'name': 'Наименование',
            'nazar': 'уголь назаровский',
            'neru': 'уголь нерюнгринский',
            'nft_proch': 'нефтетопливо прочее',
            'numb1': 'Номер',
            'numb1120': 'Код группы оборудования',
            'obl': 'Код субъекта РФ (внешний идентификатор)',
            'oes': 'Код ОЭС (внешний идентификатор)',
            'ogodj': 'уголь огоджинский',
            'okino': 'уголь разреза Окино-Ключевской',
            'pech': 'уголь печорский',
            'per': 'уголь переясловский',
            'podm': 'уголь подмосковный',
            'prim': 'уголь приморский',
            'proch': 'Прочее',
            'prochgaz': 'газ НПЗ',
            'pyak': 'уголь якутский прочий',
            'rai': 'уголь райчихинский',
            'razdol': 'уголь раздольненский',
            'sah': 'уголь сахалинский',
            'sver': 'уголь свердловский',
            'svo': 'уголь свободненский',
            'szh_gaz': 'газ сжиженный',
            'tarbag': 'уголь тарбагатайский',
            'tataur': 'уголь татауровский',
            'teniz': 'уголь тениз-коржункольский',
            'torf': 'торф',
            'tugn': 'уголь тугнуйский',
            'tung': 'уголь тунгусский',
            'tuv': 'уголь тувинский (улуг-хемский)',
            'tvproch': 'прочие виды твердого топлива',
            'ugol': 'Уголь',
            'updated_at': 'Дата и время последнего изменения записи',
            'ural': 'уголь уральский',
            'urg': 'уголь ургальский',
            'urt': 'уголь уртуйский',
            'ushum': 'уголь ушумунский (средне-амурский)',
            'ved': 'Служебные поля',
            'vork': 'уголь воркутинский',
            'yakut': 'уголь якутский',
            'year_number': 'Номер года',
            'zab_kam': 'уголь забайкальский каменный',
            'zyryan': 'уголь зырянский',
        },
        'gs_fue_equipment_group_specific_fuel_price': {
            "_table": 'EquipmentGroupSpecificFuelPrice model — цена для групп оборудования',
            'amur_c': 'Цена, уголь амурский',
            'anad_c': 'Цена, уголь анадырский',
            'azey_c': 'Цена, уголь азейский',
            'bashk_c': 'Цена, уголь башкирский (южно-уральский)',
            'berez_c': 'Цена, уголь березовский',
            'bering_c': 'Цена, уголь беринговский',
            'bikin_c': 'Цена, уголь бикинский (лучегорский)',
            'bur_c': 'Цена, уголь бурятский',
            'chel_c': 'Цена, уголь челябинский',
            'cher_c': 'Цена, уголь черемховский',
            'chit_c': 'Цена, уголь забайкальский',
            'chukot_c': 'Цена, уголь чукотский',
            'created_at': 'Дата и время создания записи',
            'database_version_id': 'Версия базы данных (FK -> gs_sys.gs_database_versions)',
            'disel_c': 'Цена, топливо дизельное',
            'domen_g_c': 'Цена, газ искусственный доменный',
            'don_c': 'Цена, уголь донецкий',
            'ekib_c': 'Цена, уголь экибастузский',
            'equipment_group_id': 'Группа оборудования (FK -> gs_fue.gs_fue_equipment_groups)',
            'erk_c': 'Цена, уголь ерковецкий',
            'gaz_c': 'Цена, газ (всего)',
            'gaz_prir_c': 'Цена, газ естественный природный',
            'gazpp_c': 'Цена, газ естественный попутный',
            'group': 'Группа цен (sost/group из Access)',
            'gtt_c': 'Цена, Газотурбинное топливо',
            'gusin_c': 'Цена, уголь гусиноозерский',
            'hak_c': 'Цена, уголь хакасский',
            'hankai_c': 'Цена, уголь ханкайский',
            'har_c': 'Цена, уголь харанорский',
            'ibor_c': 'Цена, уголь бородинский',
            'id': 'Уникальный идентификатор записи',
            'inoe_c': 'Цена, Иное топливо',
            'intin_c': 'Цена, уголь интинский',
            'irbei_c': 'Цена, уголь ирбейский',
            'irkut_c': 'Цена, уголь иркутский',
            'isk_gaz_c': 'Цена, газ искусственный (прочие виды)',
            'jer_c': 'Цена, уголь жеронский',
            'kamch_c': 'Цена, уголь камчатский',
            'kan_c': 'Цена, уголь канско-ачинский',
            'kansk_c': 'Цена, уголь канский',
            'karab_c': 'Цена, уголь карабульский',
            'karag_c': 'Цена, уголь карагандинский',
            'karajyra_c': 'Цена, уголь разреза Каражыра (Казахстан)',
            'kazah_c': 'Цена, угли Казахстана',
            'kizel_c': 'Цена, уголь кизеловский',
            'koks_g_c': 'Цена, газ искусственный коксовый',
            'kuzn_c': 'Цена, уголь кузнецкий',
            'kuzngd_c': 'Цена, уголь кузнецкий марки Г, Д',
            'kuznss_c': 'Цена, уголь кузнецкий марки СС',
            'kuznt_c': 'Цена, уголь кузнецкий марки Т',
            'kuznun_c': 'Цена, уголь кузнецкий прочий',
            'mag_c': 'Цена, уголь магаданский',
            'maikub_c': 'Цена, уголь майкубенский',
            'maztop_c': 'Цена, мазут топочный',
            'mazut_c': 'Цена, Мазут',
            'mug_c': 'Цена, уголь мугунский',
            'name': 'Наименование',
            'nazar_c': 'Цена, уголь назаровский',
            'neru_c': 'Цена, уголь нерюнгринский',
            'nft_proch_c': 'Цена, нефтетопливо прочее',
            'numb1120': 'Код группы оборудования',
            'obl': 'Код субъекта РФ (внешний идентификатор)',
            'ogodj_c': 'Цена, уголь огоджинский',
            'okino_c': 'Цена, уголь разреза Окино-Ключевской',
            'pech_c': 'Цена, уголь печорский',
            'per_c': 'Цена, уголь переясловский',
            'podm_c': 'Цена, уголь подмосковный',
            'prim_c': 'Цена, уголь приморский',
            'proch_c': 'Цена, Прочее',
            'prochgaz_c': 'Цена, газ НПЗ',
            'pyak_c': 'Цена, уголь якутский прочий',
            'rai_c': 'Цена, уголь райчихинский',
            'razdol_c': 'Цена, уголь раздольненский',
            'sah_c': 'Цена, уголь сахалинский',
            'sost': 'Состав/группа цен (sost из Access)',
            'sver_c': 'Цена, уголь свердловский',
            'svo_c': 'Цена, уголь свободненский',
            'szh_gaz_c': 'Цена, газ сжиженный',
            'tarbag_c': 'Цена, уголь тарбагатайский',
            'tataur_c': 'Цена, уголь татауровский',
            'teniz_c': 'Цена, уголь тениз-коржункольский',
            'torf_c': 'Цена, торф',
            'tugn_c': 'Цена, уголь тугнуйский',
            'tung_c': 'Цена, уголь тунгусский',
            'tuv_c': 'Цена, уголь тувинский (улуг-хемский)',
            'tvproch_c': 'Цена, прочие виды твердого топлива',
            'updated_at': 'Дата и время последнего изменения записи',
            'ural_c': 'Цена, уголь уральский',
            'urg_c': 'Цена, уголь ургальский',
            'urt_c': 'Цена, уголь уртуйский',
            'ushum_c': 'Цена, уголь ушумунский (средне-амурский)',
            'vork_c': 'Цена, уголь воркутинский',
            'yakut_c': 'Цена, уголь якутский',
            'year_number': 'Номер года',
            'zab_kam_c': 'Цена, уголь забайкальский каменный',
            'zyryan_c': 'Цена, уголь зырянский',
        },
        'gs_fue_equipment_group_type_stations': {
            "_table": 'EquipmentGroupSetStation model (привязка типа группы оборудования к электростанции)',
            'created_at': 'Дата и время создания записи',
            'database_version_id': 'Поле для связи с версией БД',
            'equipment_group_type_id': 'Тип группы оборудования (FK -> gs_sys.gs_sys_equipment_groups)',
            'id': 'Уникальный идентификатор записи',
            'station_id': 'Электростанция (FK -> gs_gen.gs_gen_stations)',
            'updated_at': 'Дата и время последнего изменения записи',
        },
        'gs_fue_equipment_groups': {
            "_table": 'EquipmentGroup model (итоговая группа оборудования)',
            'addr': 'Адрес',
            'be': 'Тип генерирующей компании (FK -> BusinessUnitExternalMapping.external_id)',
            'codegor': 'cast для совместимости, если в БД один из столбцов VARCHAR',
            'comp': 'Признак электростанции, разбитой на группы оборудования',
            'created_at': 'Дата и время создания записи',
            'd': 'Признак действующей электростанции',
            'database_version_id': 'Поле для связи с версией БД',
            'dep': 'Код департамента (FK -> DepartmentExternalMapping)',
            'er': 'Код экономического района (FK -> EconomicRegionExternalMapping.external_id)',
            'external_code': 'Внешний код (UUID)',
            'fo': 'Код федерального округа (FK -> FederalDistrictExternalMapping.external_id)',
            'forem': 'Признак ФОРЭМ',
            'gk': 'Код генерирующей компании (FK -> GenCompanyExternalMapping.external_id)',
            'gkf': 'Код филиала генерирующей компании (связь по external_id -> GenCompanyBranchExternalMapping, без FK в БД)',
            'id': 'Уникальный идентификатор записи',
            'id_department': 'Департамент (FK -> gs_sys.gs_sys_departments)',
            'main': 'Код группы оборудования, в которую входит данная группа',
            'n1': 'Мощность блока в группе оборудования_вариант 1',
            'n2': 'Мощность блока в группе оборудования_вариант 2',
            'name': 'Пользовательский идентификатор/название группы',
            'name_ext': 'Название (БД Топливо)',
            'niv': 'Признак группы оборудования',
            'note': 'Примечание',
            'numb': 'Код группы оборудования',
            'obl': 'Код субъекта РФ (FK -> TerritoriesEnergyExternalMapping.external_id)',
            'oes': 'Код ОЭС (FK -> UnionEnergySystemExternalMapping.external_id)',
            'ordnumb': 'Порядковый номер электростанции',
            'p1': 'Давление пара перед турбиной_вариант 1',
            'p2': 'Давление пара перед турбиной_вариант 2',
            'r': 'Признак расширяемой электростанции',
            'regional_district_id': 'Субъект РФ (FK -> gs_sys.gs_sys_regional_districts)',
            'regional_energy_system_id': 'Региональная энергосистема (FK -> gs_sys.gs_sys_regional_energy_systems)',
            'tm': 'Название типов турбин, которое соответствует коду (необязательное)',
            'updated_at': 'Дата и время последнего изменения записи',
            'vedomstvo': 'Ведомство',
        },
        'gs_fue_machine_fuel_param': {
            "_table": 'MachineFuelParam model — привязка топливных данных агрегата к Machine',
            'created_at': 'timestamps (UTC, server-side)',
            'database_version_id': 'Поле для связи с версией БД',
            'dem': 'Год демонтажа',
            'equipment_group_id': 'Группа оборудования (FK -> gs_fue.gs_fue_equipment_groups)',
            'grcode': 'Код группы оборудования (без связи с моделью)',
            'id': 'Уникальный идентификатор записи',
            'machine_id': 'Энергоблок (FK -> gs_gen.gs_gen_machines)',
            'note': 'Примечание',
            'nt': 'Тепловая мощность отборов, Гкал/ч',
            'numb': 'Порядковый номер',
            'numb1120': 'Код группы оборудования',
            'opesname': 'Тип (марка) оборудования',
            'stname': 'Название электростанции',
            'stnumb': 'Номер агрегата',
            'updated_at': 'Дата и время последнего изменения записи',
            'yearin': 'Год ввода в эксплуатацию',
        },
        'gs_fue_restrictions': {
            "_table": 'Ограничения (аналог таблицы «Ограничения» из Access, см',
            'created_at': 'Дата и время создания записи',
            'database_version_id': 'Версия базы данных (FK -> gs_sys.gs_database_versions)',
            'ecur': 'Текущая выработка (ecur)',
            'ecurdis': 'Текущая выработка с учётом ограничения (ecurdis)',
            'emax': 'Максимальная выработка (emax)',
            'emin': 'Минимальная выработка (emin)',
            'etp': 'Выработка Этц (etp)',
            'h': 'Поле H в Access',
            'hdis': 'H с учётом ограничения (hdis)',
            'id': 'Уникальный идентификатор записи',
            'kcur': 'Текущий коэффициент (kcur)',
            'kobl': 'Коэффициент по субъекту (kobl)',
            'name': 'Наименование',
            'obl': 'Код субъекта РФ (obl)',
            'oes': 'Код ОЭС (oes)',
            'updated_at': 'Дата и время последнего изменения записи',
            'year': 'Год (в Access — double)',
        },
    },
}


def _comment_on_table(conn, schema: str, table: str, comment: str | None) -> None:
    if not column_utils.table_exists(conn, schema, table):
        return
    conn.execute(
        text(f'COMMENT ON TABLE "{schema}"."{table}" IS :comment'),
        {"comment": comment},
    )


def _comment_on_column(
    conn, schema: str, table: str, column: str, comment: str | None
) -> None:
    if not column_utils.table_has_column(conn, schema, table, column):
        return
    conn.execute(
        text(f'COMMENT ON COLUMN "{schema}"."{table}"."{column}" IS :comment'),
        {"comment": comment},
    )


def _apply_comments(
    conn, schema_comments: dict[str, dict[str, dict[str, str]]], clear: bool
) -> None:
    for schema, tables in schema_comments.items():
        for table, comments in tables.items():
            table_comment = None if clear else comments.get("_table")
            _comment_on_table(conn, schema, table, table_comment)
            for column, comment in comments.items():
                if column == "_table":
                    continue
                column_comment = None if clear else comment
                _comment_on_column(conn, schema, table, column, column_comment)


def upgrade():
    conn = op.get_bind()
    _apply_comments(conn, _SCHEMA_COMMENTS, clear=False)


def downgrade():
    conn = op.get_bind()
    _apply_comments(conn, _SCHEMA_COMMENTS, clear=True)

