-- Создание таблицы gs_fue.gs_fue_equipment_group_extra_fuel_param
-- Использовать при отсутствии таблицы (ошибка: отношение не существует).
-- Идемпотентно: CREATE TABLE IF NOT EXISTS.

CREATE TABLE IF NOT EXISTS gs_fue.gs_fue_equipment_group_extra_fuel_param (
    id SERIAL PRIMARY KEY,
    id_equipment_group_set INTEGER REFERENCES gs_fue.gs_fue_equipment_group_sets(id) ON DELETE CASCADE,
    name VARCHAR(512),
    year_number INTEGER,
    gaz_prir NUMERIC(20,6),
    gazpp NUMERIC(20,6),
    disel NUMERIC(20,6),
    maztop NUMERIC(20,6),
    gtt NUMERIC(20,6),
    nft_proch NUMERIC(20,6),
    domen_g NUMERIC(20,6),
    koks_g NUMERIC(20,6),
    prochgaz NUMERIC(20,6),
    tvproch NUMERIC(20,6),
    szh_gaz NUMERIC(20,6),
    inoe NUMERIC(20,6),
    nazar NUMERIC(20,6),
    ibor NUMERIC(20,6),
    berez NUMERIC(20,6),
    per NUMERIC(20,6),
    irbei NUMERIC(20,6),
    kansk NUMERIC(20,6),
    gusin NUMERIC(20,6),
    tugn NUMERIC(20,6),
    okino NUMERIC(20,6),
    azey NUMERIC(20,6),
    mug NUMERIC(20,6),
    cher NUMERIC(20,6),
    jer NUMERIC(20,6),
    karab NUMERIC(20,6),
    vork NUMERIC(20,6),
    intin NUMERIC(20,6),
    sver NUMERIC(20,6),
    chel NUMERIC(20,6),
    kizel NUMERIC(20,6),
    har NUMERIC(20,6),
    urt NUMERIC(20,6),
    tataur NUMERIC(20,6),
    tarbag NUMERIC(20,6),
    zab_kam NUMERIC(20,6),
    rai NUMERIC(20,6),
    erk NUMERIC(20,6),
    ogodj NUMERIC(20,6),
    svo NUMERIC(20,6),
    bikin NUMERIC(20,6),
    razdol NUMERIC(20,6),
    hankai NUMERIC(20,6),
    neru NUMERIC(20,6),
    zyryan NUMERIC(20,6),
    pyak NUMERIC(20,6),
    kuzngd NUMERIC(20,6),
    kuznt NUMERIC(20,6),
    kuznss NUMERIC(20,6),
    kuznun NUMERIC(20,6),
    bering NUMERIC(20,6),
    anad NUMERIC(20,6),
    ekib NUMERIC(20,6),
    maikub NUMERIC(20,6),
    karag NUMERIC(20,6),
    karajyra NUMERIC(20,6),
    teniz NUMERIC(20,6),
    numb1120 INTEGER,
    numb1 INTEGER,
    database_version_id INTEGER REFERENCES gs_sys.gs_database_versions(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_equipment_group_extra_fuel_param_set_year UNIQUE (id_equipment_group_set, year_number)
);

CREATE INDEX IF NOT EXISTS ix_eg_extra_fuel_param_eg_set
    ON gs_fue.gs_fue_equipment_group_extra_fuel_param(id_equipment_group_set);
CREATE INDEX IF NOT EXISTS ix_eg_extra_fuel_param_year
    ON gs_fue.gs_fue_equipment_group_extra_fuel_param(year_number);
CREATE INDEX IF NOT EXISTS ix_eg_extra_fuel_param_numb1120
    ON gs_fue.gs_fue_equipment_group_extra_fuel_param(numb1120);
